#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to the tsEpistle 1-Click DigitalOcean Droplet.

To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (Docker) and 443 (Docker).

* tsEpistle source and release notes are available at:
  https://github.com/PhilosophiMoonbeam/tsEpistle

* Docker is installed and configured per Docker's recommendations:
  https://docs.docker.com/engine/install/ubuntu/

For more information, visit https://github.com/PhilosophiMoonbeam/tsEpistle

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
