extends:
  - requarks
  - plugin:vue/strongly-recommended
  - plugin:cypress/recommended
env:
  node: true
  jest: true
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2017
  allowImportExportEverywhere: true
globals:
  document: false
  navigator: false
  window: false
rules:
  vue/multi-word-component-names: off
  vue/custom-event-name-casing:
    - error
    - ignores:
        - searchEnter
        - searchMove
        - saveConflict
        - resetEditorConflict
        - overwriteEditorContent
        - editorInsert
        - pageEdit
        - pageHistory
        - pageSource
        - pageConvert
        - pageDuplicate
        - pageMove
        - pageDelete
