// Audited offline-only shell English, including shared account/header controls. Keep aligned with server/locales/en.json.
export const offlineEnglish = {
  "offlineApp": {
    "savedPageLinkInvalid": "This saved-page link is invalid. Choose a saved page below.",
    "offlineSynchronizationNotReady": "Offline synchronization is not ready yet.",
    "offlineStorageNotReady": "Offline storage is not ready yet.",
    "connectedAccountSavedPages": "Connected. Your account and saved pages can sync again.",
    "checkingConnectionSavedPages": "Checking connection. Your saved pages are available.",
    "serverUnavailableSavedPages": "The server is unavailable. Your saved pages are still available.",
    "youreOfflineSavedPages": "You’re offline. Saved pages are available; account actions and syncing will resume when you reconnect.",
    "savedPagesCouldNot": "Saved pages could not be opened on this device. Try again or reconnect.",
    "offlineAccess": "Offline access",
    "savedPages": "Saved pages",
    "skipContent": "Skip to content",
    "reconnect": "Reconnect",
    "openNavigation": "Open navigation"
  },
  "offlineLibrary": {
    "savedPage": "Saved page",
    "openPageOnlineSaved": "{{value}}\n\nOpen this page online, or from a saved copy on your device.",
    "offlineSyncHasNot": "Offline sync has not reported a status yet.",
    "pending": "{{pendingCount}} pending",
    "retained": "{{retainedCount}} retained",
    "removed": "{{removedCount}} removed",
    "lastSuccessfulSync": "Last successful sync {{lastSuccessAt}}.",
    "lastAttemptedSync": "Last attempted sync {{lastAttemptAt}}.",
    "sync": "Sync {{status}}: {{pending}}, {{retained}}, {{removed}}.{{timing}}{{error}}",
    "policyDetailsUnavailable": "Policy details unavailable",
    "manual": "Manual",
    "automatic": "Automatic",
    "tag": "Tag: {{tagNames}}",
    "tagSubscription": "Tag subscription",
    "noActiveIntent": "No active intent",
    "waitingSync": "Waiting for sync",
    "notEligible": "Not eligible",
    "savedCopyStale": "Saved copy is stale",
    "privateOfflineVaultCould": "The private offline vault could not be unlocked.",
    "checkingSavedPagesDevice": "Checking saved pages on this device.",
    "searchingSavedPage_one": "Searching {{count}} saved page…",
    "searchingSavedPage_other": "Searching {{count}} saved pages…",
    "searchCouldNotCompleted": "Search could not be completed. Your saved pages were not changed.",
    "noSavedPagesMatch": "No saved pages match “{{value}}”.",
    "moreMatchesAvailable": "More matches are available.",
    "matchingSavedPage_one": "{{count}} matching saved page.{{more}}",
    "matchingSavedPage_other": "{{count}} matching saved pages.{{more}}",
    "unlockPrivateReadingSee": "Unlock private reading to see pages saved for your account.",
    "noSavedPagesYet": "No saved pages yet.",
    "showingFirst50": "Showing the first 50.",
    "savedPageDevice_one": "{{count}} saved page on this device.{{more}}",
    "savedPageDevice_other": "{{count}} saved pages on this device.{{more}}",
    "checkingLocalStorageWithout": "Checking local storage without opening an account session.",
    "savedPagesUnavailableDevice": "Saved pages are unavailable on this device right now.",
    "readingSavedPagesWithout": "Reading saved pages without changing them…",
    "trySearchAgainSaved": "Try Search again. Saved pages remain unchanged.",
    "whenYouSaveEligible": "When you save an eligible public page, it appears here with its saved version and known expiry.",
    "tryDifferentPhraseClear": "Try a different phrase or clear the search to see every saved page.",
    "copyUnavailable": "Copy is unavailable.",
    "excerptPageLinkShared": "Excerpt and page link shared.",
    "sharingUnavailableCopyPage": "Sharing is unavailable. Copy the page link or full page text instead.",
    "pageLinkCopied": "Page link copied.",
    "pageLinkCouldNot": "The page link could not be copied.",
    "fullPageTextCopied": "Full page text copied.",
    "clipboardAccessWasDenied": "Clipboard access was denied. The full page text is selected below.",
    "savedPagesStillBeing": "Saved pages are still being checked.",
    "savedPageSearchCould": "Saved-page search could not be completed.",
    "openingSavedPage": "Opening the saved page…",
    "savedPageChangedExpired": "This saved page changed or expired before it finished opening.",
    "savedPageNoLonger": "This saved page is no longer available on this device.",
    "savedPageChangedBefore": "This saved page changed before it could be committed for reading.",
    "readingSavedVersionChanges": "Reading the saved version. Changes will sync when you reconnect.",
    "untitledPage": "Untitled page",
    "savedPageFailedIntegrity": "This saved page failed its integrity or safety checks.",
    "currentSiteIdentityUnavailable": "The current site identity is unavailable; saved pages cannot be opened safely.",
    "requestedSavedPageLink": "The requested saved-page link is invalid or belongs to another site.",
    "savedPagesChangedDevice": "Saved pages changed on this device. Retry opening this page to verify the new saved version.",
    "savedPagesCouldNot": "Saved pages could not be read from this device.",
    "offlineSynchronizationUnavailable": "Offline synchronization is unavailable.",
    "offlineSynchronizationCouldNot": "Offline synchronization could not be completed.",
    "savedPageRemovedLocally": "Saved page removed locally, but offline sync is unavailable: {{detail}}",
    "savedPageRemovedLocally2": "Saved page removed locally, but offline sync failed: {{detail}}",
    "savedPageRemovedLocally3": "Saved page removed locally, but offline sync failed: {{detail}}",
    "savedPagesCouldNot2": "Saved pages could not be refreshed.",
    "savedPageListCould": "{{syncFailure}} Saved-page list could not be refreshed: {{refillDetail}}",
    "savedPageRemovedLocally4": "Saved page removed locally, but the saved-page list could not be refreshed: {{refillDetail}}",
    "savedPageCouldNot": "The saved page could not be removed.",
    "automaticOfflineSavingWas": "Automatic offline saving was changed locally, but offline sync is unavailable: {{detail}}",
    "automaticOfflineSavingWas2": "Automatic offline saving was changed locally, but offline sync failed: {{detail}}",
    "automaticOfflineSavingCould": "Automatic offline saving could not be changed.",
    "offlineTagSubscriptionWas": "The offline tag subscription was removed locally, but offline sync is unavailable: {{detail}}",
    "offlineTagSubscriptionWas2": "The offline tag subscription was removed locally, but offline sync failed: {{detail}}",
    "offlineTagSubscriptionCould": "The offline tag subscription could not be removed.",
    "offlineSynchronizationCouldNot2": "Offline synchronization could not be refreshed.",
    "offlineSyncUnavailable": "Offline sync is unavailable: {{detail}}",
    "offlineSyncCouldNot": "Offline sync could not be refreshed: {{detail}}",
    "offlineSyncCouldNot2": "Offline sync could not be refreshed.",
    "offlineStorageUnavailable": "Offline storage is unavailable.",
    "deniedPageCouldNot": "The denied page could not be queued for another attempt.",
    "selectedPageCouldNot": "The selected page could not be removed.",
    "unknownSize": "unknown size",
    "dateUnavailable": "date unavailable",
    "noKnownExpiry": "No known expiry",
    "expired": "Expired",
    "expires": "Expires {{expiresAt}}",
    "unfollow": "Unfollow {{tag}}",
    "openSavedPage": "Open saved page {{title}}",
    "unlocking": "Unlocking…",
    "unlockPrivatePages": "Unlock private pages",
    "refreshing": "Refreshing…",
    "syncNow": "Sync now",
    "retrySync": "Retry sync",
    "removing": "Removing…",
    "removeExclude": "Remove / exclude",
    "sharing": "Sharing…",
    "sharePage": "Share page",
    "noMatchingSavedPages": "No matching saved pages",
    "privateSavedPagesLocked": "Private saved pages are locked",
    "noSavedPagesYet2": "No saved pages yet",
    "saved": "Saved {{capturedAt}}",
    "removePage": "Remove page",
    "savedPages": "Saved pages",
    "pagesAvailableDeviceSaved": "Pages available on this device. Your saved copies stay available while the connection is interrupted.",
    "enterDevicesPrivateReading": "Enter this device’s private reading secret to see your saved pages, even while offline.",
    "privateReadingSecret": "Private reading secret",
    "searchSavedPages": "Search saved pages",
    "device": "On this device",
    "whatGetsSaved": "What gets saved",
    "saveFrequentlyVisitedRecently": "Save frequently visited and recently edited pages",
    "defaultSaveUp10": "On by default. Save up to 10 eligible public pages, including your most recently edited page and the pages you visit most within 60 days. Removing a page excludes it from automatic saving and makes room for another. Manual saves and followed tags are managed separately.",
    "followedTags": "Followed tags",
    "browseTags": "Browse tags",
    "noneYet": "None yet",
    "needsAttention": "Needs attention",
    "selectedPagesWithoutSaved": "Selected pages without a saved copy",
    "waiting": "{{missingPolicyPagesCount}} waiting",
    "thesePagesSelectedOffline": "These pages are selected for offline saving, but their copies are not ready on this device. Reconnect and sync to make them available.",
    "page": "Page #{{pageId}} · {{locale}}",
    "savedVia": "Saved via: {{page}}",
    "checkingSavedPages": "Checking saved pages",
    "savedPagesUnavailable": "Saved pages are unavailable",
    "retrySavedPages": "Retry saved pages",
    "readingSavedPages": "Reading saved pages",
    "savedPagesCouldNot3": "Saved pages could not be read",
    "savedDevice": "Saved on this device",
    "copyPageLink": "Copy page link",
    "copyFullPageText": "Copy full page text",
    "backSavedPages": "Back to saved pages",
    "savedVersion": "Saved version",
    "provenance": "Provenance: {{selectedRecord}}",
    "availability": "Availability: {{selectedRecord}}",
    "retryOpeningPage": "Retry opening this page",
    "searchUnavailable": "Search is unavailable",
    "searchAgain": "Search again",
    "automaticSavingDefaultIncludes": "Automatic saving is on by default and includes frequently visited pages and your most recently edited eligible page. Manual downloads and followed tags are listed with their sources above.",
    "provenance2": "Provenance: {{record}}",
    "availability2": "Availability: {{record}}",
    "openPage": "Open page",
    "savedPageCount": "Saved page count",
    "searchDevice": "Search this device",
    "savedPageActions": "Saved page actions",
    "savedPageContent": "Saved page content",
    "fullSavedPageText": "Full saved page text for manual copying",
    "savedPublicPages": "Saved public pages",
    "scrollableCodeBlock": "Scrollable code block",
    "scrollableTable": "Scrollable table",
    "savedPageInvalidNo": "This saved page is invalid or no longer available to open.",
    "savedPageHasExpired": "This saved page has expired and cannot be opened.",
    "savedPagesChangedBefore": "Saved pages changed before this page could open. Try again.",
    "requestedSavedPageNo": "The requested saved page is no longer available on this device.",
    "pageHasNotBeen": "This page has not been saved on this device. You can open another saved page below or reconnect to continue."
  },
  "offlineNavigation": {
    "savedDevice": "Saved on this device",
    "checkingConnection": "Checking connection",
    "serverUnavailable": "Server unavailable",
    "youreOffline": "You’re offline",
    "savedPagesCouldNot": "Saved pages could not be read from this device.",
    "browse": "Browse",
    "onlyPagesSavedDevice": "Only pages saved on this device are listed.",
    "openingSavedPages": "Opening saved pages…",
    "tryAgain": "Try again",
    "noSavedPagesYet": "No saved pages yet. Save pages while connected to browse them here.",
    "private": "· Private",
    "browseSavedPages": "Browse saved pages",
    "savedPageCount": "Saved page count",
    "offlineAccess": "Offline access"
  },
  "offlineSettings": {
    "sCount_one": "",
    "sCount_other": "s",
    "offlineStorageHasNot": "Offline storage has not been checked yet.",
    "notSetUp": "Not set up",
    "locked": "Locked",
    "unlocked": "Unlocked",
    "unavailable": "Unavailable",
    "enablePrivateOfflineReading": "Enable private offline reading after the server verifies your account.",
    "privateVaultSavedDevice": "A private vault is saved on this device. Enter its secret to unlock private pages.",
    "privateOfflinePagesAvailable": "Private offline pages are available in this browser until you lock them.",
    "privateOfflineReadingUnavailable": "Private offline reading is unavailable until this device can open offline storage.",
    "browserStorage": "Browser storage: {{usageBytes}} of {{quotaBytes}}.",
    "savedPageUsing_one": "{{count}} saved page using {{managedBytes}}.{{capacity}}",
    "savedPageUsing_other": "{{count}} saved pages using {{managedBytes}}.{{capacity}}",
    "unknownSize": "unknown size",
    "savedDataNeedsNewer": "Your saved data needs a newer version of tsEpistle. Update the app to access it; your data has been preserved.",
    "anotherTabHoldingOffline": "Another tab is holding the offline database open. Close that tab or try again.",
    "browserDeclinedLocalStorage": "The browser declined local storage because its quota is full. No records were evicted silently.",
    "browserCouldNotOpen": "This browser could not open offline storage. Downloaded pages remain on the server.",
    "privateOfflineReadingUnavailable2": "Private offline reading is unavailable on this device.",
    "privateOfflineReadingEnabled": "Private offline reading is enabled on this device.",
    "privateOfflineReadingCould": "Private offline reading could not be enabled.",
    "confirmationCouldNotAccepted": "The confirmation could not be accepted.",
    "privateOfflineReadingUnlocked": "Private offline reading is unlocked in this browser.",
    "privateOfflineVaultCould": "The private offline vault could not be unlocked.",
    "privateOfflineReadingLocked": "Private offline reading is locked.",
    "openingOfflineStorage": "Opening offline storage…",
    "changesSavedAutomaticallyDevice": "Changes are saved automatically on this device.",
    "requestingPersistentStorage": "Requesting persistent storage…",
    "persistentStorageGrantedWas": "Persistent storage is granted or was accepted by the browser.",
    "persistentStorageWasNot": "Persistent storage was not granted. The browser may still retain your saved pages.",
    "synchronizationWillResumeWhen": "Synchronization will resume when the app reconnects.",
    "savedPagesWereRemoved": "Saved pages were removed, but local synchronization reported an error.",
    "savedPagesWereRemoved2": "Saved pages were removed, but local synchronization is unavailable: {{error}}",
    "savedPagesWereRemoved3": "Saved pages were removed. Local synchronization will resume when the server is reachable.",
    "savedPagesWereRemoved4": "Saved pages were removed. Locked drafts and submission recovery were not changed.",
    "clearingSavedPagesLocked": "Clearing saved pages, locked drafts, and submission recovery…",
    "offlineDataWasCleared": "Offline data was cleared on this device. Your server data was not deleted.",
    "persistentStorageEnabled": "Persistent storage is enabled.",
    "persistentStorageHasNot": "Persistent storage has not been granted by your browser.",
    "offlineAccess": "Offline access",
    "keepReadingWhenConnection": "Keep reading when your connection drops. These preferences apply to this browser and device.",
    "privateOfflineReading": "Private offline reading",
    "signReconnectOnceEnable": "Sign in and reconnect once to enable private offline reading. Public saved pages remain available.",
    "setUpPrivateReading": "Set up private reading",
    "unlockPrivatePages": "Unlock private pages",
    "privatePagesStayEncrypted": "Private pages stay in encrypted local storage and are not sent in URLs or logs.",
    "lockPrivatePages": "Lock private pages",
    "saveSecretSomewhereSafe": "Save this secret somewhere safe. It is shown once and cannot be recovered.",
    "confirmSave": "Confirm and save",
    "deviceStorage": "Device storage",
    "refreshStorage": "Refresh storage",
    "keepStorageDevice": "Keep storage on this device",
    "removeLocalData": "Remove local data",
    "removingSavedPagesLeaves": "Removing saved pages leaves your local drafts and submission recovery intact. Server data is unchanged.",
    "removeSavedPages": "Remove saved pages",
    "clearOfflineDataDevice": "Clear offline data on this device",
    "localDraftProtectedReconnect_one": "{{count}} local draft protected. Reconnect with the same account to access it.",
    "localDraftProtectedReconnect_other": "{{count}} local drafts protected. Reconnect with the same account to access them.",
    "clearOfflineDataDevice2": "Clear offline data on this device?",
    "removesSavedPagesLocal": "This removes saved pages, local drafts, and unresolved submission recovery from this browser. It does not delete anything from the server.",
    "clearOfflineData": "Clear offline data",
    "deviceSettings": "Device settings",
    "unlockSecret": "Unlock secret",
    "reEnterSecretExactly": "Re-enter secret exactly"
  },
  "actions": {
    "cancel": "Cancel"
  },
  "navHeader": {
    "checkingAccount": "Checking account…",
    "accountNotVerified": "Account not verified",
    "confirmingSessionServer": "Confirming your session with the server.",
    "reconnectVerifySessionOffline": "Reconnect to verify your session. Offline access is still available.",
    "ctrlK": "Ctrl K",
    "pageChangedBeforeMove": "The page changed before this move could be confirmed.",
    "pageMoveFailed": "Page move failed",
    "moveResponseCouldNot": "The move response could not be confirmed.",
    "moveReceiptCouldNot": "The move receipt could not be verified.",
    "globalPageAccountControls": "global page + account controls; only when the left cluster exists.",
    "developmentVersion": "DEVELOPMENT VERSION",
    "codeBaseNotProduction": "This code base is NOT for production use!"
  },
  "accountMenu": {
    "editPage": "Edit page",
    "openProfile": "Open profile for {{name}}",
    "lastVerifiedAccount": "Last verified account: {{name}}",
    "lastVerifiedDetail": "Last verified account · Reconnect for account actions",
    "sections": "Account menu sections",
    "appearanceSettings": "Appearance settings",
    "signingOut": "Signing out…",
    "reconnectToSignOut": "Reconnect to sign out.",
    "signIn": "Sign in",
    "label": "Account menu",
    "tabNotifications": "Notifications",
    "tabApprovals": "Approvals",
    "approvalsCount": "{{count}} active",
    "tabAppearance": "Appearance",
    "tabOffline": "Offline",
    "reasonConnection": "Reconnect to the server to use this.",
    "reasonSession": "Your sign-in must be checked again before you can use this."
  },
  "header": {
    "edit": "Edit",
    "home": "Home",
    "move": "Move / Rename",
    "view": "View",
    "admin": "Administration",
    "login": "Login",
    "assets": "Assets",
    "delete": "Delete",
    "logout": "Logout",
    "myWiki": "My Wiki",
    "search": "Search...",
    "searchModeLabel": "Choose Search or Ask",
    "searchMode": "Search",
    "askMode": "Ask",
    "askPlaceholder": "Ask Wiki Agent…",
    "account": "Account",
    "accountNotificationsAvailable": "{{account}}, Notifications available",
    "accountNotificationsUnknown": "{{account}}, Notification status not fully checked",
    "history": "History",
    "newPage": "New Page",
    "profile": "Profile",
    "siteMap": "Site Map",
    "language": "Language",
    "duplicate": "Duplicate",
    "browseTags": "Browse by Tags",
    "searchHint": "Type at least 2 characters to start searching...",
    "viewSource": "View Source",
    "currentPage": "Current Page",
    "imagesFiles": "Images & Files",
    "pageActions": "Page Actions",
    "searchClose": "Close",
    "searchLoading": "Searching...",
    "searchCopyLink": "Copy Search Link",
    "searchNoResult": "No pages matching your query.",
    "searchDidYouMean": "Did you mean...",
    "searchResultsCount": "Found {{total}} results",
    "breadcrumb": "Breadcrumb",
    "agent": "Wiki Agent",
    "agentOpen": "Open Wiki Agent",
    "searchOpen": "Open search",
    "searchCloseLabel": "Close search",
    "pageLoading": "Page loading"
  }
} as const
