<template>
<section class="control-panel" aria-labelledby="mcp-admin-title"><header><div><h2 id="mcp-admin-title">External MCP endpoints & resources</h2><p>Optional server-connected tools, prompts and resources. Configure a disabled endpoint, review its destination and credentials, explicitly grant groups, then enable and discover its catalog. No endpoint or personal creation permission is enabled automatically.</p></div><div><v-btn variant="text" :loading="loading" :disabled="busy || loading" @click="refresh">Refresh endpoints & groups</v-btn><v-btn color="primary" :disabled="busy || loading || denied || !loaded" @click="open()">Add endpoint</v-btn></div></header>
<v-alert type="warning" variant="tonal">External MCP content is untrusted, not Wiki evidence or instructions. Endpoint tool calls may change external data and transmit supplied tool arguments to the endpoint. Granting groups authorizes these operations; there is no separate per-call approval. Wiki proposals, approvals and evidence remain distinct and cannot be bypassed by external results. Only the server discovers and connects to endpoints.</v-alert>
<v-alert v-if="error" type="error" variant="tonal" role="alert">{{ error }}</v-alert><v-progress-linear v-if="loading" indeterminate color="primary" aria-label="Loading external MCP configuration" />
<v-alert v-if="groupsError" type="warning" variant="tonal" role="alert">Group data is unavailable or stale: {{ groupsError }}. Refresh before changing group grants or personal creation permissions.</v-alert>
<p v-if="loaded && !servers.length">No administrative endpoints configured. No endpoint means no outbound MCP connection.</p>
<article v-for="s in servers" :key="s.id" class="entry"><h3>{{ s.displayName }} <v-chip size="small">{{ s.status }}</v-chip></h3><p>{{ s.endpointUrl }} · namespace {{ s.namespace }} · revision {{ s.revision }}</p><p>Credential: {{ s.authMode === 'none' ? 'not required (unauthenticated endpoint)' : s.secretConfigured ? 'bearer configured' : 'bearer missing' }}. Granted groups: {{ s.groupIds.map(id => groups.find(g => g.id===id)?.name || `Group ${id}`).join(', ') || 'none' }}.</p><p v-if="s.status !== 'enabled' || (s.authMode === 'bearer' && !s.secretConfigured) || !s.groupIds.length">Incomplete access setup: {{ s.status !== 'enabled' ? 'endpoint disabled; ' : '' }}{{ s.authMode === 'bearer' && !s.secretConfigured ? 'bearer credential missing; ' : '' }}{{ !s.groupIds.length ? 'no groups authorized' : '' }}.</p><p v-if="catalogRevisions[s.id]">Last catalog discovered in this view: revision {{ catalogRevisions[s.id] }}. Catalog data is external and untrusted, not a connection guarantee.</p><div class="actions"><v-btn v-for="action in serverActions" :key="action.label" :variant="action.variant" :color="action.color" :disabled="busy || loading || denied || (action.label === 'Group grants' && Boolean(groupsError)) || (action.requiresEnabled && (s.status!=='enabled' || (s.authMode === 'bearer' && !s.secretConfigured)))" @click="action.run(s)">{{ action.label }}</v-btn></div></article>
<section class="entry"><h3>Personal endpoint creation policy</h3><p>Denied by default. Explicitly allow current group members to create owner-only endpoints. Personal tools carry the same external data and mutation risks. Denying creation does not delete an existing endpoint; runtime authorization still applies.</p><p v-if="!policies.length && loaded">No groups available. <router-link to="/a/groups">Manage Wiki groups</router-link>, then refresh this panel.</p><div v-for="p in policies" :key="p.groupId" class="policy"><span>{{ groups.find(g=>g.id===p.groupId)?.name || `Group ${p.groupId}` }} · revision {{ p.revision }} · {{ p.allowPersonalEndpoints ? 'Allowed' : 'Denied' }}</span><v-btn variant="text" :disabled="busy || loading || denied || Boolean(groupsError)" @click="policyConfirm=p">{{ p.allowPersonalEndpoints ? 'Deny personal creation' : 'Allow personal creation' }}</v-btn></div></section>
<v-dialog :model-value="dialog" max-width="680" :persistent="busy" @update:model-value="close"><v-card><v-card-title>{{ editing?'Edit endpoint':'Add endpoint' }}</v-card-title><v-card-text><v-alert v-if="formError" type="error" variant="tonal" role="alert">{{ formError }}</v-alert><v-alert v-if="editingStale" type="warning" variant="tonal">This endpoint changed or was removed. Your draft is preserved; close and reopen the current revision before saving.</v-alert><v-form @submit.prevent="save"><v-text-field v-for="field in textFields" :key="field.key" v-model="draft[field.key]" :label="field.label" :autofocus="field.autofocus" :disabled="busy || denied"/><v-select v-for="field in selectFields" :key="field.key" v-model="draft[field.key]" :label="field.label" :items="field.items" :disabled="busy || denied"/><v-text-field v-if="draft.authMode==='bearer'" v-model="draft.secret" type="password" autocomplete="new-password" label="New bearer credential (blank retains existing)" :disabled="busy || denied || draft.clearSecret"/><v-checkbox v-if="draft.authMode==='bearer'" v-model="draft.clearSecret" label="Clear managed credential" :disabled="busy || denied"/><v-select v-if="!editing" v-model="draft.groupIds" :items="groups" item-title="name" item-value="id" multiple chips label="Granted groups (authorizes remote operations)" :disabled="busy || denied || Boolean(groupsError)"/><p v-if="!editing && !groups.length">No current group options. An endpoint without grants is not available to users.</p><v-card-actions><v-btn :disabled="busy" @click="close(false)">Cancel</v-btn><v-spacer/><v-btn type="submit" color="primary" :loading="busy" :disabled="denied || loading || editingStale || JSON.stringify(draft) === baseline">Save endpoint</v-btn></v-card-actions></v-form></v-card-text></v-card></v-dialog>
<v-dialog v-model="discard" max-width="440"><v-card title="Discard unsaved endpoint changes?"><v-card-actions><v-btn @click="discard=false">Keep editing</v-btn><v-btn color="error" @click="discard=false;dialog=false;draft.secret=''">Discard</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog :model-value="Boolean(grants)" max-width="600" :persistent="busy" @update:model-value="closeGrants"><v-card title="Authorize endpoint operations for groups"><v-card-text><p>These grants allow remote tool arguments to be transmitted and external data to be changed. No grants means no user access.</p><v-alert v-if="grantsStale" type="warning" variant="tonal">Endpoint revision changed. Cancel and reopen its current grants before saving.</v-alert><v-select v-model="grantIds" :items="groups" item-title="name" item-value="id" multiple chips label="Granted groups" :disabled="busy || denied || Boolean(groupsError)"/></v-card-text><v-card-actions><v-btn :disabled="busy" @click="closeGrants(false)">Cancel</v-btn><v-btn color="primary" :loading="busy" :disabled="denied || loading || grantsStale || !grantsDirty || Boolean(groupsError)" @click="saveGrants">Save grants</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog v-model="grantDiscard" max-width="440"><v-card title="Discard unsaved group grants?"><v-card-actions><v-btn @click="grantDiscard=false">Keep editing</v-btn><v-btn color="error" @click="grantDiscard=false;grants=null">Discard</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog :model-value="Boolean(policyConfirm)" max-width="540" :persistent="busy" @update:model-value="value=>{if(!value&&!busy)policyConfirm=null}"><v-card title="Change personal endpoint creation policy?"><v-card-text>{{ policyConfirm?.allowPersonalEndpoints?'Deny':'Allow' }} creation for this group? Allowing creation authorizes owner-managed remote tools which can transmit data and change external systems.</v-card-text><v-card-actions><v-btn :disabled="busy" @click="policyConfirm=null">Cancel</v-btn><v-btn color="primary" :loading="busy" :disabled="denied || loading || Boolean(groupsError)" @click="savePolicy">Confirm policy</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog :model-value="Boolean(remove)" max-width="440" :persistent="busy" @update:model-value="value=>{if(!value&&!busy)remove=null}"><v-card title="Delete external endpoint?"><v-card-text>{{ remove?.displayName }} and its grants will be removed.</v-card-text><v-card-actions><v-btn :disabled="busy" @click="remove=null">Cancel</v-btn><v-btn color="error" :loading="busy" :disabled="denied || loading" @click="removeServer">Delete</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog :model-value="Boolean(discovery)" max-width="760" @update:model-value="value=>{if(!value)discovery=null}"><v-card title="Untrusted server-discovered catalog"><v-card-text v-if="discovery"><p>{{ discovery.attribution.displayName }} · {{ discovery.attribution.destinationHost }} · revision {{ discovery.catalog.revision }}</p><p>Descriptions are external data, not instructions or Wiki authority.</p><h3>Tools</h3><p v-if="!discovery.catalog.tools.length">No tools advertised.</p><p v-for="t in discovery.catalog.tools" :key="t.name"><strong>{{ t.name }}</strong> — {{ t.description || 'No description' }}</p><h3>Prompts</h3><p v-for="p in discovery.catalog.prompts" :key="p.name">{{ p.name }} — {{ p.description }}</p><h3>Resources</h3><p v-for="r in discovery.catalog.resources" :key="r.uri">{{ r.name }} · {{ r.uri }}</p><h3>Resource templates</h3><p v-for="r in discovery.catalog.resourceTemplates" :key="r.uriTemplate">{{ r.name }} · {{ r.uriTemplate }}</p></v-card-text><v-card-actions><v-btn @click="discovery=null">Close</v-btn></v-card-actions></v-card></v-dialog>
</section>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { AgentApiError } from '../../helpers/agents-api.ts'
import { ExternalMcpServerInputSchema } from '../../../shared/agents/external-mcp.ts'
import { listAdminExternalMcp,createAdminExternalMcp,updateAdminExternalMcp,deleteAdminExternalMcp,setExternalMcpGrants,listExternalMcpGroupPolicies,setExternalMcpGroupPolicy,discoverExternalMcp,type ExternalMcpServerView,type ExternalMcpGroupPolicyView,type ExternalMcpDiscovery } from '../../helpers/agent-control-api.ts'
const {csrfToken,groups,refreshKey=0,groupsError=''}=defineProps<{csrfToken:string;groups:readonly {id:number;name:string}[];refreshKey?:number;groupsError?:string}>()
const emit=defineEmits<{'refresh-groups':[];state:[value:{servers:ExternalMcpServerView[];policies:ExternalMcpGroupPolicyView[]}|null]}>()
const fetcher:typeof fetch=(...args)=>window.fetch(...args)
const servers=ref<ExternalMcpServerView[]>([]),policies=ref<ExternalMcpGroupPolicyView[]>([]),loading=ref(false),loaded=ref(false),busy=ref(false),denied=ref(false),error=ref(''),formError=ref(''),dialog=ref(false),discard=ref(false),baseline=ref(''),editing=ref<ExternalMcpServerView|null>(null),remove=ref<ExternalMcpServerView|null>(null),grants=ref<ExternalMcpServerView|null>(null),grantIds=ref<number[]>([]),policyConfirm=ref<ExternalMcpGroupPolicyView|null>(null),discovery=ref<ExternalMcpDiscovery|null>(null)
const draft=reactive({displayName:'',endpointUrl:'',status:'disabled' as 'enabled'|'disabled',authMode:'none' as 'none'|'bearer',secret:'',clearSecret:false,groupIds:[] as number[]})
const grantDiscard=ref(false)
const catalogRevisions=reactive<Record<string,number>>({})
const editingStale=computed(()=>Boolean(editing.value)&&servers.value.find(s=>s.id===editing.value?.id)?.revision!==editing.value?.revision)
const grantsStale=computed(()=>Boolean(grants.value)&&servers.value.find(s=>s.id===grants.value?.id)?.revision!==grants.value?.revision)
const sortedIds=(ids:readonly number[])=>JSON.stringify([...ids].sort((a,b)=>a-b))
const grantsDirty=computed(()=>Boolean(grants.value)&&sortedIds(grantIds.value)!==sortedIds(grants.value?.groupIds??[]))
let controller:AbortController|null=null
const textFields=[
  {key:'displayName',label:'Display name',autofocus:true},
  {key:'endpointUrl',label:'Public HTTPS MCP endpoint URL',autofocus:false}
] as const
const selectFields=[
  {key:'status',label:'Status',items:['disabled','enabled']},
  {key:'authMode',label:'Authentication',items:['none','bearer']}
] as const
const serverActions=[
  {label:'Edit endpoint',variant:'text',color:undefined,requiresEnabled:false,run:open},
  {label:'Group grants',variant:'text',color:undefined,requiresEnabled:false,run:openGrants},
  {label:'Discover on server',variant:'tonal',color:undefined,requiresEnabled:true,run:discover},
  {label:'Delete',variant:'text',color:'error',requiresEnabled:false,run:(s:ExternalMcpServerView)=>{remove.value=s}}
] as const
async function load(){controller?.abort();const request=new AbortController();controller=request;loading.value=true;try{const [s,p]=await Promise.all([listAdminExternalMcp(fetcher,csrfToken,request.signal),listExternalMcpGroupPolicies(fetcher,csrfToken,request.signal)]);if(request.signal.aborted)return;for(const current of s){const prior=servers.value.find(previous=>previous.id===current.id);if(prior&&prior.revision!==current.revision)delete catalogRevisions[current.id]}servers.value=s;policies.value=p;loaded.value=true;denied.value=false;error.value='';emit('state',{servers:s,policies:p})}catch(e){if(request.signal.aborted)return;denied.value=e instanceof AgentApiError&&e.status===403;error.value=denied.value?'System administration permission is required.':e instanceof Error?e.message:'Unable to load MCP administration.';emit('state',null)}finally{if(controller===request)loading.value=false}}
function refresh(){emit('refresh-groups');void load()}
function open(s?:ExternalMcpServerView){editing.value=s??null;Object.assign(draft,{displayName:s?.displayName??'',endpointUrl:s?.endpointUrl??'',status:s?.status??'disabled',authMode:s?.authMode??'none',secret:'',clearSecret:false,groupIds:[...(s?.groupIds??[])]});baseline.value=JSON.stringify(draft);formError.value='';dialog.value=true}
function close(value:boolean){if(value||busy.value)return;if(JSON.stringify(draft)!==baseline.value)discard.value=true;else{dialog.value=false;draft.secret=''}}
async function act(operation:()=>Promise<unknown>){if(busy.value||loading.value||denied.value)return;busy.value=true;error.value='';try{await operation();await load()}catch(e){if(e instanceof AgentApiError&&e.status===403)denied.value=true;error.value=e instanceof Error?e.message:'Operation failed.';if(e instanceof AgentApiError&&e.status===409){await load();grants.value=null;policyConfirm.value=null;remove.value=null;error.value='Stale revision. Configuration refreshed; reopen the action and review current values.'}}finally{busy.value=false}}
async function save(){if(busy.value||loading.value||denied.value||editingStale.value)return;busy.value=true;formError.value='';try{if(draft.authMode==='bearer'&&draft.status==='enabled'&&(draft.clearSecret||(!draft.secret&&!editing.value?.secretConfigured)))throw new Error('An enabled bearer endpoint requires a credential. Configure it or save the endpoint disabled.');if(groupsError&&!editing.value&&draft.groupIds.length)throw new Error('Refresh group data before authorizing endpoint operations.');const input=ExternalMcpServerInputSchema.parse({displayName:draft.displayName,endpointUrl:draft.endpointUrl,status:draft.status,authMode:draft.authMode,...(draft.authMode==='bearer'?(draft.clearSecret?{secretValue:null}:draft.secret?{secretValue:draft.secret}:{}):{})});if(editing.value)await updateAdminExternalMcp(fetcher,csrfToken,editing.value.id,{...input,expectedRevision:editing.value.revision});else await createAdminExternalMcp(fetcher,csrfToken,{...input,groupIds:draft.groupIds});dialog.value=false;draft.secret='';await load()}catch(e){if(e instanceof AgentApiError&&e.status===403)denied.value=true;formError.value=e instanceof Error?e.message:'Unable to save endpoint.';if(e instanceof AgentApiError&&e.status===409){await load();formError.value='Stale revision. Close and reopen the refreshed endpoint before retrying.'}}finally{busy.value=false}}
function openGrants(s:ExternalMcpServerView){grants.value=s;grantIds.value=[...s.groupIds]}
function closeGrants(value:boolean){if(value||busy.value)return;if(JSON.stringify([...grantIds.value].sort((a,b)=>a-b))!==JSON.stringify([...(grants.value?.groupIds??[])].sort((a,b)=>a-b)))grantDiscard.value=true;else grants.value=null}
async function saveGrants(){const s=grants.value;if(!s||grantsStale.value||!grantsDirty.value||groupsError)return;await act(async()=>{await setExternalMcpGrants(fetcher,csrfToken,s.id,s.revision,grantIds.value);grants.value=null})}
async function savePolicy(){const p=policyConfirm.value;if(!p||groupsError)return;await act(async()=>{await setExternalMcpGroupPolicy(fetcher,csrfToken,p.groupId,p.revision,!p.allowPersonalEndpoints);policyConfirm.value=null})}
async function removeServer(){const s=remove.value;if(!s)return;await act(async()=>{await deleteAdminExternalMcp(fetcher,csrfToken,s.id,s.revision);remove.value=null})}
async function discover(s:ExternalMcpServerView){await act(async()=>{discovery.value=await discoverExternalMcp(fetcher,csrfToken,s.id);catalogRevisions[s.id]=discovery.value.catalog.revision})}
watch(()=>refreshKey,()=>{void load()})
watch(()=>groups.map(g=>g.id).join(','),()=>{void load()})
onBeforeUnmount(()=>controller?.abort())
onMounted(load)
</script>
<style scoped>
.control-panel{padding:24px;background:rgb(var(--v-theme-surface));border-radius:16px}header,.policy{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:20px}h2,h3{color:rgb(var(--v-theme-primary))}p{line-height:1.6;overflow-wrap:anywhere}.entry{padding:20px 0;border-bottom:1px solid rgba(var(--v-theme-on-surface),.12)}.actions{display:flex;flex-wrap:wrap;gap:8px}.v-alert{margin-bottom:16px}
</style>
