<template>
<section class="control-panel" aria-labelledby="routing-title"><header><div><h2 id="routing-title">Per-turn model routing</h2><p>Declare task sufficiency for current model versions and configure conservative cost-aware selection.</p></div><v-btn variant="text" :loading="loading" :disabled="busy" @click="load">Refresh policy</v-btn></header>
<v-alert type="info" variant="tonal">Routing switches models only between durable turns, never during approval replay. Explicit conversation model choices stay pinned. Only models currently authorized for each user qualify. Unknown sufficiency or pricing excludes alternatives; the authorized current model remains the safe fallback. Native cost estimates are not billing; configured latency is an estimate, not a measured performance claim.</v-alert>
<v-alert v-if="error" type="error" variant="tonal" role="alert">{{ error }}</v-alert><v-progress-linear v-if="loading" indeterminate color="primary" aria-label="Loading routing policy"/>
<v-form v-if="policy" @submit.prevent="savePolicy"><h3>Routing policy · revision {{ policy.revision }}</h3><v-checkbox v-model="draft.enabled" label="Enable automatic routing" :disabled="busy || denied"/><v-select v-model="draft.decisionProviderId" :items="providers" item-title="displayName" item-value="id" clearable label="Decision provider (blank uses default)" :disabled="busy || denied"/>
<div class="fields"><v-text-field v-model.number="draft.minimumConfidence" type="number" step="0.01" label="Minimum classifier confidence (0.8–1)" :disabled="busy || denied"/><v-text-field v-model.number="draft.minimumSavingsRatio" type="number" step="0.01" label="Minimum savings ratio (0.05–1)" :disabled="busy || denied"/><v-text-field v-model.number="draft.minimumSavingsMicros" type="number" label="Minimum savings (µUSD estimate)" :disabled="busy || denied"/><v-text-field v-model.number="draft.switchCostMicros" type="number" label="Switching loss allowance (µUSD estimate)" :disabled="busy || denied"/><v-text-field v-model.number="draft.classifierMaxStateBytes" type="number" label="Bounded classifier state bytes (256–16384)" :disabled="busy || denied"/></div><v-btn type="submit" color="primary" :loading="busy" :disabled="denied || loading">Save routing policy</v-btn></v-form>
<section class="entry"><h3>Model task declarations</h3><p>Declarations bind an immutable current profile version. Changing the profile invalidates the old declaration; review and redeclare rather than inheriting unproven capability.</p><p v-if="!profiles.length">No conversation model profiles available.</p><article v-for="p in profiles" :key="p.id" class="entry"><h4>{{ p.displayName }} · {{ p.model }}</h4><p>Current version: <code>{{ p.profileVersionId || 'unavailable' }}</code></p><template v-if="declarations.find(m=>m.profileId===p.id)"><p>Declared version: {{ declarations.find(m=>m.profileId===p.id)?.profileVersionId }} · revision {{ declarations.find(m=>m.profileId===p.id)?.revision }} <strong v-if="declarations.find(m=>m.profileId===p.id)?.profileVersionId!==p.profileVersionId">(stale; not eligible)</strong></p><p>{{ declarations.find(m=>m.profileId===p.id)?.acceptableTasks.map(t=>`${t.taskClass}: ${t.complexities.join(', ')}`).join(' · ') }}</p><p>Configured latency estimate: {{ declarations.find(m=>m.profileId===p.id)?.estimatedLatencyMs ?? 'unknown' }} {{ declarations.find(m=>m.profileId===p.id)?.estimatedLatencyMs ? 'ms' : '' }}</p></template><p v-else>No declared task sufficiency. This model is not an automatic alternative.</p><v-btn variant="tonal" :disabled="busy || denied || !policy || !p.profileVersionId" @click="open(p)">Declare current version</v-btn><v-btn v-if="declarations.some(m=>m.profileId===p.id)" variant="text" color="error" :disabled="busy || denied" @click="remove=declarations.find(m=>m.profileId===p.id) || null">Remove declaration</v-btn></article>
<article v-for="m in declarations.filter(m=>!profiles.some(p=>p.id===m.profileId))" :key="m.profileId" class="entry"><p>Unavailable profile {{ m.profileId }} · revision {{ m.revision }}. This declaration does not authorize a model.</p><v-btn variant="text" color="error" :disabled="busy || denied" @click="remove=m">Remove declaration</v-btn></article></section>
<v-dialog :model-value="dialog" max-width="720" :persistent="busy" @update:model-value="close"><v-card title="Declare current model task sufficiency"><v-card-text><p>{{ selected?.displayName }} · {{ selected?.model }}</p><p>Immutable current version {{ selected?.profileVersionId }}</p><v-alert v-if="formError" type="error" variant="tonal" role="alert">{{ formError }}</v-alert><v-form @submit.prevent="saveModel"><div v-for="task in ROUTING_TASK_CLASSES" :key="task"><v-select v-model="tasks[task]" :items="ROUTING_COMPLEXITIES" multiple chips :label="`${task} — acceptable complexities`" :disabled="busy"/></div><v-text-field v-model="latency" type="number" label="Optional configured latency estimate (milliseconds; blank = unknown)" :disabled="busy"/><v-card-actions><v-btn :disabled="busy" @click="close(false)">Cancel</v-btn><v-spacer/><v-btn type="submit" color="primary" :loading="busy">Save declaration</v-btn></v-card-actions></v-form></v-card-text></v-card></v-dialog>
<v-dialog v-model="discard" max-width="440"><v-card title="Discard unsaved declaration?"><v-card-actions><v-btn @click="discard=false">Keep editing</v-btn><v-btn color="error" @click="discard=false;dialog=false">Discard</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog :model-value="Boolean(remove)" max-width="440" :persistent="busy" @update:model-value="value=>{if(!value&&!busy)remove=null}"><v-card title="Remove task declaration?"><v-card-text>The model will no longer qualify as an automatic alternative through this declaration.</v-card-text><v-card-actions><v-btn :disabled="busy" @click="remove=null">Cancel</v-btn><v-btn color="error" :loading="busy" @click="removeModel">Remove</v-btn></v-card-actions></v-card></v-dialog>
</section>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { AgentApiError } from '../../helpers/agents-api.ts'
import { DEFAULT_ROUTING_POLICY,ROUTING_TASK_CLASSES,ROUTING_COMPLEXITIES,RoutingPolicyInputSchema,RoutingModelPolicyInputSchema,type RoutingTaskClass,type RoutingComplexity } from '../../../shared/agents/routing.ts'
import { getAgentRouting,updateAgentRouting,setAgentRoutingModel,deleteAgentRoutingModel,listDecisionProviders,type RoutingPolicyView,type RoutingModelPolicyView,type DecisionProviderView } from '../../helpers/agent-control-api.ts'
interface ModelProfile {id:string;displayName:string;model:string;profileVersionId?:string}
const {csrfToken,profiles}=defineProps<{csrfToken:string;profiles:readonly ModelProfile[]}>()
const emit=defineEmits<{ 'refresh-profiles': [] }>()
const fetcher:typeof fetch=(...args)=>window.fetch(...args)
const loading=ref(false),busy=ref(false),denied=ref(false),error=ref(''),formError=ref(''),policy=ref<RoutingPolicyView|null>(null),declarations=ref<RoutingModelPolicyView[]>([]),providers=ref<DecisionProviderView[]>([]),selected=ref<ModelProfile|null>(null),remove=ref<RoutingModelPolicyView|null>(null),dialog=ref(false),discard=ref(false),baseline=ref(''),latency=ref(''),expectedRevision=ref(0)
const draft=reactive({...DEFAULT_ROUTING_POLICY})
const tasks=reactive<Record<RoutingTaskClass,RoutingComplexity[]>>({conversation:[],retrieval:[],writing:[],coding:[],analysis:[],planning:[]})
async function load(){loading.value=true;emit('refresh-profiles');try{const [r,p]=await Promise.all([getAgentRouting(fetcher,csrfToken),listDecisionProviders(fetcher,csrfToken)]);policy.value=r.policy;declarations.value=r.models;providers.value=p;const {revision,updatedAt,...input}=r.policy;Object.assign(draft,input);denied.value=false;error.value=''}catch(e){denied.value=e instanceof AgentApiError&&e.status===403;error.value=denied.value?'System administration permission is required.':e instanceof Error?e.message:'Unable to load routing policy.'}finally{loading.value=false}}
async function savePolicy(){if(busy.value||!policy.value)return;busy.value=true;error.value='';try{await updateAgentRouting(fetcher,csrfToken,{...RoutingPolicyInputSchema.parse(draft),expectedRevision:policy.value.revision});await load()}catch(e){error.value=e instanceof Error?e.message:'Unable to save routing policy.';if(e instanceof AgentApiError&&e.status===409){await load();error.value='Stale policy revision. Refreshed current policy; review before saving again.'}}finally{busy.value=false}}
function open(p:ModelProfile){selected.value={...p};const existing=declarations.value.find(m=>m.profileId===p.id);expectedRevision.value=existing?.revision??0;for(const task of ROUTING_TASK_CLASSES)tasks[task]=[...(existing?.acceptableTasks.find(t=>t.taskClass===task)?.complexities??[])];latency.value=existing?.estimatedLatencyMs?.toString()??'';baseline.value=JSON.stringify({tasks,latency:latency.value});formError.value='';dialog.value=true}
function close(value:boolean){if(value||busy.value)return;if(JSON.stringify({tasks,latency:latency.value})!==baseline.value)discard.value=true;else dialog.value=false}
async function saveModel(){if(busy.value||!selected.value?.profileVersionId)return;busy.value=true;formError.value='';try{const input=RoutingModelPolicyInputSchema.parse({profileVersionId:selected.value.profileVersionId,acceptableTasks:ROUTING_TASK_CLASSES.filter(task=>tasks[task].length).map(task=>({taskClass:task,complexities:tasks[task]})),estimatedLatencyMs:latency.value.trim()?Number(latency.value):null});await setAgentRoutingModel(fetcher,csrfToken,selected.value.id,{...input,expectedRevision:expectedRevision.value});dialog.value=false;await load()}catch(e){formError.value=e instanceof Error?e.message:'Unable to save declaration.';if(e instanceof AgentApiError&&e.status===409){await load();formError.value='Stale declaration or profile version. Refresh model profiles, then close and reopen this declaration before retrying.'}}finally{busy.value=false}}
async function removeModel(){const m=remove.value;if(busy.value||!m)return;busy.value=true;error.value='';try{await deleteAgentRoutingModel(fetcher,csrfToken,m.profileId,m.revision);remove.value=null;await load()}catch(e){error.value=e instanceof Error?e.message:'Unable to remove declaration.';if(e instanceof AgentApiError&&e.status===409){await load();remove.value=null;error.value='Stale revision. Refreshed declarations; review before retrying.'}}finally{busy.value=false}}
onMounted(load)
</script>
<style scoped>
.control-panel{padding:24px;background:rgb(var(--v-theme-surface));border-radius:16px}header{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:20px}h2,h3,h4{color:rgb(var(--v-theme-primary))}p{line-height:1.6;overflow-wrap:anywhere}.entry{padding:20px 0;border-bottom:1px solid rgba(var(--v-theme-on-surface),.12)}.fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.v-alert{margin-bottom:16px}
</style>
