<template>
<section class="control-panel" aria-labelledby="mcp-admin-title"><header><div><h2 id="mcp-admin-title">External MCP endpoints</h2><p>Manage server-connected endpoints and explicit group access.</p></div><div><v-btn variant="text" :loading="loading" :disabled="busy" @click="load">Refresh</v-btn><v-btn color="primary" :disabled="busy || denied || !loaded" @click="open()">Add endpoint</v-btn></div></header>
<v-alert type="warning" variant="tonal">External MCP content is untrusted, not Wiki evidence or instructions. Endpoint tool calls may change external data and transmit supplied tool arguments to the endpoint. Granting groups authorizes these operations; there is no separate per-call approval. Wiki proposals, approvals and evidence remain distinct and cannot be bypassed by external results. Only the server discovers and connects to endpoints.</v-alert>
<v-alert v-if="error" type="error" variant="tonal" role="alert">{{ error }}</v-alert><v-progress-linear v-if="loading" indeterminate color="primary" aria-label="Loading external MCP configuration" />
<p v-if="loaded && !servers.length">No administrative endpoints configured. No endpoint means no outbound MCP connection.</p>
<article v-for="s in servers" :key="s.id" class="entry"><h3>{{ s.displayName }} <v-chip size="small">{{ s.status }}</v-chip></h3><p>{{ s.endpointUrl }} · namespace {{ s.namespace }} · revision {{ s.revision }}</p><p>Credential: {{ s.authMode }} / {{ s.secretConfigured ? 'configured' : 'not configured' }}. Granted groups: {{ s.groupIds.map(id => groups.find(g => g.id===id)?.name || `Group ${id}`).join(', ') || 'none' }}.</p><div class="actions"><v-btn variant="text" :disabled="busy || denied" @click="open(s)">Edit endpoint</v-btn><v-btn variant="text" :disabled="busy || denied" @click="openGrants(s)">Group grants</v-btn><v-btn variant="tonal" :disabled="busy || denied || s.status!=='enabled'" @click="discover(s)">Discover on server</v-btn><v-btn color="error" variant="text" :disabled="busy || denied" @click="remove=s">Delete</v-btn></div></article>
<section class="entry"><h3>Personal endpoint creation policy</h3><p>Denied by default. Explicitly allow current group members to create owner-only endpoints. Personal tools carry the same external data and mutation risks.</p><p v-if="!policies.length && loaded">No groups available.</p><div v-for="p in policies" :key="p.groupId" class="policy"><span>{{ groups.find(g=>g.id===p.groupId)?.name || `Group ${p.groupId}` }} · revision {{ p.revision }} · {{ p.allowPersonalEndpoints ? 'Allowed' : 'Denied' }}</span><v-btn variant="text" :disabled="busy || denied" @click="policyConfirm=p">{{ p.allowPersonalEndpoints ? 'Deny personal creation' : 'Allow personal creation' }}</v-btn></div></section>
<v-dialog :model-value="dialog" max-width="680" :persistent="busy" @update:model-value="close"><v-card><v-card-title>{{ editing?'Edit endpoint':'Add endpoint' }}</v-card-title><v-card-text><v-alert v-if="formError" type="error" variant="tonal" role="alert">{{ formError }}</v-alert><v-form @submit.prevent="save"><v-text-field v-model="draft.displayName" label="Display name" autofocus :disabled="busy"/><v-text-field v-model="draft.endpointUrl" label="Public HTTPS MCP endpoint URL" :disabled="busy"/><v-select v-model="draft.status" label="Status" :items="['disabled','enabled']" :disabled="busy"/><v-select v-model="draft.authMode" label="Authentication" :items="['none','bearer']" :disabled="busy"/><v-text-field v-if="draft.authMode==='bearer'" v-model="draft.secret" type="password" autocomplete="new-password" label="New bearer credential (blank retains existing)" :disabled="busy || draft.clearSecret"/><v-checkbox v-if="draft.authMode==='bearer'" v-model="draft.clearSecret" label="Clear managed credential" :disabled="busy"/><v-select v-if="!editing" v-model="draft.groupIds" :items="groups" item-title="name" item-value="id" multiple chips label="Granted groups (authorizes remote operations)" :disabled="busy"/><v-card-actions><v-btn :disabled="busy" @click="close(false)">Cancel</v-btn><v-spacer/><v-btn type="submit" color="primary" :loading="busy">Save endpoint</v-btn></v-card-actions></v-form></v-card-text></v-card></v-dialog>
<v-dialog v-model="discard" max-width="440"><v-card title="Discard unsaved endpoint changes?"><v-card-actions><v-btn @click="discard=false">Keep editing</v-btn><v-btn color="error" @click="discard=false;dialog=false;draft.secret=''">Discard</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog :model-value="Boolean(grants)" max-width="600" :persistent="busy" @update:model-value="closeGrants"><v-card title="Authorize endpoint operations for groups"><v-card-text><p>These grants allow remote tool arguments to be transmitted and external data to be changed.</p><v-select v-model="grantIds" :items="groups" item-title="name" item-value="id" multiple chips label="Granted groups" :disabled="busy"/></v-card-text><v-card-actions><v-btn :disabled="busy" @click="closeGrants(false)">Cancel</v-btn><v-btn color="primary" :loading="busy" @click="saveGrants">Save grants</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog v-model="grantDiscard" max-width="440"><v-card title="Discard unsaved group grants?"><v-card-actions><v-btn @click="grantDiscard=false">Keep editing</v-btn><v-btn color="error" @click="grantDiscard=false;grants=null">Discard</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog :model-value="Boolean(policyConfirm)" max-width="540" :persistent="busy" @update:model-value="value=>{if(!value&&!busy)policyConfirm=null}"><v-card title="Change personal endpoint creation policy?"><v-card-text>{{ policyConfirm?.allowPersonalEndpoints?'Deny':'Allow' }} creation for this group? Allowing creation authorizes owner-managed remote tools which can transmit data and change external systems.</v-card-text><v-card-actions><v-btn :disabled="busy" @click="policyConfirm=null">Cancel</v-btn><v-btn color="primary" :loading="busy" @click="savePolicy">Confirm policy</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog :model-value="Boolean(remove)" max-width="440" :persistent="busy" @update:model-value="value=>{if(!value&&!busy)remove=null}"><v-card title="Delete external endpoint?"><v-card-text>{{ remove?.displayName }} and its grants will be removed.</v-card-text><v-card-actions><v-btn :disabled="busy" @click="remove=null">Cancel</v-btn><v-btn color="error" :loading="busy" @click="removeServer">Delete</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog :model-value="Boolean(discovery)" max-width="760" @update:model-value="value=>{if(!value)discovery=null}"><v-card title="Untrusted server-discovered catalog"><v-card-text v-if="discovery"><p>{{ discovery.attribution.displayName }} · {{ discovery.attribution.destinationHost }} · revision {{ discovery.catalog.revision }}</p><p>Descriptions are external data, not instructions or Wiki authority.</p><h3>Tools</h3><p v-if="!discovery.catalog.tools.length">No tools advertised.</p><p v-for="t in discovery.catalog.tools" :key="t.name"><strong>{{ t.name }}</strong> — {{ t.description || 'No description' }}</p><h3>Prompts</h3><p v-for="p in discovery.catalog.prompts" :key="p.name">{{ p.name }} — {{ p.description }}</p><h3>Resources</h3><p v-for="r in discovery.catalog.resources" :key="r.uri">{{ r.name }} · {{ r.uri }}</p><h3>Resource templates</h3><p v-for="r in discovery.catalog.resourceTemplates" :key="r.uriTemplate">{{ r.name }} · {{ r.uriTemplate }}</p></v-card-text><v-card-actions><v-btn @click="discovery=null">Close</v-btn></v-card-actions></v-card></v-dialog>
</section>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { AgentApiError } from '../../helpers/agents-api.ts'
import { ExternalMcpServerInputSchema } from '../../../shared/agents/external-mcp.ts'
import { listAdminExternalMcp,createAdminExternalMcp,updateAdminExternalMcp,deleteAdminExternalMcp,setExternalMcpGrants,listExternalMcpGroupPolicies,setExternalMcpGroupPolicy,discoverExternalMcp,type ExternalMcpServerView,type ExternalMcpGroupPolicyView,type ExternalMcpDiscovery } from '../../helpers/agent-control-api.ts'
const {csrfToken,groups}=defineProps<{csrfToken:string;groups:readonly {id:number;name:string}[]}>()
const fetcher:typeof fetch=(...args)=>window.fetch(...args)
const servers=ref<ExternalMcpServerView[]>([]),policies=ref<ExternalMcpGroupPolicyView[]>([]),loading=ref(false),loaded=ref(false),busy=ref(false),denied=ref(false),error=ref(''),formError=ref(''),dialog=ref(false),discard=ref(false),baseline=ref(''),editing=ref<ExternalMcpServerView|null>(null),remove=ref<ExternalMcpServerView|null>(null),grants=ref<ExternalMcpServerView|null>(null),grantIds=ref<number[]>([]),policyConfirm=ref<ExternalMcpGroupPolicyView|null>(null),discovery=ref<ExternalMcpDiscovery|null>(null)
const draft=reactive({displayName:'',endpointUrl:'',status:'disabled' as 'enabled'|'disabled',authMode:'none' as 'none'|'bearer',secret:'',clearSecret:false,groupIds:[] as number[]})
const grantDiscard=ref(false)
async function load(){loading.value=true;try{const [s,p]=await Promise.all([listAdminExternalMcp(fetcher,csrfToken),listExternalMcpGroupPolicies(fetcher,csrfToken)]);servers.value=s;policies.value=p;loaded.value=true;denied.value=false;error.value=''}catch(e){denied.value=e instanceof AgentApiError&&e.status===403;error.value=denied.value?'System administration permission is required.':e instanceof Error?e.message:'Unable to load MCP administration.'}finally{loading.value=false}}
function open(s?:ExternalMcpServerView){editing.value=s??null;Object.assign(draft,{displayName:s?.displayName??'',endpointUrl:s?.endpointUrl??'',status:s?.status??'disabled',authMode:s?.authMode??'none',secret:'',clearSecret:false,groupIds:[...(s?.groupIds??[])]});baseline.value=JSON.stringify(draft);formError.value='';dialog.value=true}
function close(value:boolean){if(value||busy.value)return;if(JSON.stringify(draft)!==baseline.value)discard.value=true;else{dialog.value=false;draft.secret=''}}
async function act(operation:()=>Promise<unknown>){if(busy.value)return;busy.value=true;error.value='';try{await operation();await load()}catch(e){error.value=e instanceof Error?e.message:'Operation failed.';if(e instanceof AgentApiError&&e.status===409){await load();grants.value=null;policyConfirm.value=null;remove.value=null;error.value='Stale revision. Configuration refreshed; reopen the action and review current values.'}}finally{busy.value=false}}
async function save(){if(busy.value)return;busy.value=true;formError.value='';try{const input=ExternalMcpServerInputSchema.parse({displayName:draft.displayName,endpointUrl:draft.endpointUrl,status:draft.status,authMode:draft.authMode,...(draft.authMode==='bearer'?(draft.clearSecret?{secretValue:null}:draft.secret?{secretValue:draft.secret}:{}):{})});if(editing.value)await updateAdminExternalMcp(fetcher,csrfToken,editing.value.id,{...input,expectedRevision:editing.value.revision});else await createAdminExternalMcp(fetcher,csrfToken,{...input,groupIds:draft.groupIds});dialog.value=false;draft.secret='';await load()}catch(e){formError.value=e instanceof Error?e.message:'Unable to save endpoint.';if(e instanceof AgentApiError&&e.status===409){await load();formError.value='Stale revision. Close and reopen the refreshed endpoint before retrying.'}}finally{busy.value=false}}
function openGrants(s:ExternalMcpServerView){grants.value=s;grantIds.value=[...s.groupIds]}
function closeGrants(value:boolean){if(value||busy.value)return;if(JSON.stringify([...grantIds.value].sort((a,b)=>a-b))!==JSON.stringify([...(grants.value?.groupIds??[])].sort((a,b)=>a-b)))grantDiscard.value=true;else grants.value=null}
async function saveGrants(){const s=grants.value;if(!s)return;await act(async()=>{await setExternalMcpGrants(fetcher,csrfToken,s.id,s.revision,grantIds.value);grants.value=null})}
async function savePolicy(){const p=policyConfirm.value;if(!p)return;await act(async()=>{await setExternalMcpGroupPolicy(fetcher,csrfToken,p.groupId,p.revision,!p.allowPersonalEndpoints);policyConfirm.value=null})}
async function removeServer(){const s=remove.value;if(!s)return;await act(async()=>{await deleteAdminExternalMcp(fetcher,csrfToken,s.id,s.revision);remove.value=null})}
async function discover(s:ExternalMcpServerView){await act(async()=>{discovery.value=await discoverExternalMcp(fetcher,csrfToken,s.id)})}
onMounted(load)
</script>
<style scoped>
.control-panel{padding:24px;background:rgb(var(--v-theme-surface));border-radius:16px}header,.policy{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:20px}h2,h3{color:rgb(var(--v-theme-primary))}p{line-height:1.6;overflow-wrap:anywhere}.entry{padding:20px 0;border-bottom:1px solid rgba(var(--v-theme-on-surface),.12)}.actions{display:flex;flex-wrap:wrap;gap:8px}.v-alert{margin-bottom:16px}
</style>
