<template>
  <v-container fluid class="account-workspace">
    <admin-hero :title="saved?.name || $t('admin:usersEdit.accountWorkspace')" :description="saved?.email || $t('admin:usersEdit.identityMembershipAccountLifecycle')" :eyebrow="$t('admin:usersEdit.peopleAccess')" icon="mdi-account-outline"><template #actions><v-btn :to="directoryPath" variant="text" prepend-icon="mdi-arrow-left">{{ $t('admin:usersEdit.allAccounts') }}</v-btn><v-btn variant="text" prepend-icon="mdi-refresh" :loading="loading" :disabled="busy || dialog" @click="reload">{{ $t('admin:usersEdit.reloadAccount') }}</v-btn></template></admin-hero>
    <v-alert v-if="notice" type="success" variant="tonal" closable class="mt-5" @click:close="notice = ''">{{ notice }}</v-alert>
    <async-state v-if="!saved && loading" state="loading" :title="$t('admin:usersEdit.openingAccountWorkspace')" />
    <async-state v-else-if="!saved && loadError" state="error" :title="$t('admin:usersEdit.accountUnavailable')" :message="loadError" :retry-label="$t('admin:usersEdit.tryAgain')" @retry="reload" />
    <template v-if="saved">
      <v-alert v-if="loadError" type="error" variant="tonal" class="mb-4">{{ loadError }}<v-btn variant="text" :disabled="busy" @click="reload">{{ $t('admin:usersEdit.reloadAccount') }}</v-btn></v-alert>
      <header class="account-identity"><div class="account-portrait" aria-hidden="true">{{ initials(saved.name) }}</div><div class="account-identity-name"><span class="account-eyebrow">{{ $t('admin:usersEdit.account2', { id: saved.id, value: self ? ` ${$t('admin:usersEdit.account')}` : '', interpolation: { escapeValue: false } }) }}</span><p>{{ saved.providerTitle }}</p></div><div class="account-identity-status"><span><i :class="{ paused: !saved.isActive }" />{{ saved.isActive ? $t('admin:usersEdit.activeAccount') : $t('admin:usersEdit.inactiveAccount') }}</span><small>{{ saved.isVerified ? $t('admin:usersEdit.emailVerified') : $t('admin:usersEdit.emailUnverified') }}</small></div></header>
      <div class="account-tabs-row"><nav role="tablist" :aria-label="$t('admin:usersEdit.accountWorkspaceSections')" class="account-tabs"><button v-for="tab in tabs" :id="`account-tab-${tab.key}`" :key="tab.key" role="tab" :aria-selected="section === tab.key" :aria-controls="`account-panel-${tab.key}`" :tabindex="section === tab.key ? 0 : -1" @click="setSection(tab.key)" @keydown="tabKey($event, tab.key)">{{ tab.title }}</button></nav><span aria-live="polite">{{ loading ? $t('admin:usersEdit.openingAccountWorkspace') : loadError ? $t('admin:usersEdit.reloadRequired', { defaultValue: 'Reload required before further changes' }) : dirty ? $t('admin:usersEdit.unsavedProfileChanges') : $t('admin:usersEdit.showingSavedAccount') }}</span></div>
      <v-alert v-if="saved.capabilities.explanation" type="info" variant="tonal" class="mb-5">{{ saved.capabilities.explanation }}</v-alert>
      <section v-show="section === 'profile'" id="account-panel-profile" role="tabpanel" aria-labelledby="account-tab-profile">
        <div class="account-profile-layout"><div class="account-main-column"><section class="account-surface"><header><span class="account-eyebrow">{{ $t('admin:usersEdit.personalDetails') }}</span><h3>{{ $t('admin:usersEdit.personBehindAccount') }}</h3><p>{{ $t('admin:usersEdit.keepTheirNameContact') }}</p></header><div class="account-profile-form"><v-text-field v-model="draft.name" :label="$t('admin:usersEdit.displayName')" variant="outlined" maxlength="255" :disabled="profileLocked" /><v-text-field v-model="draft.email" :label="$t('admin:usersEdit.emailAddress')" type="email" variant="outlined" maxlength="255" :disabled="profileLocked" /><v-text-field v-model="draft.jobTitle" :label="$t('admin:usersEdit.roleJobTitle')" variant="outlined" maxlength="255" :disabled="profileLocked" /><v-text-field v-model="draft.location" :label="$t('admin:usersEdit.location')" variant="outlined" maxlength="255" :disabled="profileLocked" /><v-text-field v-model="draft.timezone" :label="$t('admin:usersEdit.timeZone')" variant="outlined" :hint="$t('admin:usersEdit.exampleEuropeLondonUtc')" persistent-hint :disabled="profileLocked" /></div><div v-if="emailChanged" class="account-impact-note"><v-icon icon="mdi-email-sync-outline" /><p>{{ $t('admin:usersEdit.changingEmailAddressClears') }}</p></div></section>
          <section class="account-surface"><header><span class="account-eyebrow">{{ $t('admin:usersEdit.membership') }}</span><h3>{{ $t('admin:usersEdit.accessThroughBelonging') }}</h3><p>{{ $t('admin:usersEdit.permissionsTheseGroupsCombined') }}</p></header><div class="account-membership-grid"><label v-for="group in saved.availableGroups" :key="group.id" :class="{ selected: draft.groups.includes(group.id), locked: profileLocked || self || !group.canAssign }"><input v-model="draft.groups" type="checkbox" :value="group.id" :disabled="profileLocked || self || !group.canAssign || (saved.id === 1 && group.id === 1)" /><span><strong>{{ group.name }}</strong><small>{{ $t('admin:usersEdit.permissionsCount', { count: group.permissions.length }) }}{{ !group.canAssign ? ` ${$t('admin:usersEdit.restricted')}` : '' }}</small></span><v-icon v-if="!group.canAssign" icon="mdi-lock-outline" size="16" /></label></div><p v-if="self" class="account-footnote">{{ $t('admin:usersEdit.anotherAdministratorMustChange') }}</p><p v-if="!draft.groups.length" class="account-footnote">{{ $t('admin:usersEdit.accountHasNoGroup') }}</p><details class="account-permissions"><summary>{{ $t('admin:usersEdit.combinedPermissions', { value: dirty ? $t('admin:usersEdit.draft') : $t('admin:usersEdit.saved'), draftPermissionsCount: draftPermissions.length, interpolation: { escapeValue: false } }) }}</summary><ul><li v-for="permission in draftPermissions" :key="permission">{{ permission }}</li></ul><p v-if="!draftPermissions.length">{{ $t('admin:usersEdit.noPermissionsGrantedThese') }}</p></details><div v-if="groupsChanged" class="account-impact-note"><v-icon icon="mdi-shield-account-outline" /><p>{{ $t('admin:usersEdit.savingMembershipChangesEnds') }}</p></div></section>
        </div><aside class="account-context-column"><section class="account-context-card"><span class="account-eyebrow">{{ $t('admin:usersEdit.accountContext') }}</span><dl><div><dt>{{ $t('admin:usersEdit.signProvider') }}</dt><dd>{{ saved.providerTitle }}</dd></div><div><dt>{{ $t('admin:usersEdit.created') }}</dt><dd>{{ date(saved.createdAt) }}</dd></div><div><dt>{{ $t('admin:usersEdit.profileLastChanged') }}</dt><dd>{{ date(saved.updatedAt) }}</dd></div><div><dt>{{ $t('admin:usersEdit.lastSignRenewal') }}</dt><dd>{{ saved.lastLoginAt ? date(saved.lastLoginAt) : $t('admin:usersEdit.notRecorded') }}</dd></div></dl><p>{{ $t('admin:usersEdit.renewalsUpdateTimestampNot') }}</p></section><section class="account-context-card"><span class="account-eyebrow">{{ $t('admin:usersEdit.contributions') }}</span><dl class="account-contributions"><div><dt>{{ $t('admin:usersEdit.pagesCreated') }}</dt><dd>{{ saved.contributionCounts.pagesCreated }}</dd></div><div><dt>{{ $t('admin:usersEdit.pagesLastAuthored') }}</dt><dd>{{ saved.contributionCounts.pagesAuthored }}</dd></div><div><dt>{{ $t('admin:usersEdit.localComments') }}</dt><dd>{{ saved.contributionCounts.comments }}</dd></div><div><dt>{{ $t('admin:usersEdit.assetsAttributed') }}</dt><dd>{{ saved.contributionCounts.assets }}</dd></div></dl><p>{{ $t('admin:usersEdit.theseCurrentAttributionCounts') }}</p><div v-if="saved.privateOwnershipBlocksDeletion" class="account-private-note"><v-icon icon="mdi-lock-outline" size="17" />{{ $t('admin:usersEdit.privatePageOwnershipHistory') }}</div></section></aside></div>
        <div v-if="saved.capabilities.edit" class="account-draft-bar"><div><strong>{{ dirty ? $t('admin:usersEdit.fieldsChangedCount', { count: changes.length }) : $t('admin:usersEdit.profileMatchesSavedAccount') }}</strong><span>{{ $t('admin:usersEdit.reviewChangesBeforeThey') }}</span></div><div><v-btn variant="text" :disabled="!dirty || busy || loading || dialog" @click="reset">{{ $t('admin:usersEdit.resetDraft') }}</v-btn><v-btn color="primary" variant="flat" :disabled="!dirty || busy || loading || Boolean(loadError) || profileIssues.length > 0" @click="open('profile')">{{ $t('admin:usersEdit.reviewChanges') }}</v-btn></div></div>
        <v-alert v-if="dirty && profileIssues.length" type="warning" variant="tonal" class="mt-4"><ul><li v-for="issue in profileIssues" :key="issue">{{ issue }}</li></ul></v-alert>
      </section>
      <section v-show="section === 'security'" id="account-panel-security" role="tabpanel" aria-labelledby="account-tab-security">
        <div class="account-section-heading"><div><span class="account-eyebrow">{{ $t('admin:usersEdit.signSecurity') }}</span><h3>{{ $t('admin:usersEdit.signControls') }}</h3><p>{{ $t('admin:usersEdit.reviewEachActionEffects') }}</p></div><v-btn to="/auth" variant="text" append-icon="mdi-arrow-top-right">{{ $t('admin:usersEdit.authenticationSettings') }}</v-btn></div>
        <v-alert v-if="dirty" type="info" variant="tonal" class="mb-5">{{ $t('admin:usersEdit.securityActionsPausedWhile') }}<v-btn variant="text" @click="setSection('profile')">{{ $t('admin:usersEdit.returnProfile') }}</v-btn></v-alert>
        <div class="account-security-grid"><section class="account-security-card"><v-icon icon="mdi-login" size="26" /><span class="account-eyebrow">{{ $t('admin:usersEdit.accountAvailability') }}</span><h4>{{ saved.isActive ? $t('admin:usersEdit.openSign') : $t('admin:usersEdit.signSuspended') }}</h4><p>{{ saved.isActive ? $t('admin:usersEdit.accountActiveProviderVerification') : $t('admin:usersEdit.personCannotSignTheir') }}</p><v-btn v-if="can('deactivate')" variant="outlined" :disabled="actionLocked" @click="open('deactivate')">{{ $t('admin:usersEdit.actionTitles.deactivate') }}</v-btn><v-btn v-if="can('activate')" variant="outlined" :disabled="actionLocked" @click="open('activate')">{{ $t('admin:usersEdit.actionTitles.activate') }}</v-btn><small v-if="!can('deactivate') && !can('activate')">{{ $t('admin:usersEdit.availabilityProtectedAccount') }}</small></section>
          <section class="account-security-card"><v-icon icon="mdi-email-check-outline" size="26" /><span class="account-eyebrow">{{ $t('admin:usersEdit.emailOwnership') }}</span><h4>{{ saved.isVerified ? $t('admin:usersEdit.addressVerified') : $t('admin:usersEdit.addressNeedsVerification') }}</h4><p>{{ saved.isVerified ? $t('admin:usersEdit.accountMarkedHavingVerified') : $t('admin:usersEdit.confirmPersonControlsAddress') }}</p><v-btn v-if="can('verify')" variant="outlined" :disabled="actionLocked" @click="open('verify')">{{ $t('admin:usersEdit.actionTitles.verify') }}</v-btn><small v-else>{{ $t('admin:usersEdit.changingAddressClearsStatus') }}</small></section>
          <section class="account-security-card"><v-icon icon="mdi-two-factor-authentication" size="26" /><span class="account-eyebrow">{{ $t('admin:usersEdit.authenticator') }}</span><h4>{{ twoFactorTitle }}</h4><p>{{ twoFactorDescription }}</p><div class="account-security-actions"><v-btn v-if="can('require-2fa')" variant="outlined" :disabled="actionLocked" @click="open('require-2fa')">{{ $t('admin:usersEdit.requireEnrollment') }}</v-btn><v-btn v-if="can('reset-2fa')" variant="outlined" :disabled="actionLocked" @click="open('reset-2fa')">{{ $t('admin:usersEdit.actionTitles.reset-2fa') }}</v-btn><v-btn v-if="can('disable-2fa')" variant="text" :disabled="actionLocked" @click="open('disable-2fa')">{{ $t('admin:usersEdit.removeAccountRequirement') }}</v-btn></div></section>
          <section class="account-security-card"><v-icon icon="mdi-key-outline" size="26" /><span class="account-eyebrow">{{ $t('admin:usersEdit.password') }}</span><h4>{{ saved.provider?.localPassword ? saved.mustChangePassword ? $t('admin:usersEdit.changeRequiredSign') : $t('admin:usersEdit.managedWorkspace') : $t('admin:usersEdit.managedIdentityProvider') }}</h4><p>{{ saved.provider?.localPassword ? $t('admin:usersEdit.replacementPasswordEndsExisting') : $t('admin:usersEdit.manageCredentialsWorkspaceDoes', { providerTitle: saved.providerTitle, interpolation: { escapeValue: false } }) }}</p><v-btn v-if="saved.capabilities.password" variant="outlined" :disabled="actionLocked" @click="open('password')">{{ $t('admin:usersEdit.replacePassword') }}</v-btn><v-btn v-else-if="self && saved.provider?.localPassword" href="/p" variant="outlined">{{ $t('admin:usersEdit.openMyProfile') }}</v-btn></section>
          <section class="account-security-card"><v-icon icon="mdi-devices" size="26" /><span class="account-eyebrow">{{ $t('admin:usersEdit.signSessions') }}</span><h4>{{ $t('admin:usersEdit.requireFreshSign') }}</h4><p>{{ $t('admin:usersEdit.invalidateExistingSignTokens2') }}</p><small>{{ $t('admin:usersEdit.lastEndedIndividualDevices', { sessionsRevokedAt: saved.sessionsRevokedAt ? date(saved.sessionsRevokedAt) : $t('admin:usersEdit.notRecorded'), interpolation: { escapeValue: false } }) }}</small><v-btn v-if="can('end-sessions')" variant="outlined" :disabled="actionLocked" @click="open('end-sessions')">{{ $t('admin:usersEdit.actionTitles.end-sessions') }}</v-btn><p class="account-footnote">{{ $t('admin:usersEdit.workspaceApiKeysHave') }} <router-link to="/api">{{ $t('admin:usersEdit.apiAccess') }}</router-link>.</p></section>
          <section class="account-security-card"><v-icon icon="mdi-email-fast-outline" size="26" /><span class="account-eyebrow">{{ $t('admin:usersEdit.welcomeEmail') }}</span><h4>{{ $t('admin:usersEdit.usefulFirstStep') }}</h4><p>{{ $t('admin:usersEdit.sendWorkspacesWelcomeMessage') }}</p><small>{{ $t('admin:usersEdit.sendingUsesSavedAddress') }}</small><v-btn v-if="saved.capabilities.edit && saved.isActive" variant="outlined" :disabled="actionLocked" @click="open('welcome')">{{ $t('admin:usersEdit.reviewWelcomeEmail') }}</v-btn></section>
        </div>
        <section class="account-deletion"><div><span class="account-eyebrow">{{ $t('admin:usersEdit.accountRetirement') }}</span><h4>{{ $t('admin:usersEdit.deleteAccount2') }}</h4><p>{{ $t('admin:usersEdit.removeAccountSignRecovery') }}</p><p v-if="!saved.capabilities.delete" class="account-footnote">{{ saved.capabilities.explanation || $t('admin:usersEdit.deletionUnavailableAccount') }}</p></div><v-btn v-if="saved.capabilities.delete" color="error" variant="outlined" :disabled="actionLocked" @click="open('delete')">{{ $t('admin:usersEdit.reviewDeletion') }}</v-btn></section>
      </section>
      <section v-show="section === 'activity'" id="account-panel-activity" role="tabpanel" aria-labelledby="account-tab-activity"><div class="account-section-heading"><div><span class="account-eyebrow">{{ $t('admin:usersEdit.administrativeHistory') }}</span><h3>{{ $t('admin:usersEdit.recordConsideredChanges') }}</h3><p>{{ $t('admin:usersEdit.latest50RecordedAccount') }}</p></div></div><async-state v-if="!saved.history.length" state="empty" :title="$t('admin:usersEdit.noAdministrativeActionsRecorded')" :message="$t('admin:usersEdit.newChangesMadeThrough')" /><ol v-else class="account-activity"><li v-for="event in saved.history" :key="event.id"><span class="account-event-dot" aria-hidden="true" /><div><div class="account-event-heading"><h4>{{ eventTitle(event.action) }}</h4><time :datetime="event.createdAt">{{ date(event.createdAt) }}</time></div><small>{{ event.actorId ? $t('admin:usersEdit.administratorAccount', { actorId: event.actorId, interpolation: { escapeValue: false } }) : $t('admin:usersEdit.workspaceCredential') }}</small><p>{{ event.reason }}</p><ul v-if="eventFields(event.details).length"><li v-for="field in eventFields(event.details)" :key="field">{{ field }}</li></ul></div></li></ol></section>
    </template>
    <v-dialog v-model="dialog" max-width="760" :fullscreen="$vuetify.display.smAndDown" :persistent="busy" :aria-label="dialogTitle"><v-card class="account-review-dialog"><v-card-title><span class="account-eyebrow">{{ $t('admin:usersEdit.accountReview', { id: saved?.id, interpolation: { escapeValue: false } }) }}</span><h2>{{ dialogTitle }}</h2></v-card-title><v-card-text v-if="saved"><div class="account-review-person"><strong>{{ saved.name }}</strong><span>{{ saved.email }}</span></div><p class="account-review-description">{{ dialogDescription }}</p>
      <dl v-if="operation === 'profile'" class="account-review-changes"><div v-for="change in changes" :key="change.key"><dt>{{ change.title }}</dt><dd><span>{{ change.before || $t('admin:usersEdit.empty') }}</span><v-icon icon="mdi-arrow-right" size="16" /><strong>{{ change.after || $t('admin:usersEdit.empty') }}</strong></dd></div></dl>
      <template v-if="operation === 'password'"><v-text-field v-model="password" :label="$t('admin:usersEdit.newTemporaryPassword')" :type="showPassword ? 'text' : 'password'" autocomplete="new-password" variant="outlined" :hint="passwordHint" persistent-hint :disabled="busy"><template #append-inner><password-visibility-toggle v-model:visible="showPassword" :field="$t('admin:usersEdit.newTemporaryPassword2')" /></template></v-text-field><v-checkbox v-model="mustChangePassword" :label="$t('admin:usersEdit.requireDifferentPasswordNext')" hide-details :disabled="busy" /></template>
      <template v-if="operation === 'delete'"><v-alert type="warning" variant="tonal" class="mb-4">{{ $t('admin:usersEdit.deletionPermanentDeactivationPreserves') }}</v-alert><dl class="account-delete-counts"><div><dt>{{ $t('admin:usersEdit.pagesCreated') }}</dt><dd>{{ saved.contributionCounts.pagesCreated }}</dd></div><div><dt>{{ $t('admin:usersEdit.pagesLastAuthored') }}</dt><dd>{{ saved.contributionCounts.pagesAuthored }}</dd></div><div><dt>{{ $t('admin:usersEdit.localComments') }}</dt><dd>{{ saved.contributionCounts.comments }}</dd></div><div><dt>{{ $t('admin:usersEdit.assets') }}</dt><dd>{{ saved.contributionCounts.assets }}</dd></div></dl><v-autocomplete v-model="replaceId" v-model:search="replacementSearch" :items="replacementOptions" :label="$t('admin:usersEdit.reassignContributionAttribution')" item-title="title" item-value="id" variant="outlined" :loading="replacementLoading" :disabled="busy" no-filter clearable hide-no-data :hint="$t('admin:usersEdit.searchAnotherActiveAccount')" persistent-hint @update:search="searchReplacements" /><v-alert v-if="replacementError" type="error" variant="tonal" class="my-3">{{ replacementError }}<v-btn variant="text" @click="searchReplacements">{{ $t('admin:usersEdit.tryAgain') }}</v-btn></v-alert><v-text-field v-model="deleteConfirmation" :label="$t('admin:usersEdit.typeConfirmAccountDeletion', { id: saved.id, interpolation: { escapeValue: false } })" variant="outlined" class="mt-4" autocomplete="off" :disabled="busy" /></template>
      <v-alert v-if="endsOwnSessions" type="warning" variant="tonal" class="my-4">{{ $t('admin:usersEdit.alsoEndsCurrentSign') }}</v-alert>
      <v-textarea v-model="reason" :label="$t('admin:usersEdit.administrativeReason')" variant="outlined" rows="2" auto-grow maxlength="1000" class="mt-5" :disabled="busy" :hint="$t('admin:usersEdit.n31000Characters')" persistent-hint />
      <v-alert v-if="actionError" type="error" variant="tonal" class="mt-4">{{ actionError }}<v-btn v-if="conflict" variant="text" :disabled="busy" @click="reloadReview">{{ $t('admin:usersEdit.reloadAccount') }}</v-btn></v-alert>
    </v-card-text><v-card-actions><v-btn variant="text" :disabled="busy" @click="dialog = false; password = ''">{{ operation === 'profile' ? $t('admin:usersEdit.keepEditing') : $t('common:actions.cancel') }}</v-btn><v-spacer /><v-btn :color="operation === 'delete' ? 'error' : 'primary'" variant="flat" :disabled="!canConfirm || conflict" :loading="busy" @click="confirm">{{ operation === 'profile' ? $t('admin:usersEdit.saveProfileChanges') : operation === 'welcome' ? $t('admin:usersEdit.sendWelcomeEmail2') : dialogTitle }}</v-btn></v-card-actions></v-card></v-dialog>
  </v-container>
</template>
<script lang="ts">
import { confirmDiscard } from '../common/confirm-dialog.ts'
import { passwordPolicyMixin } from '../../helpers/password-policy.ts'
import { newPasswordIssue } from '../../../shared/security-policy.ts'
import AsyncState from '@/components/common/async-state.vue'
import PasswordVisibilityToggle from '@/components/common/password-visibility-toggle.vue'
import { accountActionTitle, accountProfileIssues, type AccountAction, type AccountProfileDraft, type AccountWorkspace } from '../../../shared/account-policy.ts'
import { fetchAccount, fetchAccountDirectory, saveAccountProfile, actOnAccount, replaceAccountPassword, deleteAccount, sendAccountWelcomeEmail, accountRequestStatus } from '../../helpers/account-api.ts'
import { getErrorMessage } from '../../helpers/root-ui-store.ts'
import { wikiStore } from '@/store/index.ts'
type Operation = AccountAction | 'profile' | 'password' | 'delete' | 'welcome'
const copy = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T
const fieldTitles: Record<keyof AccountProfileDraft, string> = { name: 'admin:usersEdit.displayName', email: 'admin:usersEdit.emailAddress', jobTitle: 'admin:usersEdit.roleJobTitle', location: 'admin:usersEdit.location', timezone: 'admin:usersEdit.timeZone', groups: 'admin:usersEdit.groupMembership' }
const descriptions: Record<AccountAction, string> = {
  activate: 'admin:usersEdit.allowPersonSignAgain', deactivate: 'admin:usersEdit.suspendSignEndExisting', verify: 'admin:usersEdit.markSavedEmailAddress', 'require-2fa': 'admin:usersEdit.requireAuthenticatorEnrollmentDuring', 'reset-2fa': 'admin:usersEdit.clearCurrentAuthenticatorRequire', 'disable-2fa': 'admin:usersEdit.removeAccountsAuthenticatorAccount', 'end-sessions': 'admin:usersEdit.invalidateExistingSignTokens' }
export default {
  mixins: [passwordPolicyMixin],
  components: { AsyncState, PasswordVisibilityToggle },
  data() { return { saved: null as AccountWorkspace | null, draft: { name: '', email: '', location: '', jobTitle: '', timezone: 'UTC', groups: [] } as AccountProfileDraft, loading: false, loadError: '', sequence: 0, disposed: false, notice: '', section: 'profile', tabs: [{ key: 'profile', title: this.$t('admin:usersEdit.profileMembership') }, { key: 'security', title: this.$t('admin:usersEdit.signSecurity') }, { key: 'activity', title: this.$t('admin:usersEdit.activity') }], dialog: false, operation: 'profile' as Operation, reason: '', password: '', showPassword: false, mustChangePassword: true, busy: false, actionError: '', conflict: false, replacementSearch: '', replaceId: null as number | null, replacementOptions: [] as Array<{ id: number; title: string }>, replacementLoading: false, replacementError: '', replacementSequence: 0, replacementTimer: null as ReturnType<typeof setTimeout> | null, deleteConfirmation: '' } },
  computed: {
    directoryPath(): string { const from = this.$route.query.from; return typeof from === 'string' && (from === '/users' || from.startsWith('/users?')) ? from : '/users' },
    self(): boolean { return this.saved?.id === wikiStore.user.id },
    dirty(): boolean { return Boolean(this.saved && JSON.stringify({ ...this.draft, groups: [...this.draft.groups].sort((a,b) => a-b) }) !== JSON.stringify(this.saved.profile)) },
    emailChanged(): boolean { return Boolean(this.saved && this.draft.email.trim().toLowerCase() !== this.saved.email) },
    groupsChanged(): boolean { return Boolean(this.saved && JSON.stringify([...this.draft.groups].sort((a,b) => a-b)) !== JSON.stringify(this.saved.profile.groups)) },
    profileLocked(): boolean { return this.busy || this.loading || Boolean(this.loadError) || this.dialog || !this.saved?.capabilities.edit },
    actionLocked(): boolean { return this.dirty || this.busy || this.loading || Boolean(this.loadError) || this.dialog },
    profileIssues() { return accountProfileIssues(this.draft) },
    draftPermissions() { return [...new Set((this.saved?.availableGroups ?? []).filter(group => this.draft.groups.includes(group.id)).flatMap(group => group.permissions))].sort() },
    changes(): Array<{ key: string; title: string; before: string; after: string }> { if (!this.saved) return []; return (Object.keys(fieldTitles) as Array<keyof AccountProfileDraft>).flatMap(key => { const before = this.saved!.profile[key], after = this.draft[key]; if (key === 'groups' ? !this.groupsChanged : before === after) return []; const value = (input: string | number[]) => Array.isArray(input) ? input.map(id => this.saved?.availableGroups.find(group => group.id === id)?.name ?? '#' + id).join(', ') : input; return [{ key, title: this.$t(fieldTitles[key]), before: value(before), after: value(after) }] }) },
    twoFactorTitle(): string { return ({ enrolled: this.$t('admin:usersEdit.authenticatorEnrolled'), 'enrollment-required': this.$t('admin:usersEdit.enrollmentRequired'), off: this.$t('admin:usersEdit.noAccountRequirement'), 'provider-managed': this.$t('admin:usersEdit.managedProvider') })[this.saved?.twoFactor ?? 'off'] },
    twoFactorDescription(): string { return ({ enrolled: this.$t('admin:usersEdit.authenticatorEnrolledAccountsSupported'), 'enrollment-required': this.$t('admin:usersEdit.personMustCompleteAuthenticator'), off: this.$t('admin:usersEdit.accountDoesNotCurrently'), 'provider-managed': this.$t('admin:usersEdit.providerHandlesOwnSign') })[this.saved?.twoFactor ?? 'off'] },
    dialogTitle(): string { return this.operation === 'profile' ? this.$t('admin:usersEdit.reviewProfileChanges') : this.operation === 'password' ? this.$t('admin:usersEdit.replacePassword') : this.operation === 'delete' ? this.$t('admin:usersEdit.deleteAccount') : this.operation === 'welcome' ? this.$t('admin:usersEdit.sendWelcomeEmail') : this.$t(`admin:usersEdit.actionTitles.${this.operation}`) },
    dialogDescription(): string { return this.operation === 'profile' ? this.$t('admin:usersEdit.applyFollowingChangesSaved') : this.operation === 'password' ? this.$t('admin:usersEdit.setNewLocalPassword') : this.operation === 'delete' ? this.$t('admin:usersEdit.privatePagesHistoryOwned') : this.operation === 'welcome' ? this.$t('admin:usersEdit.sendConfiguredWorkspaceWelcome') : this.$t(descriptions[this.operation]) },
    endsOwnSessions(): boolean { return this.self && (this.operation === 'profile' ? this.emailChanged || this.groupsChanged : !['activate', 'verify', 'welcome', 'delete'].includes(this.operation)) },
    canConfirm(): boolean { if (this.busy || this.reason.trim().length < 3 || this.reason.trim().length > 1000) return false; if (this.operation === 'profile') return this.dirty && this.profileIssues.length === 0; if (this.operation === 'password') return !newPasswordIssue(this.password, this.passwordMinimum); if (this.operation === 'delete') return Boolean(this.replaceId && this.deleteConfirmation === String(this.saved?.id)); return true }
  },
  methods: {
    async reload() { if (this.busy || (this.dirty && !(await confirmDiscard(this.$t('admin:usersEdit.discardUnsavedProfileChanges')))) || this.busy) return; const sequence = ++this.sequence; this.loading = true; this.loadError = ''; try { const value = await fetchAccount(Number(this.$route.params.id)); if (!this.disposed && sequence === this.sequence) { this.saved = value; this.draft = copy(value.profile) } } catch (error) { if (!this.disposed && sequence === this.sequence) this.loadError = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.sequence) this.loading = false } },
    reset() { if (this.saved && !this.busy && !this.dialog) this.draft = copy(this.saved.profile) },
    can(action: AccountAction): boolean { return this.saved?.capabilities.actions.includes(action) ?? false },
    open(operation: Operation) { if (this.busy || this.loading || this.loadError || (operation !== 'profile' && this.dirty)) return; this.operation = operation; this.reason = ''; this.password = ''; this.showPassword = false; this.mustChangePassword = true; this.actionError = ''; this.conflict = false; this.deleteConfirmation = ''; this.replaceId = null; this.replacementSearch = ''; this.replacementOptions = []; this.dialog = true; if (operation === 'delete') this.searchReplacements() },
    async reloadReview() { this.dialog = false; this.password = ''; await this.reload() },
    async confirm() { if (!this.saved || !this.canConfirm) return; const id = this.saved.id, operation = this.operation, ownSessions = this.endsOwnSessions; this.busy = true; this.actionError = ''; try { let next: AccountWorkspace | null = null; if (operation === 'profile') next = await saveAccountProfile(id, copy(this.draft), this.reason.trim(), this.saved.fingerprint); else if (operation === 'password') next = await replaceAccountPassword(id, this.password, this.mustChangePassword, this.reason.trim(), this.saved.fingerprint); else if (operation === 'delete') { await deleteAccount(id, this.replaceId!, this.reason.trim(), this.saved.fingerprint); this.dialog = false; this.busy = false; this.draft = copy(this.saved.profile); await this.$router.push(this.directoryPath); return } else if (operation === 'welcome') { await sendAccountWelcomeEmail(id, this.reason.trim(), this.saved.fingerprint); this.notice = this.$t('admin:usersEdit.welcomeEmailAcceptedMail'); try { next = await fetchAccount(id) } catch { this.notice += ` ${this.$t('admin:usersEdit.reloadRefreshAccountHistory')}` } } else next = await actOnAccount(id, operation, this.reason.trim(), this.saved.fingerprint); if (this.disposed) return; if (next) { this.saved = next; this.draft = copy(next.profile); if (operation !== 'welcome') this.notice = operation === 'profile' ? this.$t('admin:usersEdit.profileChangesSaved') : this.$t('admin:usersEdit.completed', { dialogTitle: this.dialogTitle, interpolation: { escapeValue: false } }) } this.dialog = false; this.password = ''; if (ownSessions) window.location.assign('/login') } catch (error) { if (!this.disposed) { this.conflict = accountRequestStatus(error) === 409; this.actionError = getErrorMessage(error) + (accountRequestStatus(error) === 0 ? ` ${this.$t('admin:usersEdit.outcomeUnconfirmedReloadAccount')}` : '') } } finally { if (!this.disposed) this.busy = false } },
    searchReplacements() { if (this.replacementTimer) clearTimeout(this.replacementTimer); const sequence = ++this.replacementSequence, search = this.replacementSearch || ''; this.replacementTimer = setTimeout(async () => { this.replacementLoading = true; this.replacementError = ''; try { const value = await fetchAccountDirectory(new URLSearchParams({ search, state: 'active', limit: '25' })); if (!this.disposed && sequence === this.replacementSequence) this.replacementOptions = value.items.filter(row => row.id !== this.saved?.id && row.id !== 2 && row.groups.every(group => this.saved?.availableGroups.some(option => option.id === group.id && option.canAssign))).map(row => ({ id: row.id, title: `${row.name} · ${row.email}` })) } catch (error) { if (!this.disposed && sequence === this.replacementSequence) this.replacementError = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.replacementSequence) this.replacementLoading = false } }, 250) },
    setSection(key: string) { this.section = key; void this.$router.replace({ query: this.$route.query, hash: '#' + key }) },
    tabKey(event: KeyboardEvent, key: string) { if (!['ArrowLeft','ArrowRight','Home','End'].includes(event.key)) return; event.preventDefault(); const index = event.key === 'Home' ? 0 : event.key === 'End' ? this.tabs.length - 1 : (this.tabs.findIndex(tab => tab.key === key) + (event.key === 'ArrowRight' ? 1 : -1) + this.tabs.length) % this.tabs.length; const next = this.tabs[index]!.key; this.setSection(next); this.$nextTick(() => document.getElementById('account-tab-' + next)?.focus()) },
    initials(value: string) { return value.trim().split(/\s+/).slice(0,2).map(part => part[0]).join('').toUpperCase() },
    date(value: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? this.$t('admin:usersEdit.notRecorded') : date.toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }) },
    eventTitle(action: string): string { return (action in accountActionTitle ? this.$t(`admin:usersEdit.actionTitles.${action}`) : undefined) ?? ({ 'profile-updated': this.$t('admin:usersEdit.profileUpdated'), 'membership-updated': this.$t('admin:usersEdit.groupMembershipChanged'), 'group-policy-updated': this.$t('admin:usersEdit.groupAccessPolicyChanged'), 'sign-in-policy-updated': this.$t('admin:usersEdit.signProviderPolicyChanged'), 'directory-groups-synchronized': this.$t('admin:usersEdit.directoryGroupMembershipSynchronized'), 'group-deleted': this.$t('admin:usersEdit.groupMembershipEndedAfter'), 'account-created': this.$t('admin:usersEdit.accountCreated'), 'account-deleted': this.$t('admin:usersEdit.accountDeleted'), 'password-replaced': this.$t('admin:usersEdit.passwordReplaced'), 'welcome-email-requested': this.$t('admin:usersEdit.welcomeEmailRequestedOutcome'), 'welcome-email-accepted': this.$t('admin:usersEdit.welcomeEmailAcceptedMail2'), 'welcome-email-failed': this.$t('admin:usersEdit.welcomeEmailFailed') } as Record<string,string>)[action] ?? action },
    eventFields(details: Record<string,unknown>): string[] { const fields = Array.isArray(details.fields) ? details.fields.filter((value): value is string => typeof value === 'string').map(value => (value in fieldTitles ? this.$t(fieldTitles[value as keyof AccountProfileDraft]) : value)) : []; return [...fields, ...(typeof details.groupId === 'number' ? [this.$t('admin:usersEdit.group', { groupId: details.groupId, interpolation: { escapeValue: false } })] : []), ...(details.sessionsEnded === true ? [this.$t('admin:usersEdit.existingSignSessionsEnded')] : [])] },
    async canLeave(): Promise<boolean> { return !this.busy && ((!this.dirty && !(this.dialog && (this.password || this.reason))) || await confirmDiscard(this.$t('admin:usersEdit.discardUnsavedAccountChanges'))) },
    beforeUnload(event: BeforeUnloadEvent) { if (this.dirty || this.busy || (this.dialog && (this.password || this.reason))) { event.preventDefault(); event.returnValue = '' } }
  },
  watch: { '$route.hash': { immediate: true, handler(hash: string) { this.section = this.tabs.some(tab => tab.key === hash.slice(1)) ? hash.slice(1) : 'profile' } }, '$route.params.id'() { if (this.saved) this.draft = copy(this.saved.profile); this.saved = null; this.dialog = false; this.password = ''; this.notice = ''; void this.reload() }, dialog(value: boolean) { if (!value) { this.password = ''; this.replacementSequence++; if (this.replacementTimer) clearTimeout(this.replacementTimer) } } },
  mounted() { void this.reload(); window.addEventListener('beforeunload', this.beforeUnload) },
  beforeRouteLeave() { return this.canLeave() },
  beforeRouteUpdate(to, from) { return to.params.id === from.params.id || this.canLeave() },
  beforeUnmount() { this.disposed = true; this.sequence++; this.replacementSequence++; if (this.replacementTimer) clearTimeout(this.replacementTimer); this.password = ''; window.removeEventListener('beforeunload', this.beforeUnload) }
}
</script>
<style lang="scss">
.account-workspace,.account-review-dialog { --account-line: var(--wiki-surface-border); --account-muted: var(--wiki-text-muted); min-width: 0; .account-eyebrow { display: block; font-size: .75rem; font-weight: 600; color: var(--account-muted); } }
.account-workspace .admin-hero__description { overflow-wrap: anywhere; }
.account-identity { display: flex; flex-wrap: wrap; gap: 12px; align-items: center; padding: 12px 0; }
.account-portrait { display: grid; place-items: center; width: 40px; height: 40px; flex-shrink: 0; border: 1px solid var(--account-line); background: var(--wiki-surface-sunken); border-radius: var(--wiki-control-radius); font-size: .875rem; }
.account-identity-name { min-width: 0; p { margin: 4px 0 0; font-size: .8125rem; color: var(--account-muted); overflow-wrap: anywhere; } }
.account-identity-status { margin-inline-start: auto; display: flex; flex-wrap: wrap; align-items: center; gap: 12px; span { display: flex; align-items: center; gap: 7px; font-size: .8125rem; } i { width: 7px; height: 7px; background: var(--wiki-purpose-success-ink); border-radius: 50%; &.paused { background: var(--account-muted); } } small { font-size: .75rem; color: var(--account-muted); } }
.account-tabs-row { display: flex; flex-wrap: wrap; justify-content: space-between; gap: 8px; align-items: center; border-bottom: 1px solid var(--account-line); margin-bottom: 16px; >span { font-size: .75rem; color: var(--account-muted); padding-block: 8px; } }
.account-tabs { display: flex; flex-wrap: wrap; gap: 4px; min-width: 0; button { background: transparent; border: 0; border-bottom: 3px solid transparent; color: var(--account-muted); padding: 10px 12px; min-height: 44px; cursor: pointer; font-size: .8125rem; font-weight: 600; &[aria-selected=true] { border-bottom-color: var(--wiki-primary-ink); color: rgb(var(--v-theme-on-surface)); } &:focus-visible { outline: 2px solid var(--wiki-primary-ink); outline-offset: -2px; } } }
.account-profile-layout { display: grid; grid-template-columns: minmax(0,1fr) 260px; gap: 16px; align-items: start; }
.account-main-column,.account-context-column { display: grid; gap: 16px; min-width: 0; }
.account-surface,.account-context-card { padding: 16px; border: 1px solid var(--account-line); border-radius: var(--wiki-panel-radius); background: var(--wiki-surface-raised); min-width: 0; }
.account-surface header { margin-bottom: 16px; h3 { margin: 4px 0 8px; font-size: 1.0625rem; font-weight: 650; } p { margin: 0; font-size: .8125rem; line-height: 1.6; color: var(--account-muted); max-width: 70ch; } }
.account-profile-form { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 4px 12px; >* { min-width: 0; } }
.account-impact-note { display: flex; align-items: flex-start; gap: 12px; padding: 12px; background: var(--wiki-surface-sunken); border-inline-start: 2px solid var(--wiki-primary-ink); margin-top: 12px; p { margin: 0; font-size: .8125rem; line-height: 1.6; } }
.account-membership-grid { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 8px; label { border: 1px solid var(--account-line); border-radius: var(--wiki-control-radius); display: flex; gap: 12px; align-items: flex-start; padding: 12px; cursor: pointer; min-width: 0; &.selected { border-color: var(--wiki-primary-ink); background: var(--wiki-surface-sunken); } &.locked { cursor: default; } input { margin-top: 3px; width: 18px; height: 18px; flex-shrink: 0; accent-color: rgb(var(--v-theme-primary)); } span { min-width: 0; } strong { display: block; font-size: .8125rem; font-weight: 600; overflow-wrap: anywhere; } small { display: block; font-size: .75rem; margin-top: 4px; color: var(--account-muted); } } }
.account-permissions { margin-top: 12px; summary { font-size: .8125rem; cursor: pointer; min-height: 44px; padding-block: 12px; } >ul { display: flex; flex-wrap: wrap; gap: 8px 16px; padding: 8px 0 0; list-style: none; font-size: .75rem; overflow-wrap: anywhere; } p { font-size: .8125rem; margin-top: 8px; color: var(--account-muted); } }
.account-context-card { dl { margin-top: 12px; display: grid; gap: 12px; } dt { font-size: .75rem; color: var(--account-muted); margin-bottom: 4px; } dd { margin: 0; font-size: .8125rem; overflow-wrap: anywhere; } >p { margin: 12px 0 0; font-size: .75rem; line-height: 1.6; color: var(--account-muted); } .account-contributions >div { display: flex; justify-content: space-between; gap: 12px; align-items: center; dt { margin: 0; } dd { font-variant-numeric: tabular-nums; } } }
.account-private-note { display: flex; gap: 8px; padding-top: 12px; margin-top: 12px; border-top: 1px solid var(--account-line); font-size: .75rem; line-height: 1.6; }
.account-footnote { font-size: .75rem !important; line-height: 1.6; color: var(--account-muted); margin: 12px 0 0; a { color: var(--wiki-primary-ink); text-underline-offset: 3px; } }
.account-draft-bar { display: flex; flex-wrap: wrap; justify-content: space-between; align-items: center; gap: 12px; padding: 16px; margin-top: 16px; border: 1px solid var(--account-line); border-radius: var(--wiki-panel-radius); background: var(--wiki-surface-raised); >div:last-child { display: flex; flex-wrap: wrap; gap: 8px; } strong { font-size: .8125rem; display: block; font-weight: 600; } span { display: block; font-size: .75rem; color: var(--account-muted); margin-top: 4px; } }
.account-section-heading { display: flex; flex-wrap: wrap; gap: 12px; justify-content: space-between; align-items: center; padding-bottom: 16px; h3 { font-size: 1.125rem; margin: 4px 0 8px; font-weight: 650; } p { font-size: .8125rem; max-width: 70ch; line-height: 1.6; color: var(--account-muted); margin: 0; } }
.account-security-grid { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 12px; }
.account-security-card { display: flex; flex-direction: column; align-items: flex-start; padding: 16px; border: 1px solid var(--account-line); border-radius: var(--wiki-panel-radius); background: var(--wiki-surface-raised); min-width: 0; >.v-icon { margin-bottom: 8px; color: var(--account-muted); } h4 { font-size: 1rem; font-weight: 650; margin: 4px 0 8px; } >p { font-size: .8125rem; line-height: 1.6; color: var(--account-muted); margin: 0 0 12px; overflow-wrap: anywhere; } >small { font-size: .75rem; color: var(--account-muted); line-height: 1.6; margin-bottom: 12px; } >.v-btn,.account-security-actions { margin-top: auto; } .account-footnote { margin: 12px 0 0; } }
.account-security-actions { display: flex; gap: 8px; align-items: flex-start; flex-wrap: wrap; .v-btn { max-width: 100%; } }
.account-deletion { margin-top: 16px; border-top: 1px solid var(--account-line); padding: 16px 0; display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 16px; h4 { font-size: 1rem; font-weight: 650; margin: 4px 0 8px; } p { font-size: .8125rem; color: var(--account-muted); line-height: 1.6; margin: 0; max-width: 70ch; } }
.account-activity { list-style: none; padding: 0; margin: 0; >li { display: grid; grid-template-columns: 12px minmax(0,1fr); gap: 12px; padding: 16px 0; border-bottom: 1px solid var(--account-line); small { font-size: .75rem; color: var(--account-muted); display: block; margin-top: 6px; } p { font-size: .8125rem; white-space: pre-wrap; overflow-wrap: anywhere; line-height: 1.6; margin: 12px 0 0; } ul { list-style: none; padding: 0; display: flex; flex-wrap: wrap; gap: 8px; margin-top: 12px; li { font-size: .75rem; padding: 4px 8px; border-radius: 4px; background: var(--wiki-surface-sunken); overflow-wrap: anywhere; } } } }
.account-event-dot { height: 7px; width: 7px; margin-top: 8px; border-radius: 50%; background: var(--wiki-primary-ink); }
.account-event-heading { display: flex; flex-wrap: wrap; justify-content: space-between; gap: 8px; h4 { font-size: .9375rem; font-weight: 650; overflow-wrap: anywhere; } time { font-size: .75rem; color: var(--account-muted); } }
.account-review-dialog { max-height: 90dvh; background: var(--wiki-surface-raised); .v-card-title { white-space: normal; padding: 20px 20px 12px; h2 { font-size: 1.125rem; margin-top: 4px; font-weight: 650; overflow-wrap: anywhere; } } .v-card-text { padding: 8px 20px 20px; overflow-y: auto; } .v-card-actions { padding: 12px 16px; border-top: 1px solid var(--account-line); flex-wrap: wrap; } }
.account-review-person { display: flex; flex-direction: column; gap: 4px; margin: 0 0 12px; strong { font-size: 1rem; font-weight: 650; overflow-wrap: anywhere; } span { font-size: .8125rem; color: var(--account-muted); overflow-wrap: anywhere; } }
.account-review-description { font-size: .8125rem; color: var(--account-muted); line-height: 1.6; margin-bottom: 16px; }
.account-review-changes { display: grid; gap: 12px; border-block: 1px solid var(--account-line); padding: 16px 0; dt { font-size: .75rem; color: var(--account-muted); margin-bottom: 8px; } dd { display: flex; gap: 12px; align-items: center; font-size: .8125rem; overflow-wrap: anywhere; margin: 0; >span,>strong { flex: 1; min-width: 0; } >span { color: var(--account-muted); } strong { font-weight: 600; } } }
.account-delete-counts { display: grid; grid-template-columns: repeat(4,minmax(0,1fr)); gap: 12px; margin: 16px 0; dt { font-size: .75rem; color: var(--account-muted); line-height: 1.5; } dd { font-size: 1rem; margin: 4px 0 0; } }
@media(max-width:1100px) { .account-profile-layout { grid-template-columns: minmax(0,1fr); } .account-context-column { grid-template-columns: repeat(2,minmax(0,1fr)); } }
@media(max-width:700px) { .account-identity-status { margin-inline-start: 0; width: 100%; } .account-profile-form,.account-membership-grid,.account-context-column,.account-security-grid { grid-template-columns: minmax(0,1fr); } .account-tabs { width: 100%; } .account-workspace .v-btn,.account-review-dialog .v-btn { white-space: normal; height: auto; min-height: 44px; max-width: 100%; padding-block: 10px; .v-btn__content { white-space: normal; } } .account-review-changes dd { flex-direction: column; align-items: flex-start; gap: 8px; } .account-delete-counts { grid-template-columns: repeat(2,minmax(0,1fr)); } }
</style>
