<template>
  <v-dialog :model-value="modelValue" max-width="660" :fullscreen="$vuetify.display.smAndDown" :persistent="saving" aria-labelledby="group-create-title" @update:model-value="close">
    <v-card class="group-dialog group-create-dialog"><div class="group-dialog-header"><h2 id="group-create-title">{{ reviewing ? $t('admin:groupsCreate.reviewNewGroup') : $t('admin:groupsCreate.createGroup') }}</h2><p>{{ reviewing ? $t('admin:groupsCreate.confirmStartingAccessBefore') : $t('admin:groupsCreate.giveSharedResponsibilityClear') }}</p></div>
      <v-card-text><async-state v-if="loading" state="loading" :title="$t('admin:groupsCreate.loadingCreationPolicy')" /><async-state v-else-if="loadError" state="error" :title="$t('admin:groupsCreate.creationPolicyUnavailable')" :message="loadError" :retry-label="$t('admin:groupsCreate.tryAgain')" @retry="load" />
        <template v-else-if="options"><div v-if="!reviewing" class="group-dialog-fields"><v-text-field v-model="name" :label="$t('admin:groupsCreate.groupName')" variant="outlined" maxlength="255" :disabled="saving" /><v-textarea v-model="description" :label="$t('admin:groupsCreate.purpose')" variant="outlined" rows="2" auto-grow maxlength="1000" :hint="$t('admin:groupsCreate.whatShouldGroupResponsible')" persistent-hint :disabled="saving" /><div><h3 class="text-title-small mb-3">{{ $t('admin:groupsCreate.startingAccess') }}</h3><div class="group-preset-list" :aria-label="$t('admin:groupsCreate.startingAccess')"><button v-for="item in presets" :key="item.key" type="button" :aria-pressed="preset === item.key" :disabled="saving" @click="preset = item.key"><v-icon :icon="preset === item.key ? 'mdi-radiobox-marked' : 'mdi-radiobox-blank'" size="21" /><span><strong>{{ $t(item.title) }}</strong><small>{{ $t(item.description) }}</small></span></button></div><p class="text-body-small text-medium-emphasis">{{ $t('admin:groupsCreate.permissionsPageRulesCan') }}</p></div></div>
          <template v-else><dl class="group-review-list"><div><dt>{{ $t('admin:groupsCreate.group') }}</dt><dd>{{ policy.name }}</dd></div><div v-if="policy.description"><dt>{{ $t('admin:groupsCreate.purpose') }}</dt><dd>{{ policy.description }}</dd></div><div><dt>{{ $t('admin:groupsCreate.startingAccess') }}</dt><dd>{{ $t(selectedPreset.title) }} · {{ $t(selectedPreset.description) }}</dd></div><div><dt>{{ $t('admin:groupsCreate.permissions') }}</dt><dd>{{ policy.permissions.map(permissionTitle).join(', ') || $t('admin:groupsCreate.none') }}</dd></div><div><dt>{{ $t('admin:groupsCreate.membersCredentials') }}</dt><dd>{{ $t('admin:groupsCreate.noMembersAddedNo') }}</dd></div></dl><v-textarea v-model="reason" :label="$t('admin:groupsCreate.administrativeReason')" variant="outlined" rows="2" auto-grow maxlength="1000" :disabled="saving" /></template>
          <v-alert v-if="saveError" type="error" variant="tonal" class="mt-4">{{ saveError }}<v-btn v-if="conflict" variant="text" :disabled="saving" @click="load">{{ $t('admin:groupsCreate.reloadCreationPolicy') }}</v-btn></v-alert>
        </template>
      </v-card-text><v-card-actions><v-btn variant="text" :disabled="saving" @click="reviewing ? reviewing = false : close(false)">{{ reviewing ? $t('admin:groupsCreate.keepEditing') : $t('common:actions.cancel') }}</v-btn><v-spacer /><v-btn v-if="!reviewing" color="primary" variant="flat" :disabled="!valid || loading || !options" @click="reviewing = true">{{ $t('admin:groupsCreate.reviewGroup') }}</v-btn><v-btn v-else color="primary" variant="flat" :loading="saving" :disabled="!valid || reason.trim().length < 3 || conflict" @click="create">{{ $t('admin:groupsCreate.createGroup2') }}</v-btn></v-card-actions>
    </v-card>
  </v-dialog>
</template>
<script lang="ts">
import { confirmDiscard } from '../common/confirm-dialog.ts'
import AsyncState from '@/components/common/async-state.vue'
import { groupPermissions, type GroupPolicyDraft } from '../../../shared/group-policy.ts'
import { fetchGroupCreationOptions, createReviewedGroup, groupRequestStatus, type GroupCreationOptions } from '../../helpers/group-workspace-api.ts'
import { getErrorMessage } from '../../helpers/root-ui-store.ts'
const presets = [
  { key: 'empty', title: 'admin:groupsCreate.startNoAccess', description: 'admin:groupsCreate.buildSpecificPolicyBefore', permissions: [] as string[] },
  { key: 'readers', title: 'admin:groupsCreate.readDiscuss', description: 'admin:groupsCreate.readAllPublicPages', permissions: ['read:pages','read:assets','read:comments','write:comments'] },
  { key: 'authors', title: 'admin:groupsCreate.knowledgeContributors', description: 'admin:groupsCreate.createEditPublicPages', permissions: ['read:pages','write:pages','read:source','read:history','read:assets','write:assets','read:comments','write:comments'] }
]
export default {
  components: { AsyncState }, props: { modelValue: Boolean }, emits: ['update:modelValue','created'],
  data() { return { name: '', description: '', preset: 'empty', reason: '', presets, options: null as GroupCreationOptions | null, loading: false, saving: false, reviewing: false, loadError: '', saveError: '', conflict: false, sequence: 0, disposed: false } },
  computed: { selectedPreset() { return presets.find(item => item.key === this.preset)! }, policy(): GroupPolicyDraft { const permissions = [...this.selectedPreset.permissions]; return { name: this.name.trim(), description: this.description.trim(), redirectOnLogin: '/', permissions, pageRules: permissions.length ? [{ id: 'starting-access', path: '', match: 'START', deny: false, roles: permissions, locales: [] }] : [] } }, valid(): boolean { return Boolean(this.name.trim() && this.name.trim().length <= 255 && this.description.trim().length <= 1000 && this.options && this.policy.permissions.every(p => this.options!.allowedPermissions.includes(p))) } },
  watch: { modelValue: { immediate: true, handler(value: boolean) { if (value) { this.name = ''; this.description = ''; this.preset = 'empty'; this.reason = ''; this.reviewing = false; this.saveError = ''; void this.load() } else this.sequence++ } } },
  mounted() { window.addEventListener('beforeunload', this.beforeUnload) }, beforeUnmount() { this.disposed = true; this.sequence++; window.removeEventListener('beforeunload', this.beforeUnload) },
  methods: {
    async load() { const sequence = ++this.sequence; this.loading = true; this.loadError = ''; this.options = null; try { const options = await fetchGroupCreationOptions(); if (!this.disposed && sequence === this.sequence) { this.options = options; this.conflict = false; this.saveError = '' } } catch (error) { if (!this.disposed && sequence === this.sequence) this.loadError = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.sequence) this.loading = false } },
    permissionTitle(key: string) { return groupPermissions.find(p => p.key === key)?.title ?? key },
    async create() { if (!this.valid || !this.options || this.saving || this.conflict || this.reason.trim().length < 3) return; this.saving = true; this.saveError = ''; try { const result = await createReviewedGroup(this.policy, this.reason.trim(), this.options.fingerprint); this.name = ''; this.description = ''; this.reason = ''; this.$emit('created', result.id); this.$emit('update:modelValue', false) } catch (error) { this.conflict = [0,401,403,409].includes(groupRequestStatus(error)); this.saveError = getErrorMessage(error) + (groupRequestStatus(error) === 0 ? ` ${this.$t('admin:groupsCreate.outcomeUnconfirmedCheckDirectory')}` : '') } finally { this.saving = false } },
    async canLeave(): Promise<boolean> { return !this.saving && ((!this.modelValue || (!this.name && !this.description && !this.reason)) || await confirmDiscard(this.$t('admin:groupsCreate.discardNewGroupDraft'))) },
    async close(value: boolean) { if (!value && await this.canLeave()) this.$emit('update:modelValue', false) }, beforeUnload(event: BeforeUnloadEvent) { if (this.modelValue && (this.saving || this.name || this.description || this.reason)) { event.preventDefault(); event.returnValue = '' } }
  }
}
</script>
