<template>
  <v-container fluid class="admin-authoring">
    <admin-hero :title="$t('admin:editor.editors')" :description="$t('admin:editor.shapeHowPeopleCreate')" icon="mdi-pencil-ruler">
      <template #actions><v-btn variant="text" prepend-icon="mdi-refresh" :disabled="saving || reviewOpen" :loading="loading" @click="reload">{{ $t('admin:shell.reload') }}<v-tooltip activator="parent" location="bottom">{{ $t('admin:editor.reloadSavedEditorPolicy') }}</v-tooltip></v-btn><v-btn variant="flat" color="primary" :disabled="!dirty || loading || saving || !valid" @click="reviewOpen = true">{{ $t('admin:editor.reviewChanges') }}</v-btn></template>
    </admin-hero>
    <section class="authoring-intro"><div><span class="authoring-kicker">{{ $t('admin:editor.authoringExperience') }}</span><h2>{{ $t('admin:editor.goodStartingPointEvery') }}</h2><p>{{ $t('admin:editor.offerRightToolsRecommend') }}</p></div><dl><div><dt>{{ $t('admin:editor.availableDraft') }}</dt><dd>{{ loaded ? draft.available.length : '—' }}<small> / {{ editors.length }}</small></dd></div><div><dt>{{ $t('admin:editor.existingPages') }}</dt><dd>{{ loaded ? totalPages : '—' }}</dd></div><div><dt>{{ $t('admin:editor.chooserFormatsUse') }}</dt><dd>{{ loaded ? usedFormats : '—' }}</dd></div></dl></section>
    <v-alert v-if="success" type="success" variant="tonal" closable class="mb-4" @click:close="success = ''">{{ success }}</v-alert>
    <v-alert v-for="warning in warnings" :key="warning" type="warning" variant="tonal" class="mb-4">{{ warning }}</v-alert>
    <async-state v-if="loading" state="loading" :title="$t('admin:editor.loadingAuthoringWorkspace')" :message="$t('admin:editor.readingSavedPolicyEditor')" />
    <async-state v-else-if="loadError" state="error" :title="$t('admin:editor.editorSettingsCouldNot')" :message="loadError" :retry-label="$t('admin:editor.tryAgain')" @retry="reload" />
    <template v-else-if="loaded">
      <div class="authoring-tabs-row"><div class="authoring-tabs" role="tablist" :aria-label="$t('admin:editor.editorWorkspaceSections')"><button v-for="tab in tabs" :id="`authoring-tab-${tab.value}`" :key="tab.value" role="tab" :aria-selected="section === tab.value" :aria-controls="`authoring-panel-${tab.value}`" :tabindex="section === tab.value ? 0 : -1" @click="setSection(tab.value)" @keydown="tabKey($event, tab.value)">{{ tab.title }}</button></div><span class="authoring-draft-state" aria-live="polite">{{ dirty ? $t('admin:editor.unsavedPolicy') : $t('admin:editor.matchesSavedPolicy') }}</span></div>
      <div v-show="section === 'policy'" id="authoring-panel-policy" role="tabpanel" aria-labelledby="authoring-tab-policy" class="authoring-policy">
        <section class="authoring-catalogue"><div class="authoring-section-heading"><div><h3>{{ $t('admin:editor.availableNewPages') }}</h3><p>{{ $t('admin:editor.chooseEditorsBelongAuthoring') }}</p></div><v-btn size="small" variant="text" :disabled="saving || reviewOpen || allAvailable" @click="selectAll">{{ $t('admin:editor.enableAllRegistered') }}</v-btn></div>
          <div class="authoring-options"><article v-for="editor in editors" :key="editor.key" class="authoring-option" :class="{ 'is-enabled': enabled(editor.key) }"><div class="authoring-option-top"><v-icon :icon="editor.icon" size="28" /><span class="authoring-format">{{ editor.format }}</span></div><h4>{{ editor.title }}</h4><p>{{ editor.description }}</p><div class="authoring-option-usage"><span>{{ $t('admin:editor.existingPagesCount', { count: usage(editor.key).pages }) }}</span><small v-if="usage(editor.key).privatePages">{{ $t('admin:editor.private', { key: usage(editor.key).privatePages, interpolation: { escapeValue: false } }) }}</small></div><div class="authoring-option-control"><label><input type="checkbox" :checked="enabled(editor.key)" :disabled="saving || reviewOpen || (enabled(editor.key) && draft.available.length === 1) || (!enabled(editor.key) && !registered(editor.key))" :aria-label="$t('admin:editor.availability', { title: editor.title, interpolation: { escapeValue: false } })" @change="toggle(editor.key)" /><span>{{ enabled(editor.key) ? $t('admin:editor.availableCreation') : $t('admin:editor.hiddenCreation') }}</span></label><v-icon v-if="draft.recommended === editor.key" icon="mdi-star-outline" size="18" :aria-label="$t('admin:editor.workspaceRecommendation2')" /></div><p v-if="!registered(editor.key)" class="authoring-registration">{{ $t('admin:editor.missingServerRegistryRepair') }}</p></article></div>
          <p class="authoring-footnote">{{ $t('admin:editor.leastOneEditorStays') }}</p>
        </section>
        <aside class="authoring-guidance"><section class="authoring-recommendation"><span class="authoring-kicker">{{ $t('admin:editor.guideFirstChoice') }}</span><h3>{{ $t('admin:editor.workspaceRecommendation') }}</h3><p>{{ $t('admin:editor.putPreferredEditorFirst') }}</p><v-select v-model="draft.recommended" :items="recommendations" :label="$t('admin:editor.recommendedEditor')" variant="outlined" density="comfortable" hide-details :disabled="saving || reviewOpen" /><p v-if="recommendationNotice" class="authoring-notice" role="status">{{ recommendationNotice }}</p></section><section class="authoring-flow"><span class="authoring-kicker">{{ $t('admin:editor.newPageJourney') }}</span><ol><li><span>01</span><div><strong>{{ $t('admin:editor.startPage') }}</strong><small>{{ $t('admin:editor.authorChoosesLocationLanguage') }}</small></div></li><li><span>02</span><div><strong>{{ draft.available.length === 1 ? $t('admin:editor.open', { title: title(draft.available[0]!), interpolation: { escapeValue: false } }) : $t('admin:editor.chooseEditors', { availableCount: draft.available.length, interpolation: { escapeValue: false } }) }}</strong><small>{{ draft.available.length === 1 ? $t('admin:editor.oneOptionChooserSkipped') : draft.recommended ? $t('admin:editor.appearsFirstRecommendation', { recommended: title(draft.recommended), interpolation: { escapeValue: false } }) : $t('admin:editor.everyEnabledEditorOffered') }}</small></div></li><li><span>03</span><div><strong>{{ $t('admin:editor.writeChosenFormat') }}</strong><small>{{ $t('admin:editor.existingPagesContinueUsing') }}</small></div></li></ol><v-btn variant="text" size="small" append-icon="mdi-arrow-right" @click="setSection('preview')">{{ $t('admin:editor.previewStartingPoint') }}</v-btn></section><div class="authoring-reset"><span>{{ dirty ? $t('admin:editor.changesLocalUntilSaved') : $t('admin:editor.workspaceUsingPolicy') }}</span><v-btn variant="text" size="small" :disabled="!dirty || saving || reviewOpen" @click="reset">{{ $t('admin:editor.resetDraft') }}</v-btn></div></aside>
      </div>
      <section v-show="section === 'formats'" id="authoring-panel-formats" role="tabpanel" aria-labelledby="authoring-tab-formats" class="authoring-format-panel"><div class="authoring-section-heading"><div><span class="authoring-kicker">{{ $t('admin:editor.understandTradeoffs') }}</span><h3>{{ $t('admin:editor.toolsDifferSourceMatters') }}</h3><p>{{ $t('admin:editor.chooseFormatsFitAuthors') }}</p></div></div><div class="authoring-comparison" tabindex="0" role="region" :aria-label="$t('admin:editor.editorCapabilitiesUsage')"><table><thead><tr><th>{{ $t('admin:editor.title') }}</th><th>{{ $t('admin:editor.authoring') }}</th><th>{{ $t('admin:editor.storedSource') }}</th><th>{{ $t('common:actions.preview') }}</th><th>{{ $t('admin:editor.collaboration') }}</th><th>{{ $t('admin:editor.existingPages') }}</th></tr></thead><tbody><tr v-for="editor in editors" :key="editor.key"><th><v-icon :icon="editor.icon" size="19" />{{ editor.title }}<small>{{ enabled(editor.key) ? $t('admin:editor.availableDraft') : $t('admin:editor.hiddenDraft') }}</small></th><td>{{ editor.key === 'ckeditor' || editor.key === 'visual-markdown' ? $t('admin:editor.visualRichText') : $t('admin:editor.sourceEditing') }}</td><td>{{ editor.format }}</td><td>{{ editor.key === 'code' ? $t('admin:editor.sourceOnly') : editor.key === 'markdown' || editor.key === 'asciidoc' ? $t('admin:editor.livePreviewPane') : $t('admin:editor.inlineVisualEditing') }}</td><td>{{ editor.key === 'markdown' ? $t('admin:editor.liveCoediting') : $t('admin:editor.revisionChecks') }}</td><td><strong>{{ usage(editor.key).pages }}</strong><small>{{ $t('admin:editor.private', { key: usage(editor.key).privatePages, interpolation: { escapeValue: false } }) }}</small></td></tr></tbody></table></div><div class="authoring-format-notes"><article><h4>{{ $t('admin:editor.markdownPortableKnowledge') }}</h4><p>{{ $t('admin:editor.markdownVisualMarkdownShare') }}</p></article><article><h4>{{ $t('admin:editor.htmlAsciidocSpecificNeeds') }}</h4><p>{{ $t('admin:editor.visualHtmlCodeStore') }}</p></article><article><h4>{{ $t('admin:editor.usageCurrentSnapshot') }}</h4><p>{{ $t('admin:editor.countsIncludeAllCurrent') }}</p></article></div><v-alert v-if="otherUsage.length" type="info" variant="tonal" class="mt-5">{{ $t('admin:editor.pagesUseOtherEditor', { otherUsage: otherUsage.reduce((sum, row) => sum + row.pages, 0), otherUsage2: otherUsage.map(row => `${row.key} (${row.pages})`).join(', '), interpolation: { escapeValue: false } }) }}</v-alert></section>
      <section v-show="section === 'preview'" id="authoring-panel-preview" role="tabpanel" aria-labelledby="authoring-tab-preview" class="authoring-preview-panel"><div class="authoring-section-heading"><div><span class="authoring-kicker">{{ $t('admin:editor.beforeAuthorsSee') }}</span><h3>{{ $t('admin:editor.previewStartingPoint') }}</h3><p>{{ $t('admin:editor.compareDraftSavedPolicy') }}</p></div><div class="authoring-preview-toggle" role="group" :aria-label="$t('admin:editor.previewPolicy')"><button :aria-pressed="previewMode === 'draft'" @click="previewMode = 'draft'">{{ $t('admin:editor.draft') }}</button><button :aria-pressed="previewMode === 'saved'" @click="previewMode = 'saved'">{{ $t('admin:editor.saved') }}</button></div></div><div class="authoring-preview-window"><div class="authoring-preview-chrome"><v-icon icon="mdi-file-plus-outline" size="18" /><span>{{ $t('admin:editor.newPage') }}</span><small>{{ previewMode === 'draft' ? $t('admin:editor.draftPolicyPreview') : $t('admin:editor.savedPolicyPreview') }}</small></div><div v-if="previewPolicy.available.length === 1" class="authoring-direct-preview"><v-icon :icon="definition(previewPolicy.available[0]!).icon" size="42" /><h4>{{ $t('admin:editor.opensDirectly', { title: title(previewPolicy.available[0]!), interpolation: { escapeValue: false } }) }}</h4><p>{{ $t('admin:editor.oneEditorAvailableSo') }}</p><span class="authoring-preview-format">{{ $t('admin:editor.source', { available: definition(previewPolicy.available[0]!).format, interpolation: { escapeValue: false } }) }}</span></div><template v-else><div class="authoring-preview-title"><h4>{{ $t('admin:editor.howWouldYouLike') }}</h4><p>{{ $t('admin:editor.chooseEditorPage') }}</p></div><div class="authoring-preview-choices"><article v-for="editor in previewEditors" :key="editor.key" :class="{ 'is-recommended': previewPolicy.recommended === editor.key }"><div><v-icon :icon="editor.icon" size="24" /><span v-if="previewPolicy.recommended === editor.key">{{ $t('admin:editor.recommended') }}</span></div><h5>{{ editor.title }}</h5><p>{{ editor.chooserDescription }}</p><small>{{ $t('admin:editor.source2', { format: editor.format, interpolation: { escapeValue: false } }) }}</small></article><article class="authoring-template-preview"><v-icon icon="mdi-content-copy" size="24" /><h5>{{ $t('admin:editor.template') }}</h5><p>{{ $t('admin:editor.reuseExistingPageStarting') }}</p><small>{{ $t('admin:editor.sourceAccessCreationPolicy') }}</small></article></div></template></div></section>
    </template>
    <v-dialog v-model="reviewOpen" max-width="720" :persistent="saving" aria-labelledby="authoring-review-title"><v-card class="authoring-review"><div class="authoring-review-heading"><span class="authoring-kicker">{{ $t('admin:editor.reviewNewPagePolicy') }}</span><h3 id="authoring-review-title">{{ $t('admin:editor.clearerStartingPoint') }}</h3><p>{{ $t('admin:editor.changesEditorsOfferedNew') }}</p></div><v-card-text><div class="authoring-review-diff"><section><h4>{{ $t('admin:editor.enableCreation') }}</h4><ul v-if="added.length"><li v-for="key in added" :key="key">{{ title(key) }}</li></ul><p v-else>{{ $t('admin:editor.noEditorsAdded') }}</p></section><section><h4>{{ $t('admin:editor.hideCreation') }}</h4><ul v-if="removed.length"><li v-for="key in removed" :key="key">{{ title(key) }}<small>{{ $t('admin:editor.existingPagesRemainEditable', { value: usage(key).pages, interpolation: { escapeValue: false } }) }}</small></li></ul><p v-else>{{ $t('admin:editor.noEditorsHidden') }}</p></section></div><div class="authoring-review-recommendation"><span>{{ $t('admin:editor.workspaceRecommendation2') }}</span><strong>{{ saved?.recommended ? title(saved.recommended) : $t('admin:editor.none') }} → {{ draft.recommended ? title(draft.recommended) : $t('admin:editor.none') }}</strong></div><p class="authoring-footnote">{{ $t('admin:editor.newlyOpenedCreationFlows', { value: draft.available.length === 1 ? $t('admin:editor.willOpenDirectlyNew', { title: title(draft.available[0]!), interpolation: { escapeValue: false } }) : $t('admin:editor.chooserWillOfferEditors', { availableCount: draft.available.length, recommended: draft.recommended ? `, with ${title(draft.recommended)} first` : '', interpolation: { escapeValue: false } }), interpolation: { escapeValue: false } }) }}</p><v-alert v-if="saveError" type="error" variant="tonal" class="mt-4">{{ saveError }}<div><v-btn variant="text" size="small" class="mt-2" :disabled="saving" @click="reloadFromReview">{{ $t('admin:editor.reloadSavedPolicy') }}</v-btn></div></v-alert></v-card-text><v-card-actions><v-btn variant="text" :disabled="saving" @click="reviewOpen = false">{{ $t('common:actions.cancel') }}</v-btn><v-spacer /><v-btn variant="flat" color="primary" :loading="saving" :disabled="saving || !valid || !dirty" @click="save">{{ $t('admin:editor.saveEditorPolicy') }}</v-btn></v-card-actions></v-card></v-dialog>
  </v-container>
</template>
<script lang="ts">
import { confirmDiscard } from '../common/confirm-dialog.ts'
import AsyncState from '@/components/common/async-state.vue'
import { PAGE_EDITOR_DEFINITIONS, type PageEditorDefinition } from '../../helpers/page-editors.ts'
import { fetchEditorWorkspace, saveEditorWorkspace } from '../../helpers/editor-policy-api.ts'
import { validateEditorPolicy, type EditorPolicy, type EditorPolicySnapshot, type EditorUsage } from '../../../shared/editor-policy.ts'
import type { PageEditorKey } from '../../../shared/page-editors.ts'
import { getErrorMessage } from '../../helpers/root-ui-store.ts'
export default {
  components: { AsyncState },
  data() { return { editors: PAGE_EDITOR_DEFINITIONS, draft: { available: [], recommended: null } as EditorPolicy, saved: null as EditorPolicySnapshot | null, registeredKeys: [] as string[], counts: [] as EditorUsage[], loading: true, loadError: '', saving: false, saveError: '', reviewOpen: false, success: '', warnings: [] as string[], recommendationNotice: '', section: 'policy', previewMode: 'draft',
    tabs: [{ title: this.$t('admin:editor.creationPolicy'), value: 'policy' }, { title: this.$t('admin:editor.formatsUsage'), value: 'formats' }, { title: this.$t('admin:editor.authorPreview'), value: 'preview' }] } },
  computed: {
    loaded(): boolean { return Boolean(this.saved) && !this.loadError },
    dirty(): boolean { return Boolean(this.saved && (this.saved.recommended !== this.draft.recommended || this.saved.available.join(',') !== this.draft.available.join(','))) },
    valid(): boolean { return validateEditorPolicy(this.draft).ok && this.draft.available.every(this.registered) },
    allAvailable(): boolean { return this.editors.filter(editor => this.registered(editor.key)).every(editor => this.enabled(editor.key)) },
    recommendations() { return [{ title: this.$t('admin:editor.noRecommendation'), value: null }, ...this.editors.filter(editor => this.enabled(editor.key)).map(editor => ({ title: editor.title, value: editor.key }))] },
    totalPages(): number { return this.counts.reduce((sum, row) => sum + row.pages, 0) },
    usedFormats(): number { return new Set(this.editors.filter(editor => this.usage(editor.key).pages > 0).map(editor => editor.format)).size },
    otherUsage(): EditorUsage[] { return this.counts.filter(row => !this.editors.some(editor => editor.key === row.key)) },
    added(): PageEditorKey[] { return this.draft.available.filter(key => !this.saved?.available.includes(key)) },
    removed(): PageEditorKey[] { return this.saved?.available.filter(key => !this.draft.available.includes(key)) ?? [] },
    previewPolicy(): EditorPolicy { return this.previewMode === 'saved' && this.saved ? this.saved : this.draft },
    previewEditors(): PageEditorDefinition[] { return this.editors.filter(editor => this.previewPolicy.available.includes(editor.key)).sort((a, b) => Number(b.key === this.previewPolicy.recommended) - Number(a.key === this.previewPolicy.recommended)) }
  },
  methods: {
    enabled(key: PageEditorKey): boolean { return this.draft.available.includes(key) },
    registered(key: PageEditorKey): boolean { return this.registeredKeys.includes(key) },
    definition(key: PageEditorKey): PageEditorDefinition { return this.editors.find(editor => editor.key === key)! },
    title(key: PageEditorKey): string { return this.definition(key).title },
    usage(key: string): EditorUsage { return this.counts.find(row => row.key === key) ?? { key, pages: 0, privatePages: 0 } },
    toggle(key: PageEditorKey) { if (this.saving || this.reviewOpen || (this.enabled(key) && this.draft.available.length === 1) || (!this.enabled(key) && !this.registered(key))) return; const selected = new Set(this.draft.available); if (selected.has(key)) selected.delete(key); else selected.add(key); this.draft.available = this.editors.filter(editor => selected.has(editor.key)).map(editor => editor.key); if (this.draft.recommended && !selected.has(this.draft.recommended)) { this.recommendationNotice = this.$t('admin:editor.wasHiddenSoRecommendation', { recommended: this.title(this.draft.recommended), interpolation: { escapeValue: false } }); this.draft.recommended = null } this.saveError = '' },
    selectAll() { const available = this.editors.filter(editor => this.registered(editor.key)).map(editor => editor.key); if (!available.length) return; this.draft.available = available; if (this.draft.recommended && !available.includes(this.draft.recommended)) this.draft.recommended = null },
    reset() { if (this.saved) this.draft = { available: [...this.saved.available], recommended: this.saved.recommended }; this.recommendationNotice = ''; this.saveError = '' },
    setSection(value: string) { this.section = value; this.$router.replace({ hash: `#${value}` }) },
    tabKey(event: KeyboardEvent, value: string) { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return; event.preventDefault(); const index = this.tabs.findIndex(tab => tab.value === value), next = event.key === 'Home' ? 0 : event.key === 'End' ? 2 : (index + (event.key === 'ArrowRight' ? 1 : -1) + 3) % 3; this.setSection(this.tabs[next]!.value); this.$nextTick(() => document.getElementById(`authoring-tab-${this.section}`)?.focus()) },
    async reload() { if (this.saving || (this.dirty && !(await confirmDiscard(this.$t('admin:editor.discardUnsavedEditorPolicy')))) || this.saving) return; this.loading = true; this.loadError = ''; try { const result = await fetchEditorWorkspace(); this.saved = result.policy; this.registeredKeys = result.registered; this.counts = result.usage; this.reset() } catch (error) { this.loadError = getErrorMessage(error) } finally { this.loading = false } },
    async reloadFromReview() { if (this.saving) return; if (this.dirty && !(await confirmDiscard(this.$t('admin:editor.discardUnsavedEditorPolicy2')))) return; this.reviewOpen = false; this.reset(); await this.reload() },
    async save() { if (!this.saved || this.saving || !this.valid || !this.dirty) return; this.saving = true; this.saveError = ''; const draft = { available: [...this.draft.available], recommended: this.draft.recommended }; try { const result = await saveEditorWorkspace(draft, this.saved.fingerprint); this.saved = result.policy; this.reset(); siteConfig.availableEditors = [...result.policy.available]; siteConfig.recommendedEditor = result.policy.recommended; this.warnings = result.warnings; this.success = this.$t('admin:editor.editorPolicySavedNew'); this.reviewOpen = false } catch (error) { this.saveError = getErrorMessage(error) } finally { this.saving = false } },
    beforeUnload(event: BeforeUnloadEvent) { if (this.dirty || this.saving) { event.preventDefault(); event.returnValue = '' } }
  },
  watch: { '$route.hash'(hash: string) { const value = hash.slice(1); if (this.tabs.some(tab => tab.value === value)) this.section = value } },
  async beforeRouteLeave() { return !this.saving && (!this.dirty || await confirmDiscard(this.$t('admin:editor.discardUnsavedEditorPolicy3'))) },
  mounted() { const hash = this.$route.hash.slice(1); if (this.tabs.some(tab => tab.value === hash)) this.section = hash; this.reload(); window.addEventListener('beforeunload', this.beforeUnload) },
  beforeUnmount() { window.removeEventListener('beforeunload', this.beforeUnload) }
}
</script>
<style lang="scss" scoped>
.admin-authoring { --authoring-border:rgba(var(--v-theme-on-surface),.13); --authoring-muted:var(--wiki-text-muted); }
.authoring-kicker { display:block; font-size:.65rem; font-weight:700; letter-spacing:.14em; text-transform:uppercase; color:var(--authoring-muted); }
.authoring-intro { display:flex; align-items:center; justify-content:space-between; gap:2rem; padding:1.8rem 0 2rem; h2 { font-size:clamp(1.4rem,2.3vw,1.9rem); font-weight:600; letter-spacing:-.04em; line-height:1.2; margin:.6rem 0; } p { font-size:.84rem; line-height:1.75; max-width:620px; color:var(--authoring-muted); margin:0; } dl { display:flex; gap:2rem; flex-shrink:0; } dt { font-size:.67rem; color:var(--authoring-muted); } dd { margin:.5rem 0 0; font-size:1.9rem; line-height:1; font-weight:550; } dd small { font-size:.8rem; color:var(--authoring-muted); } }
.authoring-tabs-row { display:flex; align-items:center; gap:.8rem; border-block:1px solid var(--authoring-border); margin-bottom:1.7rem; }
.authoring-tabs { display:flex; align-items:center; gap:.8rem; button { border:0; border-bottom:2px solid transparent; background:transparent; color:var(--authoring-muted); padding:.9rem .5rem; font-size:.8rem; white-space:nowrap; &[aria-selected=true] { color:rgb(var(--v-theme-on-surface)); border-bottom-color:rgb(var(--v-theme-primary)); font-weight:650; } &:focus-visible { outline:2px solid rgb(var(--v-theme-on-surface)); outline-offset:-3px; } } }
.authoring-draft-state { margin-left:auto; font-size:.68rem; color:var(--authoring-muted); }
.authoring-policy { display:grid; grid-template-columns:minmax(0,2fr) minmax(260px,1fr); gap:1.6rem; align-items:start; }
.authoring-section-heading { display:flex; justify-content:space-between; align-items:center; gap:1rem; margin-bottom:1.2rem; h3 { font-size:1.12rem; font-weight:600; letter-spacing:-.02em; margin:.35rem 0 .4rem; } p { margin:0; color:var(--authoring-muted); font-size:.77rem; line-height:1.75; } }
.authoring-options { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:.85rem; }
.authoring-option { display:flex; flex-direction:column; min-width:0; border:1px solid var(--authoring-border); border-radius:10px; background:rgb(var(--v-theme-surface)); padding:1.15rem; &.is-enabled { border-color:rgba(var(--v-theme-primary),.4); } h4 { font-size:1rem; font-weight:600; margin:.9rem 0 .4rem; letter-spacing:-.02em; } >p { font-size:.74rem; color:var(--authoring-muted); line-height:1.75; margin:0 0 1rem; flex:1; } }
.authoring-option-top { display:flex; justify-content:space-between; align-items:center; .v-icon { color:var(--wiki-primary-ink); } }
.authoring-format { font-size:.65rem; padding:.25rem .5rem; border:1px solid var(--authoring-border); border-radius:4px; color:var(--authoring-muted); }
.authoring-option-usage { display:flex; justify-content:space-between; align-items:center; gap:.5rem; font-size:.69rem; padding:.6rem 0; small { color:var(--authoring-muted); } }
.authoring-option-control { display:flex; align-items:center; justify-content:space-between; gap:.6rem; border-top:1px solid var(--authoring-border); padding-top:.8rem; label { display:flex; align-items:center; gap:.6rem; font-size:.73rem; cursor:pointer; } input { width:17px; height:17px; flex-shrink:0; accent-color:rgb(var(--v-theme-primary)); } }
.authoring-registration { font-size:.68rem!important; margin:.8rem 0 0!important; }
.authoring-footnote { font-size:.72rem; line-height:1.8; color:var(--authoring-muted); margin:1rem 0 0; }
.authoring-guidance { display:grid; gap:1rem; min-width:0; }
.authoring-recommendation,.authoring-flow { background:rgb(var(--v-theme-surface)); border:1px solid var(--authoring-border); border-radius:10px; padding:1.3rem; h3 { font-size:1rem; font-weight:600; margin:.7rem 0 .5rem; } p { color:var(--authoring-muted); font-size:.76rem; line-height:1.8; margin:0 0 1.2rem; } }
.authoring-flow ol { list-style:none; padding:0; margin:1rem 0; li { display:flex; gap:.8rem; position:relative; padding-bottom:1.5rem; &:last-child { padding-bottom:0; } >span { border:1px solid var(--authoring-border); border-radius:50%; width:27px; height:27px; display:grid; place-items:center; flex-shrink:0; font-size:.6rem; } strong { display:block; font-size:.77rem; font-weight:550; margin:.2rem 0 .3rem; } small { display:block; font-size:.7rem; line-height:1.7; color:var(--authoring-muted); } } }
.authoring-reset { display:flex; align-items:center; justify-content:space-between; flex-wrap:wrap; gap:.6rem; padding:.2rem; span { font-size:.7rem; color:var(--authoring-muted); } }
.authoring-notice { margin:.75rem 0 0!important; font-size:.7rem!important; }
.authoring-format-panel,.authoring-preview-panel { min-width:0; }
.authoring-comparison { overflow:auto; border:1px solid var(--authoring-border); border-radius:10px; background:rgb(var(--v-theme-surface)); table { border-collapse:collapse; width:100%; text-align:left; font-size:.75rem; } th,td { padding:1rem; border-bottom:1px solid var(--authoring-border); min-width:115px; vertical-align:middle; } thead th { font-size:.66rem; font-weight:600; color:var(--authoring-muted); } tbody th { font-weight:600; min-width:200px; .v-icon { margin-right:.6rem; } } small { display:block; font-size:.65rem; color:var(--authoring-muted); margin-top:.4rem; font-weight:400; } }
.authoring-format-notes { display:grid; grid-template-columns:repeat(3,1fr); gap:1.6rem; margin-top:1.7rem; h4 { font-size:.86rem; font-weight:600; margin-bottom:.6rem; } p { font-size:.74rem; line-height:1.8; color:var(--authoring-muted); margin:0; } }
.authoring-preview-toggle { display:flex; border:1px solid var(--authoring-border); border-radius:6px; padding:3px; button { color:var(--authoring-muted); border:0; background:transparent; padding:.4rem .7rem; border-radius:4px; font-size:.73rem; &[aria-pressed=true] { background:rgba(var(--v-theme-on-surface),.08); color:rgb(var(--v-theme-on-surface)); } } }
.authoring-preview-window { max-width:850px; margin:1.6rem auto 0; border:1px solid var(--authoring-border); border-radius:12px; background:rgb(var(--v-theme-surface)); overflow:hidden; }
.authoring-preview-chrome { display:flex; align-items:center; gap:.7rem; padding:1rem 1.4rem; border-bottom:1px solid var(--authoring-border); font-size:.8rem; small { margin-left:auto; color:var(--authoring-muted); font-size:.65rem; } }
.authoring-preview-title { padding:1.7rem 1.7rem 0; h4 { font-size:1.3rem; font-weight:600; letter-spacing:-.03em; } p { font-size:.8rem; color:var(--authoring-muted); margin:.5rem 0 0; } }
.authoring-preview-choices { padding:1.4rem 1.7rem 1.7rem; display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:.85rem; article { border:1px solid var(--authoring-border); border-radius:8px; padding:1.2rem; >div { display:flex; justify-content:space-between; gap:.5rem; align-items:center; } &.is-recommended { border-color:rgba(var(--v-theme-primary),.65); background:rgba(var(--v-theme-primary),.04); } h5 { font-size:.9rem; font-weight:600; margin:.75rem 0 .4rem; } p { font-size:.73rem; line-height:1.7; color:var(--authoring-muted); margin:0 0 .8rem; } small,span { font-size:.65rem; color:var(--authoring-muted); } } .authoring-template-preview { border-style:dashed; } }
.authoring-direct-preview { text-align:center; padding:3.5rem 2rem; h4 { font-size:1.3rem; font-weight:600; margin:1rem 0 .6rem; } p { max-width:380px; margin:0 auto 1rem; font-size:.8rem; line-height:1.8; color:var(--authoring-muted); } }
.authoring-preview-format { font-size:.7rem; border:1px solid var(--authoring-border); padding:.4rem .7rem; border-radius:5px; }
.authoring-review { --authoring-border:rgba(var(--v-theme-on-surface),.13); --authoring-muted:var(--wiki-text-muted); .v-card-actions { padding:1rem 1.5rem; border-top:1px solid var(--authoring-border); } }
.authoring-review-heading { padding:1.6rem 1.5rem 1rem; h3 { font-size:1.5rem; font-weight:600; letter-spacing:-.04em; margin:.6rem 0; } p { font-size:.8rem; color:var(--authoring-muted); line-height:1.8; margin:0; } }
.authoring-review-diff { display:grid; grid-template-columns:1fr 1fr; gap:1.4rem; h4 { font-size:.8rem; font-weight:600; } ul { padding-left:1rem; font-size:.8rem; margin:.7rem 0 0; } li { padding:.3rem 0; } small { display:block; font-size:.68rem; color:var(--authoring-muted); margin-top:.3rem; } p { font-size:.73rem; color:var(--authoring-muted); margin:.7rem 0 0; } }
.authoring-review-recommendation { display:grid; gap:.5rem; border-block:1px solid var(--authoring-border); padding:1rem 0; margin-top:1.4rem; span { font-size:.68rem; color:var(--authoring-muted); } strong { font-size:.9rem; font-weight:550; } }
@media(max-width:1150px) { .authoring-intro { align-items:flex-start; flex-direction:column; gap:1.4rem; } .authoring-policy { grid-template-columns:minmax(0,1.8fr) minmax(230px,1fr); gap:1rem; } .authoring-section-heading { align-items:flex-start; flex-wrap:wrap; } .authoring-options { grid-template-columns:1fr; } }
@media(max-width:760px) { .authoring-policy { grid-template-columns:1fr; } .authoring-guidance { grid-row:1; } .authoring-flow { display:none; } .authoring-tabs-row { flex-wrap:wrap; gap:0; } .authoring-tabs { gap:.2rem; button { font-size:.7rem; padding:.9rem .45rem; } } .authoring-draft-state { flex-basis:100%; margin:0 0 .7rem .45rem; } .authoring-format-notes { grid-template-columns:1fr; gap:1.2rem; } .authoring-intro dl { gap:1.8rem; dt { font-size:.62rem; } dd { font-size:1.6rem; } } .authoring-preview-choices { grid-template-columns:1fr; padding:1.2rem; } .authoring-preview-title { padding:1.2rem 1.2rem 0; } .authoring-preview-chrome { padding:1rem; gap:.5rem; small { font-size:.58rem; } } .authoring-review-diff { grid-template-columns:1fr; gap:1.2rem; } .authoring-direct-preview { padding:2.5rem 1.3rem; } }
</style>
