<template>
  <section aria-labelledby="group-access-heading"><div class="group-heading"><div><span class="group-kicker">{{ $t('admin:groupsAccess.understandDecision') }}</span><h2 id="group-access-heading">{{ $t('admin:groupsAccess.accessCheck') }}</h2><p>{{ $t('admin:groupsAccess.testHypotheticalPublicPage') }}</p></div></div>
    <div class="group-access-layout"><form class="group-surface group-access-form" @submit.prevent="evaluate"><v-select v-model="scope" :items="[{ title: $t('admin:groupsAccess.groupOnly'), value: 'group' },{ title: $t('admin:groupsAccess.membersCombinedGroups'), value: 'member' }]" :label="$t('admin:groupsAccess.whosePolicy')" variant="outlined" hide-details :disabled="loading" />
        <v-autocomplete v-if="scope === 'member'" v-model="memberId" v-model:search="memberSearch" :items="memberOptions" item-title="title" item-value="id" :label="$t('admin:groupsAccess.currentGroupMember')" variant="outlined" hide-details no-filter clearable :loading="memberLoading" :disabled="loading" @update:search="searchMembers" /><v-alert v-if="memberError && scope === 'member'" type="error" variant="tonal">{{ memberError }}<v-btn variant="text" @click="searchMembers">{{ $t('admin:groupsAccess.tryAgain') }}</v-btn></v-alert>
        <v-select v-model="permission" :items="actions" :label="$t('admin:groupsAccess.pageAction')" variant="outlined" hide-details :disabled="loading" /><v-text-field v-model="path" :label="$t('admin:groupsAccess.publicPagePath')" variant="outlined" :hint="$t('admin:groupsAccess.noLeadingDoesNot')" persistent-hint :disabled="loading" maxlength="500" /><div class="group-form-grid"><v-text-field v-model="locale" :label="$t('admin:groupsAccess.language')" variant="outlined" hide-details :disabled="loading" maxlength="24" /><v-combobox v-model="tags" :label="$t('admin:groupsAccess.pageTags')" variant="outlined" hide-details multiple chips closable-chips :disabled="loading" /></div>
        <v-checkbox v-if="hasDraft" v-model="useDraft" :label="$t('admin:groupsAccess.includeGroupsUnsavedPolicy')" hide-details :disabled="loading" /><p v-else class="group-note">{{ $t('admin:groupsAccess.usesSavedPolicyChanges') }}</p><v-btn color="primary" variant="flat" type="submit" prepend-icon="mdi-shield-search" :loading="loading" :disabled="!valid">{{ $t('admin:groupsAccess.checkAccess') }}</v-btn>
      </form><div class="group-access-output"><async-state v-if="loading" state="loading" :title="$t('admin:groupsAccess.evaluatingGroupAccess')" /><async-state v-else-if="error" state="error" :title="$t('admin:groupsAccess.accessCouldNotChecked')" :message="error" :retry-label="$t('admin:groupsAccess.tryAgain')" @retry="evaluate" /><div v-else-if="!result" class="group-access-intro"><v-icon icon="mdi-shield-search" size="36" /><h3>{{ $t('admin:groupsAccess.resultYouCanFollow') }}</h3><p>{{ $t('admin:groupsAccess.seeWhichMatchingRules') }}</p></div>
        <template v-else><div class="group-access-result" :class="result.allowed ? 'is-allowed' : 'is-denied'"><span class="group-kicker">{{ result.source === 'draft' ? $t('admin:groupsAccess.draftPolicyEvaluation') : $t('admin:groupsAccess.savedPolicyEvaluation') }}</span><h3><v-icon :icon="result.allowed ? 'mdi-check-circle-outline' : 'mdi-minus-circle-outline'" />{{ result.allowed ? $t('admin:groupsAccess.allowedGroupPolicy') : $t('admin:groupsAccess.deniedGroupPolicy') }}</h3><p>{{ result.reason }}</p><small>{{ result.subject }} · {{ checkedPermission }} · /{{ checkedPath }}</small></div><v-alert v-if="outdated" type="info" variant="tonal" class="my-4">{{ $t('admin:groupsAccess.inputsPolicyChangedAfter') }}</v-alert><div class="group-heading mt-5 mb-3"><h3 id="group-access-rules-heading" class="text-title-small">{{ $t('admin:groupsAccess.ruleExplanation') }}</h3><span class="group-note">{{ $t('admin:groupsAccess.evaluated', { ruleCount: result.ruleCount, interpolation: { escapeValue: false } }) }}</span></div><p v-if="!result.rules.length" class="group-note">{{ $t('admin:groupsAccess.noPageRulesContributed') }}</p><div v-else role="region" aria-labelledby="group-access-rules-heading" tabindex="0" class="group-access-rules-scroll"><ol class="group-access-rules"><li v-for="(rule, index) in result.rules" :key="rule.groupId + ':' + rule.ruleId + ':' + index"><span class="group-access-outcome" :class="{ 'is-winner': rule.outcome === 'winner' }">{{ outcomeTitles[rule.outcome] }}</span><div><strong>{{ rule.groupName }}</strong><span>{{ rule.deny ? $t('admin:groupsAccess.deny') : $t('admin:groupsAccess.allow') }} · {{ matchTitles[rule.match] }} <code>{{ rule.path || $t('admin:groupsAccess.allPaths') }}</code></span></div></li></ol></div><p v-if="result.rulesTruncated" class="group-note mt-3">{{ $t('admin:groupsAccess.showingRulesMatchingRules', { rulesCount: result.rules.length, ruleCount: result.ruleCount, interpolation: { escapeValue: false } }) }}</p></template>
        <p class="group-access-boundary">{{ $t('admin:groupsAccess.checksPublicPagePermission') }}</p>
      </div></div>
  </section>
</template>
<script lang="ts">
import { type PropType } from 'vue'
import AsyncState from '@/components/common/async-state.vue'
import { groupPermissions, type GroupPolicyDraft, type GroupAccessResult, type GroupAccessInput } from '../../../shared/group-policy.ts'
import { fetchGroupMembers, evaluateGroupPolicy, groupPolicySignature, groupPolicyCopy } from '../../helpers/group-workspace-api.ts'
import { getErrorMessage } from '../../helpers/root-ui-store.ts'
export default {
  components: { AsyncState }, props: { groupId: { type: Number, required: true }, revision: { type: String, required: true }, draft: { type: Object as PropType<GroupPolicyDraft>, required: true }, hasDraft: Boolean, initialMember: { type: Object as PropType<{ id: number; name: string } | null>, default: null } },
  data() { return { scope: 'group', memberId: null as number | null, memberSearch: '', memberOptions: [] as Array<{ id: number; title: string }>, memberLoading: false, memberError: '', memberSequence: 0, memberTimer: null as ReturnType<typeof setTimeout> | null, permission: 'read:pages', path: 'home', locale: 'en', tags: [] as string[], useDraft: true, loading: false, error: '', result: null as GroupAccessResult | null, checkedSignature: '', checkedPermission: '', checkedPath: '', sequence: 0, disposed: false, actions: groupPermissions.filter(p => p.pageScoped).map(p => ({ title: p.title, value: p.key })), outcomeTitles: { winner: this.$t('admin:groupsAccess.highestPriorityMatch'), overridden: this.$t('admin:groupsAccess.overridden'), 'no-match': this.$t('admin:groupsAccess.doesNotMatch'), locale: this.$t('admin:groupsAccess.differentLanguage'), permission: this.$t('admin:groupsAccess.differentAction') }, matchTitles: { START: this.$t('admin:groupsAccess.prefix'), END: this.$t('admin:groupsAccess.suffix'), EXACT: this.$t('admin:groupsAccess.exactPath'), SUBTREE: this.$t('admin:groupsAccess.pathDescendant'), REGEX: this.$t('admin:groupsAccess.regex'), TAG: this.$t('admin:groupsAccess.tag') } } },
  computed: { valid(): boolean { return this.scope !== 'member' || this.memberId !== null }, signature(): string { return JSON.stringify([this.groupId, this.revision, this.scope, this.memberId, this.permission, this.path, this.locale, this.tags, this.hasDraft && this.useDraft ? groupPolicySignature(this.draft) : null]) }, outdated(): boolean { return Boolean(this.result && this.checkedSignature !== this.signature) } },
  watch: { initialMember: { immediate: true, handler(member: { id: number; name: string } | null) { if (member) { this.scope = 'member'; this.memberOptions = [{ id: member.id, title: member.name }]; this.memberId = member.id } } }, groupId() { this.sequence++; this.result = null; this.error = ''; this.memberSequence++; this.memberId = null; this.memberOptions = []; this.memberSearch = ''; this.scope = 'group' }, scope(value: string) { if (value === 'member') this.searchMembers() } },
  beforeUnmount() { this.disposed = true; this.sequence++; this.memberSequence++; if (this.memberTimer) clearTimeout(this.memberTimer) },
  methods: {
    async evaluate() { if (this.loading || !this.valid) return; const sequence = ++this.sequence, signature = this.signature, input: GroupAccessInput = { path: this.path.trim(), locale: this.locale.trim(), tags: [...this.tags], permission: this.permission, ...(this.scope === 'member' ? { memberId: this.memberId! } : {}), ...(this.hasDraft && this.useDraft ? { draft: groupPolicyCopy(this.draft) } : {}) }; this.loading = true; this.error = ''; try { const result = await evaluateGroupPolicy(this.groupId, input); if (!this.disposed && sequence === this.sequence) { this.result = result; this.checkedSignature = signature; this.checkedPath = input.path; this.checkedPermission = this.actions.find(action => action.value === input.permission)?.title ?? input.permission } } catch (error) { if (!this.disposed && sequence === this.sequence) this.error = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.sequence) this.loading = false } },
    searchMembers() { if (this.memberTimer) clearTimeout(this.memberTimer); const sequence = ++this.memberSequence, search = this.memberSearch || ''; this.memberTimer = setTimeout(async () => { this.memberLoading = true; this.memberError = ''; try { const result = await fetchGroupMembers(this.groupId, new URLSearchParams({ search, limit: '25' })); if (!this.disposed && sequence === this.memberSequence) { const selected = this.memberOptions.find(item => item.id === this.memberId); this.memberOptions = result.items.map(person => ({ id: person.id, title: `${person.name} · ${person.email}` })); if (selected && !this.memberOptions.some(item => item.id === selected.id)) this.memberOptions.unshift(selected) } } catch (error) { if (!this.disposed && sequence === this.memberSequence) this.memberError = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.memberSequence) this.memberLoading = false } }, 250) }
  }
}
</script>
<style scoped>
.group-access-rules-scroll { max-height: 660px; overflow: auto; }
.group-access-rules-scroll:focus-visible { outline: 2px solid rgb(var(--v-theme-primary)); outline-offset: 3px; }
.group-access-rules-scroll .group-access-rules { max-height: none; overflow: visible; }
</style>
