<template>
  <section aria-labelledby="group-rules-heading"><div class="group-heading"><div><span class="group-kicker">{{ $t('admin:groupsEditRules.wherePageActionsApply') }}</span><h2 id="group-rules-heading">{{ $t('admin:groupsEditRules.pageRules') }}</h2><p>{{ $t('admin:groupsEditRules.describePublicPagesGroup') }}</p></div><v-btn v-if="!unrestricted" variant="outlined" prepend-icon="mdi-plus" :disabled="disabled || modelValue.pageRules.length >= 100" @click="open()">{{ $t('admin:groupsEditRules.addPageRule2') }}</v-btn></div>
    <v-alert v-if="unrestricted" type="info" variant="tonal">{{ $t('admin:groupsEditRules.fullSystemAdministrationBypasses') }}</v-alert>
    <template v-else><div class="group-rule-guide"><v-icon icon="mdi-sort-variant" size="21" /><p><strong>{{ $t('admin:groupsEditRules.specificityDeterminesResult') }}</strong> {{ $t('admin:groupsEditRules.longerMatchingTextWins') }} <button type="button" @click="$emit('evaluate')">{{ $t('admin:groupsEditRules.tryAccessCheck') }} <v-icon icon="mdi-arrow-right" size="16" /></button></p></div>
      <async-state v-if="!modelValue.pageRules.length" state="empty" :title="$t('admin:groupsEditRules.noPublicPageRules')" :message="$t('admin:groupsEditRules.groupContributesNoPage')" />
      <ol v-else class="group-rule-list"><li v-for="(rule, index) in modelValue.pageRules" :key="rule.id" class="group-rule-card"><div class="group-rule-top"><span class="group-rule-effect" :class="rule.deny ? 'is-deny' : 'is-allow'"><v-icon :icon="rule.deny ? 'mdi-minus-circle-outline' : 'mdi-check-circle-outline'" size="18" />{{ rule.deny ? $t('admin:groupsEditRules.deny') : $t('admin:groupsEditRules.allow') }}</span><span class="group-muted text-body-small">{{ $t('admin:groupsEditRules.rule', { value: index + 1, interpolation: { escapeValue: false } }) }}</span><div class="group-actions"><v-btn icon="mdi-pencil-outline" variant="text" size="small" :aria-label="$t('admin:groupsEditRules.editPageRule', { value: (index + 1), interpolation: { escapeValue: false } })" :disabled="disabled" @click="open(rule)" /><v-btn icon="mdi-close" variant="text" size="small" :aria-label="$t('admin:groupsEditRules.removePageRule', { value: (index + 1), interpolation: { escapeValue: false } })" :disabled="disabled" @click="remove(rule.id)" /></div></div><div class="group-rule-target"><span>{{ matchTitle(rule.match) }}</span><code>{{ rule.path || $t('admin:groupsEditRules.allPaths') }}</code></div><div class="group-rule-actions">{{ rule.roles.map(permissionTitle).join(' · ') }}</div><div class="group-rule-footer"><span>{{ rule.locales.length ? rule.locales.join(', ') : $t('admin:groupsEditRules.anyLanguage') }}</span><span v-if="missingPermissions(rule).length" class="group-rule-inactive">{{ $t('admin:groupsEditRules.actionSLackPermission', { value: missingPermissions(rule).length, interpolation: { escapeValue: false } }) }}</span></div></li></ol>
    </template>
    <v-dialog v-model="dialog" max-width="720" :fullscreen="$vuetify.display.smAndDown" :persistent="disabled" aria-labelledby="group-rule-title" @update:model-value="onClose"><v-card class="group-dialog group-rule-dialog"><div class="group-dialog-header"><h2 id="group-rule-title">{{ editingId ? $t('admin:groupsEditRules.editPageRule2') : $t('admin:groupsEditRules.addPageRule') }}</h2><p>{{ $t('admin:groupsEditRules.changesPolicyDraftReview') }}</p></div><v-card-text><div class="group-dialog-fields"><v-select v-model="draft.deny" :items="[{ title: $t('admin:groupsEditRules.allowMatchingActions'), value: false },{ title: $t('admin:groupsEditRules.denyMatchingActions'), value: true }]" :label="$t('admin:groupsEditRules.ruleEffect')" variant="outlined" :disabled="disabled" /><v-select v-model="draft.roles" :items="actions" :label="$t('admin:groupsEditRules.pageActions')" variant="outlined" multiple chips closable-chips :disabled="disabled" /><div class="group-form-grid"><v-select v-model="draft.match" :items="matches" :label="$t('admin:groupsEditRules.matchType')" variant="outlined" :disabled="disabled" /><v-text-field v-model="draft.path" :label="draft.match === 'TAG' ? $t('admin:groupsEditRules.tagName') : draft.match === 'REGEX' ? $t('admin:groupsEditRules.regularExpression') : $t('admin:groupsEditRules.pagePath')" variant="outlined" :disabled="disabled" :hint="pathHint" persistent-hint maxlength="500" /></div><v-combobox v-model="draft.locales" :label="$t('admin:groupsEditRules.languageCodes')" variant="outlined" multiple chips closable-chips :hint="$t('admin:groupsEditRules.leaveEmptyAnyLanguage')" persistent-hint :disabled="disabled" /><v-alert v-if="issue" type="warning" variant="tonal">{{ issue }}</v-alert></div></v-card-text><v-card-actions><v-btn variant="text" :disabled="disabled" @click="dialog = false">{{ $t('common:actions.cancel') }}</v-btn><v-spacer /><v-btn color="primary" variant="flat" :disabled="disabled || Boolean(issue)" @click="apply">{{ $t('admin:groupsEditRules.useRule') }}</v-btn></v-card-actions></v-card></v-dialog>
  </section>
</template>
<script lang="ts">
import { type PropType } from 'vue'
import AsyncState from '@/components/common/async-state.vue'
import { groupPermissions, normalizeGroupRulePath, type GroupPolicyDraft, type GroupPageRule, type GroupRuleMatch } from '../../../shared/group-policy.ts'
const emptyRule = (): GroupPageRule => ({ id: '', match: 'START', path: '', deny: false, roles: ['read:pages'], locales: [] })
const matches = [{ title: 'admin:groupsEditRules.pathStarts', value: 'START' },{ title: 'admin:groupsEditRules.pathDescendants', value: 'SUBTREE' },{ title: 'admin:groupsEditRules.pathExactly', value: 'EXACT' },{ title: 'admin:groupsEditRules.pathEnds', value: 'END' },{ title: 'admin:groupsEditRules.tagMatches', value: 'TAG' },{ title: 'admin:groupsEditRules.regularExpression', value: 'REGEX' }]
export default {
  components: { AsyncState }, props: { modelValue: { type: Object as PropType<GroupPolicyDraft>, required: true }, disabled: Boolean, unrestricted: Boolean }, emits: ['update:modelValue','evaluate','draft-state'],
  data() { return { dialog: false, editingId: '', draft: emptyRule(), original: '', matches: matches.map(item => ({ ...item, title: this.$t(item.title) })), actions: groupPermissions.filter(p => p.pageScoped).map(p => ({ title: p.title, value: p.key })) } },
  computed: { pathHint() { return this.draft.match === 'START' ? this.$t('admin:groupsEditRules.noLeadingLeaveEmpty') : this.draft.match === 'SUBTREE' ? this.$t('admin:groupsEditRules.matchesPathDescendantsSlash') : this.draft.match === 'TAG' ? this.$t('admin:groupsEditRules.renamedTagsResolveThrough') : this.draft.match === 'REGEX' ? this.$t('admin:groupsEditRules.appliedPathWithoutLeading') : this.$t('admin:groupsEditRules.enterPathWithoutLeading') }, issue(): string { if (!this.draft.roles.length) return this.$t('admin:groupsEditRules.chooseLeastOnePage'); if (['TAG','REGEX'].includes(this.draft.match) && !this.draft.path.trim()) return this.$t('admin:groupsEditRules.enterMatchValue'); if (this.draft.match === 'REGEX') { try { new RegExp(this.draft.path) } catch { return this.$t('admin:groupsEditRules.regularExpressionNotValid') } } if (this.draft.locales.some(code => typeof code !== 'string' || !/^[a-zA-Z0-9_-]{1,24}$/.test(code))) return this.$t('admin:groupsEditRules.enterValidLanguageCodes'); return '' } },
  watch: { dialog(value: boolean) { this.$emit('draft-state', value && this.original !== JSON.stringify(this.draft)) }, draft: { deep: true, handler() { this.$emit('draft-state', this.dialog && this.original !== JSON.stringify(this.draft)) } } },
  methods: { matchTitle(match: GroupRuleMatch) { const title = matches.find(item => item.value === match)?.title; return title ? this.$t(title) : match }, permissionTitle(key: string) { return groupPermissions.find(p => p.key === key)?.title ?? key }, missingPermissions(rule: GroupPageRule) { return rule.roles.filter(role => !this.modelValue.permissions.includes(role)) }, open(rule?: GroupPageRule) { if (this.disabled) return; this.editingId = rule?.id ?? ''; this.draft = rule ? JSON.parse(JSON.stringify(rule)) as GroupPageRule : { ...emptyRule(), id: crypto.randomUUID() }; this.original = JSON.stringify(this.draft); this.dialog = true }, apply() { if (this.disabled || this.issue) return; const rule: GroupPageRule = { ...this.draft, path: normalizeGroupRulePath(this.draft.match, this.draft.path.trim()), roles: [...new Set(this.draft.roles)], locales: [...new Set(this.draft.locales)] }; const pageRules = this.editingId ? this.modelValue.pageRules.map(item => item.id === this.editingId ? rule : item) : [...this.modelValue.pageRules, rule]; this.$emit('update:modelValue', { ...this.modelValue, pageRules }); this.dialog = false }, remove(id: string) { if (!this.disabled) this.$emit('update:modelValue', { ...this.modelValue, pageRules: this.modelValue.pageRules.filter(rule => rule.id !== id) }) }, onClose() { this.$emit('draft-state', false) } }
}
</script>
