<template lang="pug">
v-container.admin-theme(fluid)
  v-row
    v-col(cols='12')
      .admin-header
        img.animated.fadeInUp(src='/_assets/svg/icon-paint-palette.svg', alt='', width='80', height='80')
        .admin-header-title
          .text-headline-medium.text-primary.animated.fadeInLeft {{ $t('admin:theme.title') }}
          .text-body-large.text-medium-emphasis.animated.fadeInLeft.wait-p2s {{ $t('admin:theme.subtitle') }}
        v-spacer
        v-btn.animated.fadeInRight(
          color='success'
          variant='flat'
          size='large'
          :loading='loading'
          :disabled='!configValid'
          @click='save'
        )
          v-icon(start) mdi-check
          span {{ $t('common:actions.apply') }}

  v-form.pt-3(@submit.prevent='save')
    v-row
      v-col(cols='12', lg='4')
        v-card.animated.fadeInUp
          v-toolbar(color='primary', density='compact')
            v-icon.ml-4 mdi-theme-light-dark
            v-toolbar-title.text-body-large Appearance
          v-card-text
            v-select(
              v-model='config.theme'
              :items='themes'
              item-title='text'
              item-value='value'
              variant='outlined'
              prepend-inner-icon='mdi-palette-outline'
              :label='$t(`admin:theme.siteTheme`)'
              persistent-hint
              :hint='$t(`admin:theme.siteThemeScopeHint`, { defaultValue: `Themes define the structure and presentation of public, editor, profile, and administration surfaces.` })'
            )
            v-select.mt-3(
              v-model='config.iconset'
              :items='iconsets'
              item-title='text'
              item-value='value'
              variant='outlined'
              prepend-inner-icon='mdi-shape-outline'
              :label='$t(`admin:theme.iconset`)'
              persistent-hint
              :hint='$t(`admin:theme.iconsetHint`)'
            )
            v-divider.my-4
            v-switch.mt-0(
              v-model='config.darkMode'
              inset
              color='primary'
              :label='$t(`admin:theme.darkMode`)'
              persistent-hint
              :hint='$t(`admin:theme.defaultAppearanceHint`, { defaultValue: `Default appearance for visitors who have not chosen a personal preference.` })'
            )
            v-select.mt-3(
              v-model='config.tocPosition'
              :items='tocPositions'
              item-title='text'
              item-value='value'
              variant='outlined'
              prepend-inner-icon='mdi-table-of-contents'
              label='Table of contents position'
              persistent-hint
              hint='Shown on wide screens; compact screens use the page navigation menu.'
            )

      v-col(cols='12', lg='8')
        v-card.animated.fadeInUp.wait-p1s
          v-toolbar(color='primary', density='compact')
            v-icon.ml-4 mdi-format-color-fill
            v-toolbar-title.text-body-large Color palette
            v-btn-toggle.mr-2(
              v-model='previewMode'
              mandatory
              density='compact'
              variant='outlined'
              divided
              aria-label='Palette mode'
            )
              v-btn(value='light', aria-label='Edit light palette')
                v-icon(start) mdi-white-balance-sunny
                span.d-none.d-sm-inline Light
              v-btn(value='dark', aria-label='Edit dark palette')
                v-icon(start) mdi-weather-night
                span.d-none.d-sm-inline Dark
          v-card-text
            .d-flex.flex-wrap.align-center.ga-2.mb-4
              .text-body-medium.text-medium-emphasis.flex-grow-1
                | Customize every semantic color independently for {{ previewMode }} mode. Foreground contrast is generated by Vuetify.
              v-btn(
                size='small'
                variant='text'
                prepend-icon='mdi-restore'
                @click='resetActivePalette'
              ) Reset {{ previewMode }} colors
            .theme-palette-grid
              theme-color-field(
                v-for='field in paletteFields'
                :key='`${previewMode}-${field.key}`'
                v-model='config.colors[previewMode][field.key]'
                :label='field.label'
              )

            v-divider.my-5
            .text-label-large.mb-2 Live preview
            v-theme-provider(:theme='previewMode', with-background)
              .theme-preview
                .theme-preview__heading
                  div
                    .text-title-medium Knowledge that feels at home
                    .text-body-small.text-medium-emphasis Palette preview · {{ previewMode }} mode
                  v-chip(color='secondary', variant='tonal', size='small') Updated
                .text-body-medium.mt-3
                  | Primary actions, status colors, surfaces, and readable foregrounds update as you edit.
                .d-flex.flex-wrap.ga-2.mt-4
                  v-btn(color='primary', variant='flat') Primary action
                  v-btn(color='secondary', variant='tonal') Secondary
                  v-btn(color='accent', variant='outlined') Accent
                .theme-preview__statuses.mt-4
                  v-chip(color='info', variant='tonal', size='small') Info
                  v-chip(color='success', variant='tonal', size='small') Success
                  v-chip(color='warning', variant='tonal', size='small') Warning
                  v-chip(color='error', variant='tonal', size='small') Error

      v-col(cols='12')
        v-card.animated.fadeInUp.wait-p2s
          v-toolbar(color='primary', density='compact')
            v-icon.ml-4 mdi-pillar
            v-toolbar-title.text-body-large Reading gutters
            v-chip.mr-3(size='small', color='secondary', variant='tonal') Wide screens
          v-card-text
            .gutter-section-heading
              div
                .text-title-medium Marginalia for the reading surface
                .text-body-medium.text-medium-emphasis.mt-1
                  | Choose a restrained ornament for the open space beside article text. Decorations recede automatically when the reading gutter narrows.
              v-chip(size='small', variant='outlined', color='primary') Article pages only
            .gutter-style-grid.mt-5(role='radiogroup', aria-label='Reading gutter ornament')
              button.gutter-style-option(
                v-for='option in gutterStyles'
                :key='option.value'
                type='button'
                role='radio'
                :aria-checked='config.gutterStyle === option.value'
                :class='{ "is-selected": config.gutterStyle === option.value }'
                @click='config.gutterStyle = option.value'
              )
                .gutter-style-option__canvas
                  .wiki-gutter-art.gutter-style-option__art.gutter-style-option__art--start(
                    :class='`wiki-gutter-art--${option.value}`'
                    :style='gutterPreviewStyle(option.value)'
                    aria-hidden='true'
                  )
                    page-gutter-column(v-if='option.value === `columns`')
                  .gutter-style-option__paper
                    span
                    span
                    span
                    span
                  .wiki-gutter-art.gutter-style-option__art.gutter-style-option__art--end(
                    :class='`wiki-gutter-art--${option.value}`'
                    :style='gutterPreviewStyle(option.value)'
                    aria-hidden='true'
                  )
                    page-gutter-column(v-if='option.value === `columns`')
                .gutter-style-option__label
                  span.text-label-large {{ option.title }}
                  v-icon(v-if='config.gutterStyle === option.value', color='primary', size='18') mdi-check-circle
                .text-body-small.text-medium-emphasis {{ option.description }}
            v-expand-transition
              .gutter-custom-editor.mt-5(v-if='config.gutterStyle === `custom`')
                v-textarea.is-monospaced(
                  v-model='config.gutterCustomCss'
                  label='Custom gutter CSS declarations'
                  variant='outlined'
                  color='primary'
                  persistent-hint
                  hint='Applied only to each gutter ornament. Enter declarations without a selector, braces, or @-rules.'
                  placeholder='background: radial-gradient(circle, rgba(99, 102, 241, .16), transparent 68%); opacity: .7;'
                  :maxlength='PAGE_GUTTER_CUSTOM_CSS_MAX_LENGTH'
                  :counter='PAGE_GUTTER_CUSTOM_CSS_MAX_LENGTH'
                  :rules='gutterCustomCssRules'
                  auto-grow
                  rows='3'
                )
                .d-flex.flex-wrap.ga-2.mt-2
                  v-chip(size='small', variant='tonal') background
                  v-chip(size='small', variant='tonal') border
                  v-chip(size='small', variant='tonal') opacity
                  v-chip(size='small', variant='tonal') filter

      v-col(cols='12')
        v-card.animated.fadeInUp.wait-p2s
          v-toolbar(color='primary', density='compact')
            v-icon.ml-4 mdi-code-tags
            v-toolbar-title.text-body-large {{ $t('admin:theme.codeInjection') }}
          v-card-text
            v-row
              v-col(cols='12', lg='6')
                v-textarea.is-monospaced(
                  v-model='config.injectCSS'
                  :label='$t(`admin:theme.cssOverride`)'
                  variant='outlined'
                  color='primary'
                  persistent-hint
                  :hint='$t(`admin:theme.cssOverrideHint`)'
                  auto-grow
                )
                i18next.text-body-small.pl-2.ml-1(path='admin:theme.cssOverrideWarning', tag='div')
                  strong.text-error(place='caution') {{ $t('admin:theme.cssOverrideWarningCaution') }}
                  code(place='cssClass') .contents
              v-col(cols='12', lg='6')
                v-textarea.is-monospaced(
                  v-model='config.injectHead'
                  :label='$t(`admin:theme.headHtmlInjection`)'
                  variant='outlined'
                  color='primary'
                  persistent-hint
                  :hint='$t(`admin:theme.headHtmlInjectionHint`)'
                  auto-grow
                )
                v-textarea.is-monospaced.mt-2(
                  v-model='config.injectBody'
                  :label='$t(`admin:theme.bodyHtmlInjection`)'
                  variant='outlined'
                  color='primary'
                  persistent-hint
                  :hint='$t(`admin:theme.bodyHtmlInjectionHint`)'
                  auto-grow
                )
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { useTheme } from 'vuetify'
import { wikiStore } from '@/store/index.ts'
import ThemeColorField from './theme-color-field.vue'
import PageGutterColumn from '../common/page-gutter-column.vue'
import { fetchThemeConfig, saveThemeConfig, type ThemeConfig } from '../../helpers/theming-api.ts'
import { applyWikiThemeColors, resolveThemeName } from '../../helpers/theme.ts'
import { loadingStart, loadingStop, pushGraphError, showNotification } from '../../helpers/root-ui-store.ts'

import {
  PAGE_GUTTER_CUSTOM_CSS_MAX_LENGTH,
  PageGutterCustomCssSchema,
  type PageGutterStyle
} from '../../../shared/page-gutters.ts'
import { cloneThemeColors, DEFAULT_THEME_COLORS, isThemeColors, normalizeThemeColors, type ThemeColorKey } from '../../../shared/theme-colors.ts'
type PaletteMode = 'light' | 'dark'


const createConfig = (): ThemeConfig => ({
  theme: 'default',
  iconset: 'mdi',
  darkMode: siteConfig.darkMode,
  colors: normalizeThemeColors(siteConfig.themeColors),
  tocPosition: siteConfig.tocPosition,
  gutterStyle: siteConfig.gutterStyle,
  gutterCustomCss: siteConfig.gutterCustomCss,
  injectCSS: '',
  injectHead: '',
  injectBody: ''
})

const theme = useTheme()
const config = reactive<ThemeConfig>(createConfig())
const persistedConfig = ref<ThemeConfig>(createConfig())
const loading = ref(false)
const previewMode = ref<PaletteMode>(config.darkMode ? 'dark' : 'light')
const configValid = computed(() => isThemeColors(config.colors) && PageGutterCustomCssSchema.safeParse(config.gutterCustomCss).success)
const themes = [{ text: 'Default', author: 'tsFranki', value: 'default' }]
const iconsets = [
  { text: 'Material Design Icons (default)', value: 'mdi' },
  { text: 'Font Awesome 5', value: 'fa' },
  { text: 'Font Awesome 4', value: 'fa4' }
]
const tocPositions = [
  { text: 'Left (default)', value: 'left' },
  { text: 'Right', value: 'right' },
  { text: 'Hidden', value: 'off' }
]
const gutterStyles: Array<{ value: PageGutterStyle; title: string; description: string }> = [
  { value: 'columns', title: 'Attic columns', description: 'Fine fluting and measured capitals; the classical default.' },
  { value: 'orbits', title: 'Celestial orbits', description: 'Quiet circles and axes echo the geometry of the page title.' },
  { value: 'laurel', title: 'Laurel cadence', description: 'A spare botanical rhythm drawn along a central stem.' },
  { value: 'aurora', title: 'Aurora wash', description: 'Soft color fields for a warmer, contemporary margin.' },
  { value: 'none', title: 'Unadorned', description: 'Preserve the open reading space without ornament.' },
  { value: 'custom', title: 'Custom study', description: 'Apply your own declaration block to both gutter regions.' }
]
const gutterCustomCssRules = [
  (value: string): true | string => value.length <= PAGE_GUTTER_CUSTOM_CSS_MAX_LENGTH || `Use no more than ${PAGE_GUTTER_CUSTOM_CSS_MAX_LENGTH} characters.`,
  (value: string): true | string => !/[{}@]/.test(value) || 'Enter declarations only; selectors, braces, and @-rules are not allowed.'
]
const gutterPreviewStyle = (style: PageGutterStyle): string | undefined => style === 'custom' ? config.gutterCustomCss : undefined
const paletteFields: Array<{ key: ThemeColorKey; label: string }> = [
  { key: 'background', label: 'Page background' },
  { key: 'surface', label: 'Cards and surfaces' },
  { key: 'primary', label: 'Primary' },
  { key: 'secondary', label: 'Secondary' },
  { key: 'accent', label: 'Accent' },
  { key: 'info', label: 'Information' },
  { key: 'success', label: 'Success' },
  { key: 'warning', label: 'Warning' },
  { key: 'error', label: 'Error' }
]

const copyConfig = (source: ThemeConfig): ThemeConfig => ({
  ...source,
  colors: cloneThemeColors(source.colors)
})

const assignConfig = (source: ThemeConfig): void => {
  Object.assign(config, copyConfig(source))
}

watch(() => config.darkMode, value => {
  previewMode.value = value ? 'dark' : 'light'
  void theme.change(value ? 'dark' : 'light', false)
})

watch(() => config.colors, colors => {
  if (isThemeColors(colors)) applyWikiThemeColors(theme, colors)
}, { deep: true })

const loadConfig = async (): Promise<void> => {
  loadingStart(wikiStore, 'admin-theme-refresh')
  try {
    const loaded = await fetchThemeConfig(window.fetch.bind(window), 'Theme config response is invalid')
    persistedConfig.value = copyConfig(loaded)
    assignConfig(loaded)
  } catch (error) {
    pushGraphError(wikiStore, error)
  } finally {
    loadingStop(wikiStore, 'admin-theme-refresh')
  }
}

const resetActivePalette = (): void => {
  Object.assign(config.colors[previewMode.value], DEFAULT_THEME_COLORS[previewMode.value])
}

const save = async (): Promise<void> => {
  if (loading.value || !configValid.value) return
  loading.value = true
  loadingStart(wikiStore, 'admin-theme-save')
  try {
    const payload = copyConfig(config)
    await saveThemeConfig(window.fetch.bind(window), payload, 'Theme config update failed')
    persistedConfig.value = payload
    siteConfig.darkMode = payload.darkMode
    siteConfig.themeColors = cloneThemeColors(payload.colors)
    siteConfig.gutterStyle = payload.gutterStyle
    siteConfig.gutterCustomCss = payload.gutterCustomCss
    wikiStore.site.dark = payload.darkMode
    showNotification(wikiStore, {
      message: 'Theme settings updated successfully.',
      style: 'success',
      icon: 'check'
    })
  } catch (error) {
    pushGraphError(wikiStore, error)
  } finally {
    loadingStop(wikiStore, 'admin-theme-save')
    loading.value = false
  }
}

onMounted(() => { void loadConfig() })

onBeforeUnmount(() => {
  applyWikiThemeColors(theme, persistedConfig.value.colors)
  void theme.change(resolveThemeName(wikiStore.user.appearance, persistedConfig.value.darkMode), false)
})
</script>

<style lang="scss" scoped>
.admin-theme {
  max-width: 1680px;
}

.theme-palette-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 16px;
}

.theme-preview {
  padding: 20px;
  border: 1px solid rgba(var(--v-border-color), var(--v-border-opacity));
  border-radius: 12px;
  background: rgb(var(--v-theme-surface));
  color: rgb(var(--v-theme-on-surface));

  &__heading {
    display: flex;
    gap: 16px;
    justify-content: space-between;
    align-items: flex-start;
  }

  &__statuses {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }
}

.gutter-section-heading {
  display: flex;
  gap: 24px;
  align-items: flex-start;
  justify-content: space-between;
}

.gutter-style-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 14px;
}

.gutter-style-option {
  display: flex;
  min-width: 0;
  flex-direction: column;
  padding: 10px 10px 14px;
  border: 1px solid rgba(var(--v-border-color), .14);
  border-radius: 16px;
  background: color-mix(in srgb, rgb(var(--v-theme-surface)) 96%, rgb(var(--v-theme-background)));
  color: rgb(var(--v-theme-on-surface));
  cursor: pointer;
  font: inherit;
  text-align: start;
  transition: border-color .16s ease, box-shadow .16s ease, transform .16s ease;

  &:hover {
    border-color: color-mix(in srgb, rgb(var(--v-theme-primary)) 42%, transparent);
    box-shadow: 0 12px 28px rgba(15, 23, 42, .08);
    transform: translateY(-2px);
  }

  &:focus-visible {
    outline: 3px solid rgba(var(--v-theme-primary), .2);
    outline-offset: 3px;
  }

  &.is-selected {
    border-color: rgb(var(--v-theme-primary));
    box-shadow:
      0 0 0 1px rgb(var(--v-theme-primary)),
      0 14px 30px rgba(15, 23, 42, .09);
  }

  &__canvas {
    position: relative;
    overflow: hidden;
    height: 116px;
    border: 1px solid rgba(var(--v-border-color), .09);
    border-radius: 11px;
    background:
      radial-gradient(circle at 82% 12%, rgba(var(--v-theme-primary), .09), transparent 45%),
      rgb(var(--v-theme-background));
  }

  &__art {
    position: absolute;
    inset-block: 8px;
    width: 23%;

    &--start {
      inset-inline-start: 2%;
    }

    &--end {
      inset-inline-end: 2%;
      transform: scaleX(-1);
    }
  }

  &__paper {
    position: absolute;
    inset: 10px 27%;
    display: flex;
    flex-direction: column;
    gap: 8px;
    padding: 16px 12px;
    border: 1px solid rgba(var(--v-border-color), .1);
    border-radius: 8px;
    background: rgb(var(--v-theme-surface));
    box-shadow: 0 5px 16px rgba(15, 23, 42, .05);

    span {
      width: 100%;
      height: 3px;
      border-radius: 999px;
      background: rgba(var(--v-theme-on-surface), .13);

      &:nth-child(2) {
        width: 82%;
      }

      &:nth-child(3) {
        width: 92%;
      }

      &:nth-child(4) {
        width: 64%;
      }
    }
  }

  &__label {
    display: flex;
    gap: 8px;
    align-items: center;
    justify-content: space-between;
    margin: 12px 3px 3px;
  }

  > .text-body-small {
    min-height: 2.5rem;
    margin-inline: 3px;
    line-height: 1.35;
  }
}

.gutter-custom-editor {
  padding: 18px 18px 14px;
  border: 1px solid color-mix(in srgb, rgb(var(--v-theme-primary)) 24%, transparent);
  border-radius: 14px;
  background: color-mix(in srgb, rgb(var(--v-theme-primary)) 4%, rgb(var(--v-theme-surface)));
}

.v-textarea.is-monospaced :deep(textarea) {
  font-family: 'Roboto Mono', 'Courier New', Courier, monospace;
  font-size: 13px;
  font-weight: 600;
  line-height: 1.4;
}

@include until($desktop) {
  .theme-palette-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .gutter-style-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@include until($tablet) {
  .theme-palette-grid {
    grid-template-columns: 1fr;
  }

  .gutter-section-heading {
    flex-direction: column;
    gap: 12px;
  }

  .gutter-style-grid {
    grid-template-columns: 1fr;
  }

  .admin-header {
    > .v-spacer {
      display: none;
    }

    > .v-btn {
      flex: 1 0 100%;
      margin-top: 4px;
    }
  }

  .theme-preview {
    padding: 16px;

    &__heading {
      align-items: flex-start;
      flex-direction: column;
    }
  }
}
</style>
