<template>
  <v-container fluid class="account-directory">
    <admin-hero :title="$t('admin:users.title')" :description="$t('admin:users.directoryDescription', { defaultValue: 'Accounts, memberships and sign-in status.' })" :eyebrow="$t('admin:users.peopleAccess')" icon="mdi-account-outline">
      <template #actions><v-btn variant="text" prepend-icon="mdi-refresh" :loading="loading" :disabled="creating" @click="load">{{ $t('admin:shell.reload') }}<v-tooltip activator="parent" location="bottom">{{ $t('admin:users.reloadMemberDirectory') }}</v-tooltip></v-btn><v-btn v-if="directory?.canCreate" color="primary" variant="flat" prepend-icon="mdi-account-plus-outline" @click="creating = true">{{ $t('admin:users.createAccount') }}</v-btn></template>
    </admin-hero>

    <nav class="account-directory-stats" :aria-label="$t('admin:users.accountStatusFilters')"><button :aria-pressed="state === 'all' && verified === 'all'" @click="setStatus('all')"><span>{{ $t('admin:users.allAccounts') }}</span><strong>{{ directory?.counts.accounts ?? '—' }}</strong></button><button :aria-pressed="state === 'active' && verified === 'all'" @click="setStatus('active')"><span>{{ $t('admin:users.active') }}</span><strong>{{ directory?.counts.active ?? '—' }}</strong></button><button :aria-pressed="state === 'inactive' && verified === 'all'" @click="setStatus('inactive')"><span>{{ $t('admin:users.inactive') }}</span><strong>{{ directory?.counts.inactive ?? '—' }}</strong></button><button :aria-pressed="verified === 'unverified'" @click="setStatus('unverified')"><span>{{ $t('admin:users.emailUnverified') }}</span><strong>{{ directory?.counts.unverified ?? '—' }}</strong></button></nav>
    <p class="account-directory-guide">{{ $t('admin:users.groupMembershipsConnectPeople') }} <router-link to="/groups">{{ $t('admin:users.manageGroups') }} <v-icon icon="mdi-arrow-right" size="16" /></router-link></p>
    <section class="account-directory-register" aria-labelledby="account-register-heading" :aria-busy="loading">
      <div class="account-register-heading"><div><span class="account-kicker">{{ $t('admin:users.accountRegister') }}</span><h2 id="account-register-heading">{{ $t('admin:users.findPeople') }}</h2></div><span aria-live="polite">{{ directory ? $t('admin:users.accountsCount', { count: directory.total }) : '' }}</span></div>
      <form class="account-directory-filters" @submit.prevent="searchNow"><v-text-field v-model="search" :label="$t('admin:users.searchNameEmail')" prepend-inner-icon="mdi-magnify" variant="outlined" density="comfortable" hide-details clearable /><v-select v-model="provider" :items="providerOptions" :label="$t('admin:users.signProvider')" variant="outlined" density="comfortable" hide-details /><v-select v-model="group" :items="groupOptions" :label="$t('admin:users.groupMembership')" variant="outlined" density="comfortable" hide-details /><v-btn v-if="filtered" variant="text" @click="clearFilters">{{ $t('admin:users.clearFilters') }}</v-btn></form>
      <async-state v-if="loading" state="loading" :title="$t('admin:users.loadingAccounts')" :message="$t('admin:users.readingCurrentMembershipsAccount')" />
      <async-state v-else-if="error" state="error" :title="$t('admin:users.accountDirectoryUnavailable')" :message="error" :retry-label="$t('admin:users.tryAgain')" @retry="load" />
      <async-state v-else-if="!directory?.items.length" state="empty" :title="filtered ? $t('admin:users.noMatchingAccounts') : $t('admin:users.noAccountsShow')" :message="filtered ? $t('admin:users.tryAnotherNameProvider') : $t('admin:users.createAccountWelcomeSomeone')" />
      <template v-else>
        <div class="account-register-columns" aria-hidden="true"><span>{{ $t('admin:users.personMembership') }}</span><span>{{ $t('admin:users.signProvider') }}</span><span>{{ $t('admin:users.accountState') }}</span></div>
        <ul class="account-register-list"><li v-for="person in directory.items" :key="person.id"><div class="account-person"><span class="account-initials" aria-hidden="true">{{ initials(person.name) }}</span><div><router-link class="account-person-name" :to="accountLink(person.id)">{{ person.name }} <v-icon v-if="person.id <= 2 || person.isSystem" icon="mdi-lock-outline" size="15" :aria-label="person.id === 2 ? $t('admin:users.guestIdentity') : $t('admin:users.protectedAccount')" /></router-link><p class="account-email">{{ person.email }}</p><div class="account-memberships"><span v-for="membership in person.groups" :key="membership.id">{{ membership.name }}</span><em v-if="!person.groups.length">{{ $t('admin:users.noGroupMembership') }}</em></div></div></div><div class="account-provider"><strong>{{ person.providerTitle }}</strong><span>{{ person.lastLoginAt ? $t('admin:users.signRenewal', { lastLoginAt: relativeDate(person.lastLoginAt), interpolation: { escapeValue: false } }) : $t('admin:users.noSignRecorded') }}</span></div><div class="account-row-state"><span class="account-state" :class="{ 'account-state-paused': !person.isActive }"><i aria-hidden="true" />{{ person.isActive ? $t('admin:users.active') : $t('admin:users.inactive') }}</span><span v-if="!person.isVerified" class="account-unverified">{{ $t('admin:users.emailUnverified') }}</span><span v-else-if="person.twoFactor === 'enrollment-required'" class="account-unverified">{{ $t('admin:users.authenticatorRequired') }}</span><router-link :to="accountLink(person.id)" :aria-label="$t('admin:users.manage', { name: person.name, interpolation: { escapeValue: false } })">{{ $t('admin:users.manage2') }} <v-icon icon="mdi-arrow-right" size="16" /></router-link></div></li></ul>
        <footer class="account-register-footer"><span>{{ $t('admin:users.includesSystemIdentities', { value: offset + 1, total: Math.min(offset + directory.limit, directory.total), total2: directory.total, interpolation: { escapeValue: false } }) }}</span><div><v-btn variant="text" :disabled="offset === 0" prepend-icon="mdi-chevron-left" @click="page(-1)">{{ $t('admin:users.previous') }}</v-btn><v-btn variant="text" :disabled="offset + directory.limit >= directory.total" append-icon="mdi-chevron-right" @click="page(1)">{{ $t('admin:users.next') }}</v-btn></div></footer>
      </template>
    </section>
    <account-create ref="createDialog" v-model="creating" @created="created" />
  </v-container>
</template>
<script lang="ts">
import AsyncState from '@/components/common/async-state.vue'
import AccountCreate from './admin-users-create.vue'
import { fetchAccountDirectory } from '../../helpers/account-api.ts'
import { getErrorMessage } from '../../helpers/root-ui-store.ts'
import type { AccountDirectory } from '../../../shared/account-policy.ts'
const directoryFilters = (query: Record<string, unknown>) => ({ search: typeof query.search === 'string' ? query.search.slice(0,200) : '', state: ['active','inactive'].includes(String(query.state)) ? String(query.state) : 'all', verified: query.verified === 'unverified' ? 'unverified' : 'all', provider: typeof query.provider === 'string' ? query.provider : 'all', group: typeof query.group === 'string' ? query.group : 'all', offset: Number.isSafeInteger(Number(query.offset)) && Number(query.offset) >= 0 && Number(query.offset) <= 1000000 ? Number(query.offset) : 0 })
export default {
  components: { AsyncState, AccountCreate },
  data() { return { directory: null as AccountDirectory | null, loading: false, error: '', ...directoryFilters(this.$route.query), restoring: false, creating: false, sequence: 0, disposed: false, timer: null as ReturnType<typeof setTimeout> | null } },
  computed: {
    filtered(): boolean { return Boolean(this.search || this.state !== 'all' || this.verified !== 'all' || this.provider !== 'all' || this.group !== 'all') },
    providerOptions() { return [{ title: this.$t('admin:users.allProviders'), value: 'all' }, ...(this.directory?.providers ?? []).map(row => ({ title: row.title, value: row.key }))] },
    groupOptions() { return [{ title: this.$t('admin:users.allGroups'), value: 'all' }, ...(this.directory?.groups ?? []).map(row => ({ title: row.name, value: String(row.id) }))] }
  },
  watch: {
    search() { if (!this.restoring) this.queueSearch() }, provider() { if (!this.restoring) this.queueSearch() }, group() { if (!this.restoring) this.queueSearch() },
    '$route.query'(query: Record<string, unknown>) { const next = directoryFilters(query); if (Object.entries(next).every(([key,value]) => Reflect.get(this,key) === value)) return; this.restoring = true; Object.assign(this,next); this.$nextTick(() => { this.restoring = false; void this.load(false) }) }
  },
  methods: {
    async load(syncQuery = true) { if (syncQuery) this.syncQuery(); const sequence = ++this.sequence; this.loading = true; this.error = ''; try { const directory = await fetchAccountDirectory(new URLSearchParams({ search: this.search || '', state: this.state, verified: this.verified, provider: this.provider, group: this.group, offset: String(this.offset), limit: '25' })); if (this.disposed || sequence !== this.sequence) return; this.directory = directory; if (this.offset && this.offset >= directory.total) { this.offset = 0; void this.load() } } catch (error) { if (!this.disposed && sequence === this.sequence) this.error = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.sequence) this.loading = false } },
    syncQuery() { const query = { ...this.$route.query }; for (const key of ['search','state','verified','provider','group','offset']) delete query[key]; if (this.search) query.search = this.search; if (this.state !== 'all') query.state = this.state; if (this.verified !== 'all') query.verified = this.verified; if (this.provider !== 'all') query.provider = this.provider; if (this.group !== 'all') query.group = this.group; if (this.offset) query.offset = String(this.offset); void this.$router.replace({ query }) },
    accountLink(id: number) { return { path: `/users/${id}`, query: { from: this.$route.fullPath } } },
    queueSearch() { if (this.timer) clearTimeout(this.timer); this.timer = setTimeout(() => this.searchNow(), 250) },
    searchNow() { if (this.timer) clearTimeout(this.timer); this.offset = 0; void this.load() },
    setStatus(status: string) { this.state = ['active', 'inactive'].includes(status) ? status : 'all'; this.verified = status === 'unverified' ? 'unverified' : 'all'; this.searchNow() },
    clearFilters() { this.search = ''; this.state = 'all'; this.verified = 'all'; this.provider = 'all'; this.group = 'all'; this.searchNow() },
    page(direction: number) { this.offset = Math.max(0, this.offset + direction * 25); void this.load() },
    initials(name: string) { return name.trim().split(/\s+/).slice(0, 2).map(part => part[0]).join('').toUpperCase() },
    relativeDate(value: string) { const days = Math.floor((Date.now() - Date.parse(value)) / 86400000); return days <= 0 ? this.$t('admin:users.today') : days === 1 ? this.$t('admin:users.yesterday') : this.$t('admin:users.daysAgo', { count: days }) },
    created(id: number) { this.creating = false; void this.$router.push(this.accountLink(id)) }
  },
  mounted() { void this.load() },
  beforeRouteLeave() { return (this.$refs.createDialog as { canLeave: () => Promise<boolean> } | undefined)?.canLeave() ?? true },
  beforeUnmount() { this.disposed = true; this.sequence++; if (this.timer) clearTimeout(this.timer) }
}
</script>
<style lang="scss">
.account-directory { --account-line: var(--wiki-surface-border); min-width: 0; }
.account-kicker { display: block; font-size: .75rem; font-weight: 600; color: var(--wiki-text-muted); }
.account-directory-stats { display: flex; flex-wrap: wrap; gap: 8px; margin: 16px 0 12px; button { display: flex; align-items: center; justify-content: space-between; gap: 12px; min-height: 44px; padding: 8px 12px; border: 1px solid var(--account-line); border-radius: var(--wiki-control-radius); background: var(--wiki-surface-raised); color: rgb(var(--v-theme-on-surface)); cursor: pointer; &[aria-pressed=true] { border-color: var(--wiki-primary-ink); background: var(--wiki-surface-sunken); } span { font-size: .8125rem; } strong { font-size: .875rem; font-weight: 650; font-variant-numeric: tabular-nums; } &:focus-visible { outline: 2px solid var(--wiki-primary-ink); outline-offset: 2px; } } }
.account-directory-guide { font-size: .8125rem; line-height: 1.6; color: var(--wiki-text-muted); margin: 0 0 16px; a { color: var(--wiki-primary-ink); text-underline-offset: 4px; margin-inline-start: 8px; } }
.account-directory-register { border: 1px solid var(--account-line); border-radius: var(--wiki-panel-radius); background: var(--wiki-surface-raised); overflow: hidden; min-width: 0; }
.account-register-heading { display: flex; flex-wrap: wrap; justify-content: space-between; align-items: center; gap: 12px; padding: 16px; h2 { font-size: 1.125rem; margin-top: 4px; font-weight: 650; } >span { font-size: .8125rem; color: var(--wiki-text-muted); } }
.account-directory-filters { display: grid; grid-template-columns: minmax(0,1.5fr) minmax(0,1fr) minmax(0,1fr) auto; gap: 12px; padding: 0 16px 16px; align-items: center; >* { min-width: 0; } }
.account-register-columns { display: grid; grid-template-columns: minmax(0,1.6fr) minmax(0,.8fr) minmax(0,.55fr); gap: 16px; padding: 10px 16px; border-block: 1px solid var(--account-line); background: var(--wiki-surface-sunken); font-size: .75rem; font-weight: 600; color: var(--wiki-text-muted); }
.account-register-list { list-style: none; padding: 0; margin: 0; >li { display: grid; grid-template-columns: minmax(0,1.6fr) minmax(0,.8fr) minmax(0,.55fr); gap: 16px; align-items: center; padding: 14px 16px; border-bottom: 1px solid var(--account-line); &:last-child { border-bottom: 0; } } }
.account-person { display: flex; align-items: flex-start; gap: 12px; min-width: 0; >div { min-width: 0; } }
.account-initials { display: grid; place-items: center; flex-shrink: 0; width: 36px; height: 36px; border-radius: var(--wiki-control-radius); background: var(--wiki-surface-sunken); border: 1px solid var(--account-line); font-size: .75rem; }
.account-person-name { font-size: .9375rem; font-weight: 650; color: var(--wiki-primary-ink); text-decoration: none; overflow-wrap: anywhere; &:hover, &:focus-visible { text-decoration: underline; text-underline-offset: 4px; } }
.account-email { margin: 4px 0 8px; font-size: .8125rem; color: var(--wiki-text-muted); overflow-wrap: anywhere; }
.account-memberships { display: flex; flex-wrap: wrap; gap: 5px; span { border: 1px solid var(--account-line); border-radius: 4px; padding: 2px 6px; font-size: .75rem; overflow-wrap: anywhere; } em { font-size: .75rem; color: var(--wiki-text-muted); } }
.account-provider { display: flex; flex-direction: column; gap: 5px; min-width: 0; overflow-wrap: anywhere; strong { font-size: .8125rem; font-weight: 600; } span { font-size: .75rem; color: var(--wiki-text-muted); } }
.account-row-state { display: flex; flex-direction: column; gap: 6px; align-items: flex-start; min-width: 0; a { display: inline-flex; align-items: center; gap: 4px; color: var(--wiki-primary-ink); font-size: .8125rem; text-underline-offset: 3px; } }
.account-state { display: inline-flex; align-items: center; gap: 6px; font-size: .8125rem; i { width: 6px; height: 6px; background: var(--wiki-purpose-success-ink); border-radius: 50%; } &.account-state-paused i { background: var(--wiki-text-muted); } }
.account-unverified { font-size: .75rem; }
.account-register-footer { border-top: 1px solid var(--account-line); padding: 12px 16px; display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 10px; >span { font-size: .75rem; color: var(--wiki-text-muted); } >div { display: flex; flex-wrap: wrap; gap: 8px; } }
@media(max-width:1000px) { .account-directory-filters { grid-template-columns: minmax(0,1fr) minmax(0,1fr); >:first-child { grid-column: 1/-1; } } .account-register-columns { display: none; } .account-register-list>li { grid-template-columns: minmax(0,1fr) auto; } .account-provider { grid-column: 1; padding-inline-start: 48px; } .account-row-state { grid-column: 2; grid-row: 1/3; } }
@media(max-width:600px) { .account-directory-stats { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); button { padding: 8px; gap: 6px; } } .account-directory-filters { grid-template-columns: minmax(0,1fr); >:first-child { grid-column: auto; } } .account-register-list>li { grid-template-columns: minmax(0,1fr); gap: 8px; } .account-row-state { grid-column: 1; grid-row: auto; flex-direction: row; align-items: center; padding-inline-start: 48px; flex-wrap: wrap; } .account-directory .v-btn { min-height: 44px; height: auto; .v-btn__content { white-space: normal; } } .account-person-name,.account-row-state a,.account-directory-guide a { display: inline-flex; align-items: center; min-height: 44px; } }
</style>
