<template>
  <section aria-labelledby="group-members-heading"><div class="group-heading"><div><span class="group-kicker">{{ $t('admin:groupsEditUsers.whoSharesAccess') }}</span><h2 id="group-members-heading">{{ candidates ? $t('admin:groupsEditUsers.addPeopleGroup') : $t('admin:groupsEditUsers.members') }}</h2><p>{{ candidates ? $t('admin:groupsEditUsers.chooseExistingAccountsThen') : $t('admin:groupsEditUsers.personsAccessCombinesPolicies') }}</p></div><div class="group-actions"><v-btn v-if="candidates" variant="text" prepend-icon="mdi-arrow-left" @click="setMode(false)">{{ $t('admin:groupsEditUsers.currentMembers') }}</v-btn><v-btn v-else-if="canManage" variant="outlined" prepend-icon="mdi-account-plus-outline" :disabled="disabled" @click="setMode(true)">{{ $t('admin:groupsEditUsers.addMembers') }}</v-btn></div></div>
    <v-alert v-if="disabled && canManage" type="info" variant="tonal" class="mb-4">{{ lockReason || $t('admin:groupsEditUsers.saveResetPolicyDraft') }}</v-alert>
    <form class="group-directory-filters" @submit.prevent="searchNow"><v-text-field v-model="search" :label="candidates ? $t('admin:groupsEditUsers.findAccountAdd') : $t('admin:groupsEditUsers.searchCurrentMembers')" variant="outlined" hide-details clearable prepend-inner-icon="mdi-magnify" @update:model-value="queueSearch" /><v-btn variant="text" :loading="loading" @click="load">{{ $t('admin:groupsEditUsers.reloadMembers') }}</v-btn></form>
    <div v-if="selected.length" class="group-selection-bar"><strong>{{ $t('admin:groupsEditUsers.selected', { selectedCount: selected.length, interpolation: { escapeValue: false } }) }}</strong><v-btn variant="text" :disabled="disabled" @click="selected = []">{{ $t('admin:groupsEditUsers.clearSelection') }}</v-btn><v-spacer /><v-btn :color="candidates ? 'primary' : undefined" variant="flat" :disabled="disabled" @click="$emit('review', { action: candidates ? 'add' : 'remove', people: selected })">{{ candidates ? $t('admin:groupsEditUsers.reviewAdditions') : $t('admin:groupsEditUsers.reviewRemovals') }}</v-btn></div>
    <async-state v-if="loading" state="loading" :title="$t('admin:groupsEditUsers.loadingMembership')" /><async-state v-else-if="error" state="error" :title="$t('admin:groupsEditUsers.membershipCouldNotLoaded')" :message="error" :retry-label="$t('admin:groupsEditUsers.tryAgain')" @retry="load" /><async-state v-else-if="!directory?.items.length" state="empty" :title="search ? $t('admin:groupsEditUsers.noMatchingAccounts') : candidates ? $t('admin:groupsEditUsers.noAccountsAvailableAdd') : $t('admin:groupsEditUsers.noMembersYet')" :message="search ? $t('admin:groupsEditUsers.tryAnotherNameEmail') : candidates ? $t('admin:groupsEditUsers.createAccountsUsersThen') : $t('admin:groupsEditUsers.addPeopleWhenGroups')" />
    <template v-else><ul class="group-member-list"><li v-for="person in directory.items" :key="person.id" class="group-member-row"><input v-if="canManage" type="checkbox" :aria-label="$t('admin:groupsEditUsers.select', { name: person.name, interpolation: { escapeValue: false } })" :checked="selected.some(item => item.id === person.id)" :disabled="disabled || !person.canRemove || (selected.length >= 100 && !selected.some(item => item.id === person.id))" @change="select(person, ($event.target as HTMLInputElement).checked)" /><div class="group-member-person"><router-link v-if="canReadAccounts" :to="'/users/' + person.id">{{ person.name }}</router-link><strong v-else>{{ person.name }}</strong><span>{{ person.email }}</span></div><div class="group-member-state"><span>{{ person.isActive ? $t('admin:groupsEditUsers.activeAccount') : $t('admin:groupsEditUsers.inactiveAccount') }}</span><small v-if="!person.canRemove">{{ $t('admin:groupsEditUsers.protectedMembership') }}</small></div><v-btn v-if="!candidates" variant="text" icon="mdi-shield-search" size="small" :aria-label="$t('admin:groupsEditUsers.checkAccess', { name: person.name, interpolation: { escapeValue: false } })" @click="$emit('evaluate', { id: person.id, name: person.name })" /></li></ul><div class="group-pagination"><span>{{ $t('admin:groupsEditUsers.of', { value: offset + 1, total: Math.min(offset + directory.items.length, directory.total), total2: directory.total, interpolation: { escapeValue: false } }) }}</span><div class="group-actions"><v-btn variant="text" :disabled="offset === 0" @click="paginate(-1)">{{ $t('admin:groupsEditUsers.previous') }}</v-btn><v-btn variant="text" :disabled="offset + 25 >= directory.total" @click="paginate(1)">{{ $t('admin:groupsEditUsers.next') }}</v-btn></div></div></template>
  </section>
</template>
<script lang="ts">
import AsyncState from '@/components/common/async-state.vue'
import { fetchGroupMembers } from '../../helpers/group-workspace-api.ts'
import { getErrorMessage } from '../../helpers/root-ui-store.ts'
import type { GroupMembers, GroupMember } from '../../../shared/group-policy.ts'
export default {
  components: { AsyncState }, props: { groupId: { type: Number, required: true }, revision: { type: String, required: true }, disabled: Boolean, canManage: Boolean, canReadAccounts: Boolean, lockReason: { type: String, default: '' } }, emits: ['review','evaluate'],
  data() { return { candidates: false, search: '', offset: 0, selected: [] as Array<{ id: number; name: string }>, directory: null as GroupMembers | null, loading: false, error: '', sequence: 0, disposed: false, timer: null as ReturnType<typeof setTimeout> | null } },
  watch: { groupId: { immediate: true, handler() { this.candidates = false; this.search = ''; this.offset = 0; this.selected = []; void this.load() } }, revision() { this.selected = []; void this.load() } },
  beforeUnmount() { this.disposed = true; this.sequence++; if (this.timer) clearTimeout(this.timer) },
  methods: { async load() { const sequence = ++this.sequence; this.loading = true; this.error = ''; try { const result = await fetchGroupMembers(this.groupId, new URLSearchParams({ search: this.search || '', candidates: String(this.candidates), limit: '25', offset: String(this.offset) })); if (!this.disposed && sequence === this.sequence) this.directory = result } catch (error) { if (!this.disposed && sequence === this.sequence) this.error = getErrorMessage(error) } finally { if (!this.disposed && sequence === this.sequence) this.loading = false } }, queueSearch() { if (this.timer) clearTimeout(this.timer); this.timer = setTimeout(() => this.searchNow(), 250) }, searchNow() { if (this.timer) clearTimeout(this.timer); this.offset = 0; void this.load() }, paginate(direction: number) { this.offset = Math.max(0, this.offset + direction * 25); void this.load() }, setMode(candidates: boolean) { this.candidates = candidates; this.selected = []; this.search = ''; this.offset = 0; void this.load() }, select(person: GroupMember, checked: boolean) { if (this.disabled || !this.canManage || !person.canRemove || (checked && this.selected.length >= 100 && !this.selected.some(item => item.id === person.id))) return; this.selected = checked ? [...this.selected.filter(item => item.id !== person.id), { id: person.id, name: person.name }] : this.selected.filter(item => item.id !== person.id) } }
}
</script>
