apiVersion: v2
name: tsepistle
version: '0.1.0-alpha.1'
appVersion: '0.1.0-alpha.1'
description: tsEpistle, an independent community fork of Wiki.js.
keywords:
  - wiki
  - documentation
  - knowledge base
  - docs
  - reference
  - editor
type: application
home: https://github.com/PhilosophiMoonbeam/wiki
icon: https://raw.githubusercontent.com/PhilosophiMoonbeam/wiki/main/client/static/svg/icon-tsepistle.svg
sources:
  - https://github.com/PhilosophiMoonbeam/wiki
